### ISSUE TITLE
Copy/paste glyph from another FontForge window not working

### ISSUE THREAD

**Issue by ilius** [fontforge/fontforge#2663] opened 2016-04-01 13:56 UTC
I open two fonts in two FontForge windows, select a glyph in first window, copy, select a (empty) glyph in second window and paste. But it does not do anything.
Both fonts are Unicode BMP
I even tried opening one font in two windows, still not working

**Comment by ilius** [comment] 2016-04-01 15:55
Apparently it only works once!
So I have to close and re-open the second (target) file to paste another (range) of glyphs from first file

**Comment by frank-trampe** [comment] 2016-04-03 19:39
What platform?

**Comment by ilius** [comment] 2016-04-04 05:16
Debian GNU/Linux

**Comment by juanitogan** [comment] 2017-03-21 07:56
Seems to be an issue with the clipboard across all OSs.

I have the same/similar issue on Windows 10.  In general, I found that I can only paste into another font if I haven't done other edits there since opening it.  Otherwise, close it and reopen it.  I can then do multiple pastes as long as I don't fiddle with other things.  Yet, sometimes, this quits as well and it just won't work at all -- I have yet to figure the magic of that out.

Mac: #2528

**Comment by c0dehunter** [comment] 2018-07-05 12:29
This didn't help me.

**Comment by serhioV** [comment] 2018-07-30 09:21
does not work on Windows 10, version 08:20 UTC 31 JUL 2017

Copy one glypth from one font to another does nothing

**Comment by Artyrm** [comment] 2018-10-02 19:28
Same on win 7.

**Comment by jeffjohnson** [comment] 2018-12-14 13:03
For those who are still having problems with this, open the two fonts from the same fontforge instance and then you can copy/paste from one font to another. Tried on Elementary OS 5 (Juno, based on Ubuntu 16 LTS I believe).

**Comment by sakthikanth** [comment] 2019-03-04 10:21
It works for me when open another file from the same window instead of opening from the folder location.

Thanks,

**Comment by dimkanovikov** [comment] 2021-09-20 18:20
Hello from 2021 :)

And the issue is still here. So, thank you Jeff for the workaround you post here.

**Comment by animevietsub** [comment] 2023-07-02 05:39
It's fixed on win 7, if you click File -> Open, the new windows is able to copy.
![image](https://github.com/fontforge/fontforge/assets/25116853/d2ec07a0-3c42-4abf-a9f3-e32f19e0fffd)

**Closed** 2023-07-02 07:50 UTC

**Comment by 65fas** [comment] 2025-10-26 06:06
If you are as silly as me then I was trying to copy/paste while I had a different keyboard layout turned on other then the standard Latin/English. Obviously Ctrl + C/P won't get registered correctly then. Whoops!
