### ISSUE TITLE
SVG export flips glyphs

### ISSUE THREAD

**Issue by cyberwombat** [fontforge/fontforge#3140] opened 2017-08-18 16:11 UTC
When I use FF scripting to create SVG all the glyphs are flipped or 180 rotated. I tried with TTF and OTF.

I am using fontforge from HomeBrew on OSX Sierra. My version output shows:

````
Based on sources from 15:52 UTC 18-Aug-2017-D.
Based on source from git with hash:
fontforge 15:52 UTC 18-Aug-2017
libfontforge 20170818
````

The script I use:
````
#!/usr/local/bin/fontforge
Open($1)
Generate($1:r + ".svg")
````

Attached is a sample otf file which I run as:

````
convert.pe FontAwesome.otf FontAwesome
````

In the resulting SVG I look for "camera" and use that as my path in SVG.js. A fiddle is [here](http://jsfiddle.net/cyberwombat/wpsuxvnn/1/) as well as an attached SVG file.

Here's a related [SO post](https://stackoverflow.com/questions/13087903/command-line-tool-for-converting-ttf-otf-fonts-to-svg) with others having issue.

[test.svg.zip](https://github.com/fontforge/fontforge/files/1234952/test.svg.zip)
[FontAwesome.otf.zip](https://github.com/fontforge/fontforge/files/1234935/FontAwesome.otf.zip)

**Comment by tshinnic** [comment] 2017-08-18 21:12
Isn't this just the "which way is up?" problem?

OTF/TTF defines the origin at (0,0) as though at the bottom-left corner,
with +Y moving towards the top of the screen.  But SVG chose to set the
origin (0,0) at the top-left corner, with increasing +Y moving down towards
the *bottom* of the screen.  There's not a bug, but there's rather a change
of definitions.

If you're creating SVG source you will need to flip along the Y-axis
somehow to make the output look right.  I've done it two ways.  One way is
to just add an SVG transform() attribute to a <g> group surrounding each
individual glyph.  It is tricky a bit, but then somewhat cookbook.  Do it
with a script updating the SVG source.  The other way is to use some tool
to actually flip the individual coordinates in the path strings.  Again,
use a script if possible.

Perhaps Inkscape would be of help, but I've had the same sort of problem
there with +Y moving in opposite to what I thought it should be.

**Comment by cyberwombat** [comment] 2017-08-18 21:16
Ah that explains why. While I agree it's not a bug it seems that if 100% of people doing a ttf->svg conversion are going to need to flip either their svg (which proved too messy for me as it affected a lot of other transforms) or load the ttf in an editor and flip all the glyphs (which is what I did so I would have correct svg to work with) then I would tend to think that doing this conversion as part of the svg conversion process seems a given wouldn't you think?

**Comment by frank-trampe** [comment] 2017-11-29 15:33
So the problem here is that the existing behavior (which I think ought to have corrected geometry) is assumed by a lot of existing workflows. If we are to provide this feature, it must be in a non-disruptive way. I'm open to proposals.

**Comment by cyberwombat** [comment] 2017-11-29 16:30
Well a flag to flip would be nice. I guess it's your call as to what that flag is set to - it could default to current behavior to not break flows or could upgrade semver and flip by default providing flag to fix.

**Comment by skef** [comment] 2020-02-28 12:38
`Generate()`, whether in its native or Python form, outputs a font. When called with an `.svg` suffix it outputs an SVG-format font. That format is now largely outmoded and deprecated. 

What both the filer here and the folks at the StackOverflow link are doing is using `Generate` as a way to write out SVG glyphs in bulk. However, FontForge already has the glyph-level `export` function, in the UI and also both APIs. And when used to output an SVG it already flips the glyph with a transform. 

Even if it may be convenient for some users to use `Generate` for this purpose I don't think it makes sense to add a flip-flag. The resulting font would simply be wrong. Users who need SVGs of their glyphs should use `export`.

**Comment by skef** [comment] 2021-04-09 10:24
As I said last year, glyph-level export is the solution for this; there's a flag now. Closing this issue.

**Closed by skef** 2021-04-09 10:24 UTC
Labels: maybe-done, needs-info
