### ISSUE TITLE
Dialogs show up "too centered" on a multi monitor setup 

### ISSUE THREAD

**Issue by Pomax** [fontforge/fontforge#2381] opened 2015-06-18 16:55 UTC
Similar to https://github.com/fontforge/fontforge/issues/2256, but actually much easier to fix:  On a multi-monitor setup Fontforge will place dialog windows in the center of "the total screen width" rather than centered on the monitor fontforge itself is open in. On odd numbered monitor setups, that's a little funny, but on a dual setup, it puts the dialog half on screen 1 and half on screen 2, and that's really problematic =)

**Comment by larsenwork** [comment] 2015-06-19 08:00
So how's it easy to fix? :)

**Comment by Pomax** [comment] 2015-06-19 15:32
Don't confuse "easier" with "easy", they are absolutely different things. #2256 is hard because the only proper solution is to figure out of the positioning conflicts with other applications. Here, the problem is internal to FontFont and the solution requires not using the total display resolution to figure out where to place dialogs, but asking windows which screen it's on, and then using that screen's dimensions for dialog positioning.

**Comment by jtanx** [comment] 2015-06-19 15:37
See that's the problem, it's not a native app at all. As has been mentioned multiple times before, it uses X11 directly and rolls its own GUI toolkit. You're more than welcome to fix this if (a) you can fix the [X11 server](http://sf.net/p/vcxsrv) to work with multi-monitor setups, or (b) you can rewrite FF to use a standard GUI toolkit.

**Comment by Pomax** [comment] 2015-06-19 15:46
Not having been part of this project or having ever look at this issue tracker before yesterday, that is not something I can reasonably be expected to already know =)

I have no knowledge whatsoever of X11, but it sounds like this is a bug in X11 then, which should probably be filed upstream if that hasn't happened yet, so that rolling over to the next X11 update automatically fixes it for Fontforge.

That said, the "you're welcome to fix it yourself" comment is pretty low. You know damn well I don't have the skills to do so, which is why I filed an issue, not a PR. If this is a bug you know exists in X11, then I assume that because X11 is important to Fontforge, you've already filed this over on the X11 bug tracker, and this issue doesn't need to be solved by anyone working on the project, X11 will fix this. Just drop a link to that bug in this ticket and mark it as closed because eventually X11 will fix their bug. No need to be mean.

**Comment by larsenwork** [comment] 2015-06-19 16:46
@Pomax no-one is mean. I think the confusion comes from your 
> Similar to #2256, but actually much easier to fix
which frankly only makes sense to say if you have looked in the code and have an idea how to fix it :wink: 

@jtanx I'm asking this because I don't know: Is it (fairly easily) possible to make it so that dialogs always open in e.g. the left half of the view? This wouldn't (I assume) break anything for single monitor and would open on the left monitor in dual monitor setups which still isn't perfect but better than cut in half?

**Comment by Pomax** [comment] 2015-06-19 16:54
I think it's also the confusion between "easy" and "easier". Easier just means it's less complicated, it doesn't say anything about it being a simple thing to fix =/

**Comment by larsenwork** [comment] 2015-06-19 17:06
@pomax easy vs easier makes no diff - you can "say" so if you've looked in and know about the code :smirk: 

But no harm no foul :beers: 

@jtanx feel free to close this issue if the answer to my question above is no :+1:

**Comment by Pomax** [comment] 2015-06-19 18:48
small comment on the proposed solution: I'd rather have it centered across monitors than have FontForge do weird "half screen" positioning - better to either fix it by having X11 do the right thing that trying to work around an assumption about how many monitors people use.

So with that said: someone who clearly does know the code is probably in a better position than I am to hit up the X11 bug tracker and see if they're already tracking this. If not, that should probably be filed.

**Comment by ctrlcctrlv** [comment] 2015-07-08 13:39
It's not a bug in X11. Don't waste the X11 maintainer's time with this. It's a bug in whatever X emulator you are using. On GNU/Linux it works "fine" (actually it favors the first montior for new windows, but it most definitely does not stick things in the center of both monitors) because GNU/Linux correctly is using Xinerama. [XQuartz just pretends that your two monitors are one big monitor and relays that to X.](https://xquartz.macosforge.org/trac/ticket/797) Not X's fault it places the window in the wrong place.

Also @Pomax "That said, the "you're welcome to fix it yourself" comment is pretty low. You know damn well I don't have the skills to do so, which is why I filed an issue, not a PR." -- Don't worry, the current maintainers haven't a clue either. (I'm not any better.)

FontForge was written by a FOSS advocate as a retirement project, and that advocate (George Williams) then retired from his retirement project, leaving some application packagers and a whole bunch of "ideas guys" behind to try to maintain this 460,000+ line(*!*) project.

```
$ wc -l gdraw/*.c fontforge/*.c fontforgeexe/*.c|grep total
  465627 total
```

We're all doing our best. FontForge's development spans over 20 years and uses tons of old cruft no one understands. It's worse than working on COBOL - at least a lot of people wrote COBOL. Almost no one worked with the X11 libraries.

**Comment by jtanx** [comment] 2015-07-09 00:34
Yeah, I looked further into this, and in particular:

> -[no]multimonitors or -[no]multiplemonitors
    Create a screen 0 that **covers all monitors** [the primary monitor] on a system with multiple monitors. Fake XINERAMA data is created describing the individual monitors, (This is similar to the 'merged framebuffer' or 'pseudo-xinerama' mode provided by some drivers for the xorg X server). This option is currently enabled by default in -multiwindow mode. 

I tried `-nomultimonitors`and it does work (in terms of centering content on the primary display), but then it stops you from using the FontForge on the other monitors, presumably because those areas are now 'out of range'.

I would guess you would have to either:
* Improve multi-monitor support in some (unknown to me) manner through VcXsrv
* Add Xinerama support to FontForge to determine the presence of multiple monitors

**Closed** 2019-08-25 12:17 UTC
Labels: Windows, someday-maybe
