### ISSUE TITLE
crashes after a point referenced by Point Info is deleted

### ISSUE THREAD

**Issue by icecream17** [fontforge/fontforge#4528] opened 2020-12-12 23:28 UTC
- [x] The FontForge version and the operating system you're using
    - FontForge-2020-11-07,  Windows 10 Pro x64 bit
- [x] The behavior you expect to see, and the actual behavior
    - Crashes instead of not crashing.
- [x] Steps to reproduce the behavior
    i. Click the "Get Info..." option for a point
        ![image](https://user-images.githubusercontent.com/58114641/101998792-0caa8a80-3c9c-11eb-9602-78750c17454e.png)
        ![image](https://user-images.githubusercontent.com/58114641/101998817-32379400-3c9c-11eb-9279-ff5ee17dc152.png)
    ii. Delete the point
    iii. Wait around 2 or 3 seconds, then
        ![image](https://user-images.githubusercontent.com/58114641/101998830-5a26f780-3c9c-11eb-9e3d-f759da67ece8.png)
- [ ] \(optional) Possible solution/fix/workaround

**Comment by skef** [comment] 2020-12-13 00:51
This is totally a dup. I'll try to hunt down the other issue.

And it's not likely to be fixed unless we're willing to make the point info dialog modal.

**Comment by skef** [comment] 2020-12-13 06:55
Closed as duplicate of #2829. Also note #3489.

**Closed by skef** 2020-12-13 06:55 UTC
