### ISSUE TITLE
Export of a glyph as a SVG file fails on Windows 10

### ISSUE THREAD

**Issue by StefanPeev** [fontforge/fontforge#4691] opened 2021-03-29 06:57 UTC
I tried to export a glyph as a SVG file both through FontForge 20th Anniversary Edition and AppVeyor latest version and the results are:

- in Windows 7 - export is possible
- in Windows 10 - I receive a message "Save Failed"

What may be the reason for such results?

**Comment by jtanx** [comment] 2021-03-29 08:12
Please post a sample file. Just guessing, do you have permisions to save to the location you're trying? What if you try to save somewhere else?

**Comment by skef** [comment] 2021-03-29 08:15
Hard to say. The most likely candidate for the problem is the `fopen()` on line 392 of `fontforge/cvexport.c`. If you're in a position to compile you try changing that function to:

```
int ExportSVG(char *filename,SplineChar *sc,int layer, ExportParams *ep) {
    FILE *svg;
    int ret;

    svg = fopen(filename,"w");
    if ( svg==NULL ) {
        perror("SVG fopen error is:");
return(0);
    }
    ret = _ExportSVG(svg,sc,layer,ep);
    fclose(svg);
return( ret );
}
```
to see what it says.

**Comment by StefanPeev** [comment] 2021-03-29 17:51
> What if you try to save somewhere else?

The result is the same - Save Failed.

**Comment by StefanPeev** [comment] 2021-03-29 17:53
@skef No, I am not in position to compile... sorry.

**Comment by skef** [comment] 2021-03-29 19:32
> No, I am not in position to compile... sorry.

No shame in that—we aren't either. 

Once we get our ducks more in a row I'll try to remember to submit a draft PR and get you a build artifact to try out.

**Comment by skef** [comment] 2021-03-31 12:51
@StefanPeev See if you can unpack this (with archiver 7z) and make use of it: https://github.com/fontforge/fontforge/suites/2389141540/artifacts/50759798 . I added code analogous to`perror` above. If the problem reproduces we'll have a bit more information and I can add further diagnostics as needed. If not we can try to figure out why.

**Comment by StefanPeev** [comment] 2021-04-01 15:09
@skef Thank you! The ZIP archive MINGW64.zip is the decision. The problem is solved in the included in the ZIP archive version of FontForge.

**Comment by skef** [comment] 2021-04-01 16:10
That's not necessarily good news -- it could mean there's something about our usual packaging that's causing the problem. 

@jtanx any ideas? Should he try MINGW32.zip?

**Comment by StefanPeev** [comment] 2021-04-02 15:55
@skef I'm affraid that one of my students reported this error on Windows 10 even with FontForge in MINGW32.zip - see the picture...

![FontForge_SVG_Export_Error_on_Wnidows_10](https://user-images.githubusercontent.com/12949369/113431831-01af6d80-93e5-11eb-9c3c-7f331a2ab6e8.jpg)

**Comment by skef** [comment] 2021-04-02 17:00
@StefanPeev This could be progress. If they are able to try, see if they can reproduce the problem with the updated MINGW32.zip: https://github.com/fontforge/fontforge/suites/2408653119/artifacts/51301947 . I've added code to print the name of the file FontForge is attempting to save to. 

(This is probably the same URL so they should be careful to make sure they've got and are using the new version.)

**Comment by skef** [comment] 2021-04-12 21:01
@StefanPeev Have you had a chance to take another look at this?

**Comment by skef** [comment] 2021-04-19 01:42
Still hoping for more feedback on this @StefanPeev

**Comment by jtanx** [comment] 2021-05-14 09:16
Closing, feel free to reoepn if you want another shot at this.

**Closed by jtanx** 2021-05-14 09:16 UTC
Labels: Windows
