### ISSUE TITLE
No pop-up when hovering over a GSUB rule

### ISSUE THREAD

**Issue by dscorbett** [fontforge/fontforge#3550] opened 2019-03-17 15:57 UTC
Hovering over a rule in a subtable no longer pops up a visual representation of the rule, as it does in the 2017-07-30 version. I am using the 2019-03-17 version of FontForge on macOS Mojave 10.14.3.

To reproduce, open a font with a GSUB table. Open the “Font Info” window. Select the “Lookups” tab. Expand a GSUB lookup. Select a non-contextual substitution subtable. Click “Edit Data”. Hover over a rule. Nothing happens. In the previous version, it would show the glyphs in a pop-up.

<img width="544" alt="Pop-up in FontForge 2017-07-30 for a single substitution rule in Noto Sans" src="https://user-images.githubusercontent.com/1124347/54493861-e8453280-48aa-11e9-80f4-517dea5e7c45.png">

**Comment by skef** [comment] 2019-03-17 18:25
Interestingly, this does not seem to be a GGDKDraw problem, or at least it's not specific to GDK, GXDraw also doesn't display these. 

I haven't found an obvious change in the code but I'm still poking around.

**Comment by skef** [comment] 2019-03-17 19:25
Ah, ok, I think the problem is here in `GGadgetPopupTest()`:
```
    /* Is the cursor still in the original window? */
    if (GDrawGetPointerWindow(popup_info.gw) != popup_info.gw)
        return true;
```
I changed the function call in the guard from `GDrawGetPointerWindow(root)`, but I've tested with that and it doesn't solve the problem. 

I suspect the issue here is that a `GMatrixElement` gets its own window in some sense, and that's what is being returned by `GDrawGetPointerWindow()`. At least the size and offsets of the `GWindow` returned seem to imply that. So the fix is either to adjust the "base" assigned to `popup_info.gw` or change what we call or the logic in GDrawGetPointerWindow()`. 

@jtanx: a trick here is to do `GWindow ttt = GDrawGetPointerWindow(popup_info.gw);` right before the test and set a breakpoint right after, to be able to check the window being returned. Then it's just a matter of deciding on how the logic might be changed. Any ideas?

**Comment by jtanx** [comment] 2019-03-17 21:12
The question is, what changed so it no longer works?

The matrix window is a child window of the main window, so that comparison is failing, because it's returning the child window, whereas the popup comparison is expecting the main window. You can confirm this by checking the `parent` element on the window returned by `GDrawGetPointerWindow` (other ways to tell it's a child window is that there's an `is_toplevel` property, and that the `parent` window isn't the root window).

**Comment by skef** [comment] 2019-03-17 21:26
> The question is, what changed so it no longer works?

Unfortunately those lines (before the modification I mention) were added in:
```
commit 9fcd577ecc559bffc1e0c9b9357826fd0984d7bb
Author: Jeremy Tan <jtanx@outlook.com>
Date:   Mon Aug 15 13:31:48 2016 +0800

    ggadgets.c: Prevent popups from showing if mouse is over another window
    
    This prevents FontForge from showing a popup when the mouse is
    over a window that isn't the one that initiated the popup.
```
So that guard may never have worked, unless you remember having verified this style of popup earlier in the GGDKDraw development.

**Comment by skef** [comment] 2019-03-17 21:27
(Or, to put it a different way, "what changed" is that this test was added to fix some other issue.)

**Comment by khaledhosny** [comment] 2019-03-17 21:49
I reverted 9fcd577ecc559bffc1e0c9b9357826fd0984d7bb locally and indeed the popups show again.

**Comment by jtanx** [comment] 2019-03-18 08:01
In that case, the fix should be pretty simple, use `GDrawIsAncestor` to figure out if the window returned by `GDrawGetPointerWindow` is the current window, or a child of the window listed in the popup. The popups I were testing against were the ones you get when hovering over the font view, and also the one on the splash screen.

**Closed** 2019-03-18 08:42 UTC
