### ISSUE TITLE
Fontforge in Python Package Index (PyPI)

### ISSUE THREAD

**Issue by codingisacopingstrategy** [fontforge/fontforge#2048] opened 2015-01-17 17:36 UTC
Can fontforge be distributed on the [Python Package Index](https://pypi.python.org/pypi)?

This would make it trivial to install it for use in python scripts, and to use inside python virtual environments.

Cheers,

**Comment by felipesanches** [comment] 2017-11-01 23:09
This would be great!

**Comment by ctrlcctrlv** [comment] 2017-11-02 05:12
https://packaging.python.org/guides/packaging-binary-extensions/

**Comment by khaledhosny** [comment] 2019-07-23 01:17
I often found myself needing this for building my fonts (locally and on CI) and having FontForge Python module on PyPI allows getting newer version easily (e.g. on Travis antiqued Ubuntu distrivutions) and pinning to a specific version for reproduciblility.

With proper setup we can make the CI builders automatically upload wheel for release tags.

I can give the building infrastructure a try, put I can’t handle the PyPI account.

**Comment by skef** [comment] 2019-07-23 02:28
What's the "model" for this? Is the idea to do a build of the full repository but restricted at the top-end to the python modules (and so not the GUI)? Would `libuninameslist` be built first and linked in somehow? Will the build be static (because otherwise the libraries would need somewhere to go)?

**Comment by jtanx** [comment] 2019-07-23 08:45
Yeah it's a massive PITA because of all the dependencies, how exactly you package that into a standalone(?) wheel is something I'd like to see.

**Comment by khaledhosny** [comment] 2019-07-23 10:48
My plan is to add a `setup.py` file that builds the `*hook.c` files and links to `libfontforge` (and the other two required libraries until they are merged together). Calling `setup.py` would happen after a normal build, and it can then be used to generate wheels and other Python dist packages to be uploaded to PyPI.

**Comment by jtanx** [comment] 2019-07-23 10:50
So confirming, the wheel includes `libfontforge` (and links to it dynamically? statically?), or is that just expected to exist? If it does include it, what about all third-party dependencies?

**Comment by anthrotype** [comment] 2019-07-23 10:51
yes, all shared libraries including third party deps can be packaged up into a wheel, using auditwheel tool

https://github.com/pypa/auditwheel

**Comment by anthrotype** [comment] 2019-07-23 10:52
and https://github.com/matthew-brett/delocate for macOS

**Comment by khaledhosny** [comment] 2019-07-23 10:53
I’d go for statistic linking when possible, but dynamic linking with bundling of `libfontforge` is OK as a last resort.

**Comment by skef** [comment] 2021-04-12 23:38
reverse-dup of #4377.

**Closed by skef** 2021-04-12 23:38 UTC
Labels: feature
