### ISSUE TITLE
Big Sir Fontforge denied access

### ISSUE THREAD

**Issue by abonagura** [fontforge/fontforge#4897] opened 2022-01-27 04:06 UTC
I have tried EVERYTHING! I’ve tried all the previous work around a for catilina and I can not grant access to fonforge on Mac OS: big sir

**Comment by ctrlcctrlv** [comment] 2022-01-27 05:02
To explain why I tagged your issue dubious, it's because "I have tried EVERYTHING" is not helpful to us. What did you try? What happened? For some reason I'm imagining an infomercial—"I've tried EVERYTHING to lose weight!", then a bariatric surgeon appears. "No you haven't! Mexican gastric bypass only $4999!"

I kid, certainly, but please enumerate "EVERYTHING".

Also, it's Big **Sur**.

**Comment by eddjcaine** [comment] 2022-01-28 11:32
This seems like a super place. 

I'm having an issue importing fonts into FontForge - the Import dialogue states "Unauthorized Operation not permitted" when I try to browse anywhere. I'm using Big *cough* **Sur**.

I have tried to give access to files using the Security and Privacy preference pane but there seems to be no way to add FontForge to the list.

Any ideas would be appreciated. Pedantry will be punished.

Fanks
Edd

**Comment by ctrlcctrlv** [comment] 2022-01-29 12:38
Closing as duplicate of #4082. Could reopen if demonstrated to be substantially different.

**Closed by ctrlcctrlv** 2022-01-29 12:38 UTC
Labels: Mac OS X, dubious
