### ISSUE TITLE
Interpolation leaves much to be desired

### ISSUE THREAD

**Issue by Kelvinsong** [fontforge/fontforge#2163] opened 2015-03-23 22:58 UTC
Currently interpolation is workable but very difficult to use. Would it be too hard to add the following capabilities:

* Set first point to top-left-most point for all glyphs before interpolating
* Provide an easy way to order contours (the order they’re listed in the sfd source) in multi-contour glyphs like ‘ % ’
* Average OS2 metrics (currently they are all lost)
* Average kerns (currently they are all lost)
* Copy GSUB tables if possible (currently they are all lost)
* Clear “point mismatch” errors in the warnings dialog every time interpolation operation is run to prevent the same errors from being shown twice

**Comment by adrientetar** [comment] 2015-03-25 22:18
> Set first point to top-left-most point for all glyphs before interpolating

Select all glyphs, Element > Simplify > Canonic contour. Normalization of starting shouldn’t be done automatically anyway.

**Comment by Kelvinsong** [comment] 2015-03-27 21:47
got it, what about the rest?

**Comment by davelab6** [comment] 2015-03-27 22:08
Do the rest yourself in Python :(

**Comment by davelab6** [comment] 2015-03-27 22:09
Or export UFOs and use MutatorMath

**Comment by davelab6** [comment] 2015-03-27 22:09
Or export UFOs and use Metapolator :)

**Comment by Kelvinsong** [comment] 2015-03-29 19:52
that is not a solution…if y’all don’t think interpolation is not a priority just say so then…

**Comment by davelab6** [comment] 2015-03-29 19:54
I think it is so important I founded the metapolator project and put
significant funding into it.

**Comment by Kelvinsong** [comment] 2015-03-29 21:49
oh! That sounds cool though I still don’t really get how it works. But it says it’s not released? Where do I download it
&& does it do regular interpolation or do I have to turn my font into a “skeleton” font or whatever it’s called I’m asking because I’m currently designing an open source serif family in my repository

**Comment by adrientetar** [comment] 2015-03-29 22:44
I use instance generator from the FDK, no need to duplicate existing good tools into FF (but if you want to do so, patches welcome).

**Comment by davelab6** [comment] 2015-03-30 13:11
It's not released. You can get involved in development to use it or wait,
and use fdk meanwhile. It works on regular UFOs.

**Comment by Kelvinsong** [comment] 2015-03-31 02:48
the Adobe Font Development Kit for OpenType (AFDKO) Overview doesn’t say anything about interpolation tho?¿ I’m confused sorry

**Comment by davelab6** [comment] 2015-03-31 03:05
Fdk processes UFO into OTF.

MutatorMath interpolates UFO

**Comment by adrientetar** [comment] 2015-03-31 06:20
Use [makeInstancesUFO](https://github.com/adobe-type-tools/afdko/blob/master/FDK/Tools/SharedData/FDKScripts/makeInstancesUFO.py) from the FDK. You first need to prepare your font for interpolation, export UFO and create a designspace file [similar this one](https://github.com/adobe-fonts/source-serif-pro/blob/master/RomanMasters/SourceSerifPro.designspace) that quantifies stuff like the weight of each of your masters.

> Fdk processes UFO into OTF.

That's makeotf.

**Comment by adrientetar** [comment] 2015-03-31 16:47
Duplicate of #1149.

**Closed by adrientetar** 2015-03-31 16:47 UTC
Labels: duplicate
