### ISSUE TITLE
Can't install FontForge

### ISSUE THREAD

**Issue by StudioSudo** [fontforge/fontforge#5102] opened 2022-09-07 15:15 UTC
Upon opening 
FontForge-2022-03-08-74e2eca.app.dmg
I get the error 
"FontForge" cannot be opened because the developer cannot be verified."

<img width="273" alt="Screenshot 2022-09-07 at 16 07 26" src="https://user-images.githubusercontent.com/113043918/188914986-ce2c8967-1f42-4b6d-8ec9-e848222a26cf.png">

Any help resolving this would be great
Thanks

**Comment by ctrlcctrlv** [comment] 2022-09-11 05:26
Duplicate of #4082…although it seems closed. I'll reopen it given your comment.

**Closed by ctrlcctrlv** 2022-09-11 05:26 UTC
