### ISSUE TITLE
Option to remove Ascent and Descent guides

### ISSUE THREAD

**Issue by ghost** [fontforge/fontforge#4274] opened 2020-04-12 05:53 UTC
This applies to both TrueType and bitmap fonts,

I personally hate the Ascent and Descent guides because the values of them are not actually even relevant to my fontdevelopment.

The numerical size values (aside from advance widths) that are relevant to me are:
* Em Size (not a height or width, but a reference size used in ppem "pixels per em" values) for example 2048
* WinAscent (the font top) for example 1884
* WinDescent (the font bottom) for example 514

As for all the others:
* Ascent and Descent are not relevant (they're not even saved in the TrueType file, only their sum, Em Size, is)
* I set Typo Line Gap and HHead Line Gap to 0
* I set Typo Ascent and HHead Ascent to WinAscent
* I set Typo Descent and HHead Descent to WinDescent

So, I don't want to see the Ascent and Descent guides because they aren't relevant to anything I do in my fontdevelopment unless it just so happens that the em size is the same as font height, which in many fonts it isn't. I would like instead to see WinAscent and WinDescent guides because they are the ones that determine the actual boundaries of height.

**Comment by yuiijjjjjjjjjjj** [comment] 2020-04-12 07:32
I marque this as CRITICAL because I'm really tired of seeing Ascent and Descent guides!

**Comment by frank-trampe** [comment] 2020-04-12 10:38
We might accept a pull request for this if there is a good reason for it and it is done in a way that does not change default behavior (maybe a preference checkbox that hides the guides in question), but let's talk this through and let others weigh in. Ascent and descent in the `hhea` table are intent-based values. If you want guides at the vertical positions you have stated for WinAscent and WinDescent, surely you could just set ascent and descent to those values?

**Comment by yuiijjjjjjjjjjj** [comment] 2020-04-12 10:40
If I change the Ascent and Descent values then their sum (Em Size) would change, which would change the size of the entire font. And changing it back for each release isn't exactly the most convenient fontdevelopment method.

**Comment by yuiijjjjjjjjjjj** [comment] 2020-04-12 10:43
The fallacy of FontForge's implementation is how it assumes two heights add up to the em-size, and enforces it on users. In my case em-size is a size, not a height, and it isn't split into anything but the units, so the Ascent and Descent guides are useless.

**Comment by skef** [comment] 2020-04-12 10:49
Probably wouldn't be much work to split out the colors for vertical and horizontal coordinate lines and then those users who don't want to see the former could just the color to white/transparent.

**Comment by yuiijjjjjjjjjjj** [comment] 2020-04-12 11:49
> Probably wouldn't be much work to split out the colors for vertical and horizontal coordinate lines and then those users who don't want to see the former could just the color to white/transparent.

What?

**Comment by frank-trampe** [comment] 2020-04-12 11:51
@yuiijjjjjjjjjjj, the em size is also an intent-based value. What is the specific problem with your ascent and descent aligning to the em size?

**Comment by yuiijjjjjjjjjjj** [comment] 2020-04-12 11:52
> @yuiijjjjjjjjjjj, the em size is also an intent-based value. What is the specific problem with your ascent and descent aligning to the em size?

The em-size is only a value, not a height or width, while Ascent and Descent that sum to the em-size are completely irrelevant in my fontdevelopment, and they don't even save in TrueType.

**Comment by skef** [comment] 2020-04-12 11:55
If you go to File -> X Resource Editor -> Outline View there is a setting for "Coordinate Line Color" if you set this to white (or whatever your background color is) that will make all of the coordinate lines invisible. 

Now, you don't want all the lines to be invisible, just certain lines. You could actually solve this problem for yourself by doing that and adding whatever you want back into the guide layer, of course. But presumably you're thinking of a more convenient interface. 

(Still, doing that plus adding what you want back in with the guide layer is probably your best bet for at least the short term.)

**Comment by yuiijjjjjjjjjjj** [comment] 2020-04-12 11:58
Would this affect the bitmap grid? (In bitmaps, the problem is similar, with Ascent and Descent not being useful. WinAscent and WinDescent should be rounded to pixel the same way GDI does)

**Comment by skef** [comment] 2020-04-12 12:03
Looks like the setting for the Bitmap View is File -> X Resource Editor -> Bitmap View "Guide color", but if you're going to use the grid at all you should set that to the same as the grid color to remove the contrast. 

I've barely used the bitmap font UI at all so beyond that I'm not going to be able to offer much advice.

**Comment by skef** [comment] 2020-04-12 12:05
(It doesn't look like the bitmap view has a configurable, separate guide layer anyway.)

**Comment by frank-trampe** [comment] 2020-04-12 12:22
@yuiijjjjjjjjjjj, intent-based means that the author can choose it and that it is not necessarily bound to glyph geometry. The em size affects internal unit calculations, but it does not lock you into particular vertical metrics. I'm not sure why we use ascent and descent rather than the separate user-provided em size for Truetype em size, but we cannot easily change it now.

I still do not understand why you want to set an em size that does not correspond to the space between your ascent and descent lines of preference. Could you perhaps post a visual example?

**Comment by yuiijjjjjjjjjjj** [comment] 2020-04-12 13:27
That's because the ppem size is the definitive unit of measure, related to the em size. If you have 19ppem text and 2048 units per em, then 19 pixels is the em which is 2048 units, and therefore one pixel is 2048/19 units. If you increase em-size, the entire font reduces in size. The font height (WinAscent+WinDescent) is independent of the em-size, and you wouldn't necessarily want 19ppem text to have a height of 19 pixels, because the em size (in this case 19 pixels) is "intent-based" while the WinAscent and WinDescent values directly influence how the font is constructed because the box drawing characters are related to the font top and font bottom, and exceeding the font top or font bottom will result in clipping in reasonable rendering engines.

**Comment by frank-trampe** [comment] 2020-04-12 16:06
That's not really a visual example, and I still don't understand what you are saying. Given that, as you say, the WinAscent and WinDescent values are not coupled to the main ascent and descent values, I don't understand why you would not set the main ascent and descent values and (implicitly) the `head` em size to correspond to the design intent.

As I've said before, we could likely talk through a patch if this is actually a problem, but we first need to know precisely what the problem is. I would continue to recommend that you provide a specific example with visuals in which computing `unitsPerEm` in `head` from the native ascent and descent values yields bad results.

**Comment by yuiijjjjjjjjjjj** [comment] 2020-04-12 16:44
Ok here is a visual example.

On the left: Standard DMCA Sans Serif 9.0-20252. WinAscent: 1884, WinDescent: 514, em-size: 2048.
On the right: the em-size is changed to 2398, which is the sum of WinAscent and WinDescent, which is the font height.

![image](https://user-images.githubusercontent.com/63473040/79074567-74fc3300-7ced-11ea-8d2e-b5ac4afb2f04.png)

By changing the em-size, the font became smaller! This is undesirable because a smaller font can be less readable, and professional documents would break when the font would be updated.

**Comment by frank-trampe** [comment] 2020-04-12 19:39
Yes, but you can simply change the ascent and descent to get the result you want. I still think that this problem is at most whether you want those visible in the charview or not, such that the originally proposed solutions achieve what you want.

**Comment by yuiijjjjjjjjjjj** [comment] 2020-04-13 04:19
> Yes, but you can simply change the ascent and descent to get the result you want. I still think that this problem is at most whether you want those visible in the charview or not, such that the originally proposed solutions achieve what you want.

No, because then the em-size would change as well.

**Comment by frank-trampe** [comment] 2020-04-13 20:50
I'm saying that you ought to set the ascent and descent to generate the em size you want (as you are probably already doing) and then to submit a patch just for the guide visibility if the existing options for suppression are unsatisfactory. Given that nobody else is likely to want to hide the design intent bounding box (and I still don't understand why it's such a negative for you to have it), I think that it is fine to make it a preference-file-only setting (with no preference pane checkbox).

**Comment by yuiijjjjjjjjjjj** [comment] 2020-04-14 05:32
The "design intent bounding box" is USELESS to my fontdevelopment. If it's useless then it's a distraction. I don't want "intent"ional guides that have a completely arbitrary sum to em-size, I only want vertically, aside from the baseline, the WinAscent and WinDescent (the hard boundaries).

**Comment by yuiijjjjjjjjjjj** [comment] 2020-04-14 09:21
Here are the specific vertical metrics of DMCA Sans Serif:

Font bottom: -514 units
Font top: 1884 units
Font height: Font top - Font bottom = 2398 units

This has NOTHING to do with the FontForge's conception of Ascent and Descent.

In x ppem the font top would be the rounded value of 1884÷2048×x pixels up from the baseline, and the font bottom would be the rounded value of 514÷2048×x pixels down from the baseline.

**Comment by fundamentals-fontdevelopment** [comment] 2020-06-07 17:10
This is indeed extremely important. Why have two values that are completely arbitrary and don't correspond to literally anything in the font?

**Comment by ctrlcctrlv** [comment] 2020-06-08 18:39
This problem, again, is simply one of display. Why have the values? Someone might be using FontForge to export OTF from TTF. So when if you are right that the values don't matter in TTF, which I haven't verified, they aren't going to be removed. 

A workaround right now would be to put guidelines down on the values you are interested in (so, it seems, WinAscent and WinDescent)

A user preference to change the display of default guidelines is the maximum acceptable fix for this issue. Removing the values in TTF is not going to happen.

**Comment by fundamentals-fontdevelopment** [comment] 2020-06-11 07:14
> Why doesn't it work to set ascent equal to WinAscent, and descent equal to WinDescent?

It's impossible because Ascent and Descent sum to the em-size. You can't possibly have a+b=2048, a=1884, b=514, because it's mathematically contradictory.

**Comment by ctrlcctrlv** [comment] 2020-06-11 16:30
Well why does the em-size need to be 2048?

**Comment by fundamentals-fontdevelopment** [comment] 2020-06-11 19:09
> 
> 
> Well why does the em-size need to be 2048?

The em-size is a critical part of the font and the entire scale depends on it. A 16ppem font will have the em-size be 16 pixels. The WinAscent and WinDescent are font height boundaries set relative to the origin baseline, so for example in case of 1884 and 514 respectively, the font top is 15 pixels upwards and the font bottom is 4 pixels downwards, making the font height 19 pixels in 16ppem. The maths wouldn't work out to be metric-compatible if any of em-size, WinAscent and WinDescent were to be changed.

**Comment by fundamentals-fontdevelopment** [comment] 2020-06-11 19:34
So, the "24 pixel outline" and such are vague. 24 pixel what?

• If it stands for the em-size (ppem), then to show the entire font height the boxes would have to change size depending on the font height.  
• If it stands for the font height, then the boxes would remain the same size and the glyphs would be scaled within the font height boundaries.

**Comment by ctrlcctrlv** [comment] 2020-06-11 19:36
Wait...are you saying that a font with em-size 1024 will appear half the size of one at 2048 at the same point size? I really don't think that's right...

**Comment by ctrlcctrlv** [comment] 2020-06-11 19:36
We're talking about UPM, right?

**Comment by fundamentals-fontdevelopment** [comment] 2020-06-12 03:53
> Wait...are you saying that a font with em-size 1024 will appear half the size of one at 2048 at the same point size? I really don't think that's right...

It would appear double the size if nothing else is changed.

**Comment by skef** [comment] 2021-04-09 10:20
The ascent, descent, baseline, and zero-line are painted in the `CoordinateLineColor`. The width line has its own color. I can see breaking out ascent and descent into their own color like width to close this.

**Closed** 2022-01-20 12:01 UTC
