### ISSUE TITLE
fontforge produces empty .ttf file

### ISSUE THREAD

**Issue by vbarbarosh** [fontforge/fontforge#5003] opened 2022-05-05 10:47 UTC
Latest version of fontforge was used. A font was downloaded from https://fonts.google.com/noto/specimen/Noto+Sans+SC .
The resulting `a.ttf` file is suspiciously small. I expect it to be at least 9M in size.

```
docker run --rm -i ubuntu bash << 'EOF'
set -x -o nounset -o errexit -o pipefail
cd
apt update
DEBIAN_FRONTEND=noninteractive apt-get install -y curl unzip cmake g++ \
    libjpeg-dev libtiff5-dev libpng-dev libfreetype6-dev libgif-dev \
    libgtk-3-dev libxml2-dev libpango1.0-dev libcairo2-dev libspiro-dev \
    python3-dev ninja-build cmake build-essential gettext
curl https://fonts.google.com/download?family=Noto%20Sans%20SC -o noto.zip
curl https://codeload.github.com/fontforge/fontforge/zip/refs/heads/master -o fontforge-master.zip
unzip noto.zip
unzip fontforge-master.zip
mkdir fontforge-master/build
cd fontforge-master/build
cmake -GNinja -DENABLE_GUI=0 ..
ninja
bin/fontforge -lang=ff -c 'Open($1);Generate($2)' ~/NotoSansSC-Regular.otf a.ttf
ls -alh ~/NotoSansSC-Regular.otf a.ttf
EOF

[...]

+ bin/fontforge -lang=ff -c 'Open($1);Generate($2)' /root/NotoSansSC-Regular.otf a.ttf
Copyright (c) 2000-2022. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20220308
 Based on sources from 2022-05-05 10:36 UTC-D.
The following table(s) in the font have been ignored by FontForge
  Ignoring 'VORG' vertical origin table
No glyph with unicode U+05140 in font
No glyph with unicode U+051c9 in font
No glyph with unicode U+055c0 in font
No glyph with unicode U+079ca in font
No glyph with unicode U+088cf in font
No glyph with unicode U+096a3 in font
+ ls -alh /root/NotoSansSC-Regular.otf a.ttf
-rw-r--r-- 1 root root 8.1M Oct 22  2018 /root/NotoSansSC-Regular.otf
-rw-r--r-- 1 root root 6.5K May  5 10:37 a.ttf
```

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by ctrlcctrlv** [comment] 2022-05-05 12:09
Noto CJK fonts do not work and will probably never do, sorry. Closing as duplicate of #4453. FontForge is not a generic SFNT transformation program, despite often being used that way.

**Closed by ctrlcctrlv** 2022-05-05 12:09 UTC

**Comment by ctrlcctrlv** [comment] 2022-05-05 12:12
Well, that's perhaps a bit too pessimistic.

What I'm trying to say is that highly professional fonts push the standard to its breaking point, and do things that are either underdocumented or undocumented. Because FontForge doesn't act as an SFNT transformer (keeping around SFNT tables as they are) but translates everything to its internal format then back to SFNT, you see what you see.

Given Noto CJK is still broken two years later, I'm guessing fixing it is hard. But I shouldn't say it'll probably never work, that's too pessimistic.
