### ISSUE TITLE
Can't import fontforge module from Python. 

### ISSUE THREAD

**Issue by fmotion1** [fontforge/fontforge#5307] opened 2023-10-29 01:22 UTC
### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [x] Screenshot

![pwsh_tfQbnxLv9C](https://github.com/fontforge/fontforge/assets/33441569/928cf5ec-8b38-4cce-afe9-403e69e4e3a4)

- [x] The FontForge version and the operating system you're using

FontForge v2023.01.01
Windows 10 Pro x64 Version 22H2 (Build 19045.3448)

- [x] The behavior you expect to see, and the actual behavior

I expect fontforge to import. If it doesn't import, I expect it to be installable via pip.

- [x] Steps to reproduce the behavior 

Download FontForge and then try to import it in a python script within a VENV.

- [ ] \(optional) Possible solution/fix/workaround

Any help greatly appreciated!

**Comment by ctrlcctrlv** [comment] 2023-11-24 00:26
Duplicate of #4377. You need MinGW Python.

**Closed by ctrlcctrlv** 2023-11-24 00:26 UTC
