### ISSUE TITLE
Crashes Everywhere: When opening .otf files or clicking "New" in the first dialog box

### ISSUE THREAD

**Issue by strablonsky** [fontforge/fontforge#5006] opened 2022-05-05 23:47 UTC
## The issue

Hello all! I've been using FontForge with great success in the past few months. However there's an issue that I haven't been able to resolve.

I was editing a font when FontForge crashed. Afterwards, every time I try to open and .otf file, or if I click "New" in the following dialog box...

<img width="481" alt="Screen Shot 2022-05-05 at 20 42 34" src="https://user-images.githubusercontent.com/105024517/167044206-55c3441d-4cff-47af-a0cb-03c04e3128c9.png">

...FontForge crashes immediately. 

<img width="372" alt="image" src="https://user-images.githubusercontent.com/105024517/167043826-c11860b3-4350-43e0-a9aa-1ee6ee0943a5.png">

I've tried:

- Restarting my computer
- Uninstalling and installing it again

What can I do?

## System and version

- FontForge: I've downloaded the latest version
- Macbook: macOS Monterey 12.3.1 - M1max
<img width="687" alt="image" src="https://user-images.githubusercontent.com/105024517/167044502-85e2631a-b973-4c9b-b5f5-fb903339b3e6.png">

**Comment by strablonsky** [comment] 2022-05-05 23:54
## Fixed it

I edited the _prefs_ file in ~/.config./ and changed AntiAlias from 0 to 1

<img width="375" alt="image" src="https://user-images.githubusercontent.com/105024517/167045120-0ffed49d-cb40-4dde-a524-c6ca1ddea9b1.png">

**Comment by ctrlcctrlv** [comment] 2022-05-08 14:41
Closing as duplicate of #4959, where I posted that workaround.

**Closed by ctrlcctrlv** 2022-05-08 14:41 UTC
