### ISSUE TITLE
Some kerns wont generate.

### ISSUE THREAD

**Issue by jpittman43** [fontforge/fontforge#5011] opened 2022-05-09 16:31 UTC
I have Fontforge 20220308
![How it is suppose to look](https://user-images.githubusercontent.com/105231420/167455136-fa6243a9-c1bd-452e-a995-1d31c6335b3d.jpg)
![This is what it does](https://user-images.githubusercontent.com/105231420/167455147-af10cc31-b2f9-4539-a688-e8c2e863a8cc.jpg)

When it is in the program it kerns correctly but when it is generated into a TTF C E L F all ignore close up kerning.

**Comment by ctrlcctrlv** [comment] 2022-05-10 03:57
What are your export options

**Comment by jpittman43** [comment] 2022-05-10 05:26
![generate](https://user-images.githubusercontent.com/105231420/167548496-e9c760f0-8f3b-4f63-a463-defa3fd53530.jpg)

**Comment by ctrlcctrlv** [comment] 2022-05-10 10:44
Not what I meant, sorry.

These, please:

![image](https://user-images.githubusercontent.com/838783/167611377-949bcaa6-1fdd-40cf-a0a8-2f0c6b72be4c.png)

**Comment by jpittman43** [comment] 2022-05-10 12:48
![options](https://user-images.githubusercontent.com/105231420/167632036-c966af75-dfd0-4d41-9378-3a3cb1e9e8fe.jpg)

**Comment by ctrlcctrlv** [comment] 2022-05-10 15:05
Try to tick "Windows-compatible kern" and "Old style kern".

**Comment by ctrlcctrlv** [comment] 2022-05-10 18:02
OK, I'm gonna need to know what program you're trying it in, and if you could upload the SFD that'd help too.

**Comment by jpittman43** [comment] 2022-05-10 18:24
Microsoft Office 2019

**Comment by jpittman43** [comment] 2022-05-10 18:26
I can't upload a sfd

**Comment by jpittman43** [comment] 2022-05-10 19:28
I think I would have to send it by email. It's not a supported file.

**Comment by ctrlcctrlv** [comment] 2022-05-10 19:41
Unsupported files can be zipped.

**Comment by jpittman43** [comment] 2022-05-10 21:01
[trouble.zip](https://github.com/fontforge/fontforge/files/8664951/trouble.zip)

**Comment by jpittman43** [comment] 2022-05-12 19:37
[trouble.zip](https://github.com/fontforge/fontforge/files/8682043/trouble.zip)

**Comment by ctrlcctrlv** [comment] 2022-05-12 20:19
Why do you have so many tables?

![image](https://user-images.githubusercontent.com/838783/168160435-4bccf788-f9a9-4f46-98c0-db1c5e89b2f4.png)

Don't worry, @khaledhosny [had to teach me this also](https://github.com/fontforge/fontforge/issues/3435#issuecomment-465940407), years ago. (#3435)

> Multiple subtables are supported, but multiple subtables where character coverage overlap will not do what you expect; since a character that is covered in one subtable will be skipped for all subsequent subtables. Either merge the subtables or split them into different lookups.
>
> There is no FontForge issue here, FontForge is compiling the GPOS lookups as you created them faithfully, but your lookups don’t do what you think they are doing. I doubt that you will find any implementation where your GPOS kerning works, but even if you do it is still not a FontForge issue.
>
> For better or worth, FontForge representation of OpenType lookup is very close to the metal with little abstraction, this can make it clumsy to use at times, but on the other hand you can create pretty much any lookup supported by the standard (which is not the case for some other higher level representations).

> [...]

> Again, your kerning lookups are wrongly setup. Either merge your subtables into one, or move each subtable into a separate lookup. Nothing to be fixed in FontForge, it is correctly compiling your lookups.

Closing as user misunderstood OT spec, duplicate of #3435.

**Closed by ctrlcctrlv** 2022-05-12 20:19 UTC
