### ISSUE TITLE
Crashes on startup when disabling anti-alias in view menu

### ISSUE THREAD

**Issue by noisecrime** [fontforge/fontforge#5097] opened 2022-09-02 05:06 UTC
Tried disabling anti-alias option under the view menu.

I think FontForge crashed shortly afterwards.
However ever since that change FontForge would crash on start up every time.
The crash occurred after the  'Open Font' dialog and would happen regardless of loading a font or creating a new one.

I was able to track down the fontforge preferences file in user/roaming and located the 'antialias' option, which I set from 0 back to 1.
After that change, fontforge would open and ran fine.

In conclusion then on my PC disabling 'anti-alias' option would result in FontForge crashing on startup.

I would suggest maybe adding a method to reset the prefs in the 'Open Font' dialog box that pops up when you launch FontForge. That would have saved me some time in trying to fix the issue and might also work for fixing other preference related problems. Perhaps make a back up of the current prefs, so users can have a reference to their old preferences.

Version: 20220308 11:23 ( win 10 )

Edit: typo that had pres instead of preferences

**Comment by skef** [comment] 2022-09-02 05:23
In practice that button would only help with crashes associated with the FontView but not associated with the open file dialog, which is a pretty narrow category that this problem just happens to fall into.

**Comment by noisecrime** [comment] 2022-09-02 16:26
True, it was just a suggestion that would put the option in a user facing position that they are likely to be able to access.

Assuming the crash bug I experienced is not a wide reaching issue that many users run into ( I mean if it was why wouldn't you just enforce anti-alias to true and remove it from the settings that users can change? ), I feel that such a showstopper crash bug due to changing a display setting needs a simple solution for users to be able to fix themselves.

If there is a better way to deliver and present to users a way to reset the preferences than that's great. Otherwise I suspect that many users who run into this crash bug will not have the knowledge to fix it themselves.

**Comment by notpeter** [comment] 2022-09-10 19:50
Same immediate crash when trying to disable Anti-Aliasing, but under MacOS.
 
For anyone who finds this, the location of these preferences on MacOS is `~/.config/fontforge/prefs`

So just
```bash
rm ~/.config/fontforge/prefs 
```

And FontForge.app will no longer crash on startup.

**Comment by ctrlcctrlv** [comment] 2022-09-11 05:23
Duplicate of #4959, which has a better workaround at https://github.com/fontforge/fontforge/issues/4959#issuecomment-1079701267.

**Closed by ctrlcctrlv** 2022-09-11 05:23 UTC

**Comment by noisecrime** [comment] 2022-09-11 05:38
Disappointed this is closed and the issue it duplicates is also closed since clearly the problem remains.

If there is a bug fix why was it completed in April yet in the latest version I downloaded a coupe of weeks ago the bug persists?

If the bug fix has not been pushed to master why not?

If the bug fix is not actually addressing the problem are the developers seriously suggesting a crash bug that makes the application unusable and is only fixable by the following is a viable solution?

1. Users who bother to search the github issues for a solution.
2. User who bother to search the github closed issues to find a solution.
3. Users who understand what preferences are, where they are stored and how to edit them.


This seems to be wholly unacceptable approach to software development, especially for a setting that an end user could easily toggle on/off when experimenting with the application. 

That is not to say I don't apricate that fixes can take time to implement and test, nor am I dismissing the obvious effort put into this amazing project by all its contributors. I just find it frustrating that such a simple change in the preferences can effectively cripple the app and the current solution seems to require users first find it, second understand and are willing to implement it.

**Comment by ctrlcctrlv** [comment] 2022-09-11 05:45
It's in master. Just not in a current release. You can download a master build.

**Comment by noisecrime** [comment] 2022-09-11 07:14
Ah, ok guess that makes sense - just assumed Master and release were in sync.
Thanks
