### ISSUE TITLE
FontForge hangs when changing the weight of some glyphs

### ISSUE THREAD

**Issue by mbandsmer** [fontforge/fontforge#5012] opened 2022-05-11 21:41 UTC
As found in FontForge 20220308 (Windows version):
Changing the weight of some glyphs causes FontForge to hang with 100% CPU usage.

Steps to reproduce:
* Open the Cochineal-italic.otf font file (attached in zip)
* Select all glyphs (Ctrl-A)
* Go to Element / Style / Change Weight
* In the dialog, set "Embolden by" to 12 em units, and leave the other settings at their defaults:
- ![image](https://user-images.githubusercontent.com/65569771/167951848-a42c054f-036d-444f-ab49-3dc32824d54f.png)
* Click Ok.  The first few glyphs appear to get emboldened as expected, but as soon as we get to the "A" glyph, FontForge will hang with 100% processor usage and never complete the operation.

[Cochineal-Italic.zip](https://github.com/fontforge/fontforge/files/8673603/Cochineal-Italic.zip)

**Comment by skef** [comment] 2022-05-13 10:42
This might be worth looking at soon, and maybe I'll try to do so this weekend. 

Either way, though, it seems like we've now fixed the important issues raised by the last release other than the Windows `sans` question. @jtanx what is your thinking when it comes to a maintenance release? Should we try to do one fairly soon?

**Comment by rallg** [comment] 2022-05-13 18:32
This behavior is not specific to Windows. Also happens with other fonts, on Linux and on Termux:proot:Arch. Has been happening for years. Not new.

User workaround: Remember which character caused the problem. Manually embolden it.

I believe the problem is caused when tightly-placed points will overlap in the emboldened glyph. The reques to to automatically remove overlap, part of the style weight command, appears to not work as expected. But the problem occurs whether or not that box is checked.

**Comment by skef** [comment] 2022-05-16 07:09
@rallg that was just a mostly unrelated message between contributors (added here because I happened to be noting that I would look at this, which I now have). The last release was substantial and came with a few problems that are now fixed so it's getting to be time for a maintenance update.

**Closed** 2022-07-03 04:16 UTC
