### ISSUE TITLE
Sfd files empty on Mac with Big Sur

### ISSUE THREAD

**Issue by samiel60** [fontforge/fontforge#4677] opened 2021-03-24 14:51 UTC
I was able to (at least apparently) install FF on MacBook Pro M1
with MacOS Big Sur.

The program opens, but then:
1) if I open existing .sfd files, they appear empty;
2) if I create a new file and save it, subsequently reopened,
it is the same way empty.
Identify possible problems with the operating system I use?
Could there be some other factor why the files appear empty?
Thank you

**Comment by ctrlcctrlv** [comment] 2021-03-25 03:47
Is this a duplicate of #4520 ?

**Comment by samiel60** [comment] 2021-03-25 22:45
oops, I'm sorry I checked wrong.
I would say that it is just the same problem.
I have overcome the obstacle of the "unidentified developer", neing 
able, at least apparently, to complete the installation. Now, however, 
despite having checked some hacks reported on the net, I have precisely 
the problem mentioned above and I do not know if there is a connection 
between the two.
thank you



Il 25/03/21 04:47, Fredrick Brennan ha scritto:

**Comment by ctrlcctrlv** [comment] 2021-12-24 20:29
(Duplicate of #4520)

**Closed by ctrlcctrlv** 2021-12-24 20:29 UTC
Labels: Mac OS X
