### ISSUE TITLE
Cannot start Fontforge without connecting to network

### ISSUE THREAD

**Issue by sungsit** [fontforge/fontforge#2237] opened 2015-04-30 15:05 UTC
Compiled from 6e6079c0ca6615b2a090afeeecec41efc20b5968 on Archlinux x86_64 3.19.3-3-ARCH

Debugging messages:

No network

```
Based on sources from 03:55 ICT 29-Apr-2015-ML-TtfDb-D.
Based on source from git with hash: 6e6079c0ca6615b2a090afeeecec41efc20b5968

...

E: 15-04-30 21:40:56 No adapter found, ZSYS_INTERFACE= isn't helping
fontforge: src/zbeacon_v2.c:208: zbeacon_hostname: Assertion `self' failed.
Aborted (core dumped)
```

With network

```
15-04-30 21:41:25 client beacon address: <my ip address>
```

**Comment by davelab6** [comment] 2015-04-30 15:10
Duplicate of https://github.com/fontforge/fontforge/issues/1987

**Comment by davelab6** [comment] 2015-04-30 15:11
Thanks for your report! :)

**Closed** 2015-04-30 15:11 UTC
