### ISSUE TITLE
Fresh MacOS Install  User Interface totally unintelligible.

### ISSUE THREAD

**Issue by ourson66** [fontforge/fontforge#4853] opened 2021-11-17 00:07 UTC
### Description:
I freshly installed the latest version downloaded from FontForge's website on my Mac (see version info below) and launched it for the first time.  Nothing in the user interface is at all legible, it looks like it's using some sort of "domino" font, even the menus in the user interface are unreadable.  It makes the app completely unusable, but I can't imagine this is something in the app itself, so any assistance in troubleshooting this would be greatly appreciated!

### Versions:
FontForge:   FontForge version 20201107 based on sources from 2020-11-07 20:56 UTC git:21ad4a18fb3d4becfe566d8215eba4483b0ddc4b
Mac OS: Version 12.0.1 (Monterey)

### Screenshot:
![Screen Shot 2021-11-16 at 6 28 44 PM](https://user-images.githubusercontent.com/10282917/142082462-ab6e08fc-9a05-4aba-aa27-115ac069de7e.png)
nd

**Comment by skef** [comment] 2021-11-17 00:20
Based on the character counts this isn't a localization problem. 

Try installing the font [DejaVu Sans](https://dejavu-fonts.github.io/Download.html) and seeing if that helps. If it does then the most likely source of this problem is a corrupted version of Helvetica somewhere on your system.

**Comment by jtanx** [comment] 2022-02-03 10:14
Dupe of #4651/ #3918/#3592

**Closed by jtanx** 2022-02-03 10:14 UTC
