### ISSUE TITLE
Error message that .sfd files are "too corrupted to open", even though they were working this morning...

### ISSUE THREAD

**Issue by madeleddy** [fontforge/fontforge#4094] opened 2020-01-08 23:02 UTC
Has this happened to anyone else before ? I was using FontForge this morning, and when I went to open one of my files this message appeared: 

![Capture d’écran 2020-01-08 à 5 58 12 PM](https://user-images.githubusercontent.com/45421653/72023365-8b9f7380-3240-11ea-8b7d-f26af9fa0b28.png)

I tried re-downloading FontForge twice and no luck.

- I'm using OSx 10.15.2 and FF version 20190801

Please let me know what I can do !

**Comment by ctrlcctrlv** [comment] 2020-01-08 23:05
We need to see the file

**Comment by madeleddy** [comment] 2020-01-08 23:29
@ctrlcctrlv now it appears that I actually can't open any .sfd files from my Desktop or Documents, i've figured out that i can open them if I place them in a public (in my case, my "Creative Cloud Files") folder. 

I get this message whenever I try to open any .sfd file from a local folder:

![Capture d’écran 2020-01-08 à 6 28 12 PM](https://user-images.githubusercontent.com/45421653/72024902-a673e700-3244-11ea-9965-5d4ab18e1e65.png)


Do you think this is a problem with my Mac..? So strange and inconvenient

Here's the sfd file anyways so you can see for yourself:

[lorey.sfd.zip](https://github.com/fontforge/fontforge/files/4037821/lorey.sfd.zip)

**Comment by ctrlcctrlv** [comment] 2020-01-08 23:49
Duplicate of #4082

**Closed by ctrlcctrlv** 2020-01-08 23:49 UTC
