### ISSUE TITLE
App Store Mac unidentified developer 

### ISSUE THREAD

**Issue by kikidesignnet** [fontforge/fontforge#2474] opened 2015-08-31 05:42 UTC
"“FontForge” can’t be opened because it is from an unidentified developer."

This is the error I got when I tried to open the FontForge that I downloaded. I want assurance that it's safe to open. Also is it possible to register with Mac in order to download the software safely?

**Comment by JoesCat** [comment] 2015-08-31 14:51
You did not mention where you got the download from.
Did you download from here: https://github.com/fontforge/fontforge/releases ?

**Comment by kikidesignnet** [comment] 2015-08-31 15:32
http://fontforge.github.io/en-US/downloads/mac/

This is where I download it from...

**Comment by EvanTypefaces** [comment] 2015-09-11 23:34
Workaround:
Right click the application and click Open. It will ask you whether you want to open it or not. Confirm and there will be no more problem. If it occurs again, repeat.

**Comment by cicku** [comment] 2015-09-12 03:19
You should modify your system setting to allow untreated sources. Thought it's not recommended.

**Comment by schizoidnightmares** [comment] 2020-05-24 15:50
Happened to me too, downloaded it from:
https://fontforge.org/en-US/downloads/mac-dl/

**Comment by JoesCat** [comment] 2020-05-24 17:52
I don't have a MAC, but there are others with the similar trouble.
Read through this to see if there is a workaround: #4082 
I'm also curious to know if the dumpster-dive works (see "...this is dumb" #2538 ).

**Comment by schizoidnightmares** [comment] 2020-05-25 01:25
I was able to get it working fully by doing this:
https://github.com/fontforge/fontforge/issues/4082#issuecomment-612408666

**Comment by jtanx** [comment] 2021-10-03 09:42
Dupe of #2344

**Closed by jtanx** 2021-10-03 09:42 UTC
Labels: Mac OS X
