### ISSUE TITLE
Paste shortcut under windows is not working

### ISSUE THREAD

**Issue by fedorl** [fontforge/fontforge#2338] opened 2015-06-07 09:26 UTC
Paste shortcut under windows is Ctrl+V. When using in FontForge, it does not paste and clears the clipboard content instead. When using paste from menu works as expected. (seen on Windows 7)

**Comment by jtanx** [comment] 2015-06-07 10:43
This is a duplicate of #2286. You can use Ctrl+V, but if you click on the text box before pasting, you will lose the paste.

**Closed by jtanx** 2015-06-07 10:43 UTC
Labels: duplicate, Windows
