### ISSUE TITLE
Color bitmap fonts support

### ISSUE THREAD

**Issue by pnemade** [fontforge/fontforge#2044] opened 2015-01-13 10:21 UTC
Hi,
  Sorry if this is already reported but I can't open https://pravins.fedorapeople.org/NotoColorEmoji.ttf in  fontforge-20141230 build. Is there anyway to open bitmap font in fontforge?

**Comment by jtanx** [comment] 2015-01-13 11:32
As it stands, no - someone would have to write the parsing code (and everything else needed) to support colour fonts ([CBDT](http://www.microsoft.com/typography/otspec170/cbdt.htm)/[CBLC](http://www.microsoft.com/typography/otspec170/cblc.htm) tables). [See also](https://color-emoji.googlecode.com/git/specification/v1.html).

**Comment by KrasnayaPloshchad** [comment] 2015-03-24 13:09
I also found the newest version of Segoe UI Symbol (include in Windows 8.1) have some colorful Miscellaneous Symbols.

**Comment by ctrlcctrlv** [comment] 2015-07-08 07:38
There are currently *four* competing standards, actually @jtanx .

* Apple [uses its own `sbix` table](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6sbix.html), no vector support (every font I've seen like this uses PNG, but the standard mentions JPEG, GIF and TIFF are also allowed -- yikes).
* Google [uses `cbdt`/`cblc` tables (May 2013)](https://color-emoji.googlecode.com/git/specification/v1.html), PNG only.
* Microsoft, Adobe, and Mozilla are backing a vector format. I am biased but this format is the best, Google and Apple are moving back into the past of bitmap fonts, when the rest of the world moved away from them a long time ago. They were probably rushing to s*it something out instead of do it right as many software companies do today.
 * [Microsoft wants `colr`/`cpal` tables.](https://www.microsoft.com/typography/otspec/cpal.htm) (The proprietary software "Glyphs App" for Apple OS is ahead of the game and [supports this already.](https://www.glyphsapp.com/tutorials/creating-a-microsoft-color-font))
 * [Adobe/Mozilla wants full SVG support in OpenType, via an `svg` table.](http://www.w3.org/2013/10/SVG_in_OpenType/)

FontForge supports none of these standards, and I don't think anyone should write any code for any support until it's clear what's going to be supported and some of the software giants (or at least foundries) consolidate on a technology. Multiple Master fonts were cool in their day too. In my opinion these color fonts are a quite stupid gimmick.

**Comment by KrasnayaPloshchad** [comment] 2015-07-08 20:31
@jtanx In the Unicode block “Miscellaneous Symbols and Pictographs”, there are some symbols have specifically indicated the colour of their glyph in their name. When I open the [BabelMap Online](http://www.babelstone.co.uk/Unicode/babelmap.html), choosing this block, some of them displaying properly with colour because my computer is including [Segoe UI Emoji](https://en.wikipedia.org/wiki/Emoji#Microsoft_Windows) font natively.
- U+1F323 : WHITE SUN
- U+1F324 : WHITE SUN WITH SMALL CLOUD
- U+1F325 : WHITE SUN BEHIND CLOUD
- U+1F326 : WHITE SUN BEHIND CLOUD WITH RAIN
- U+1F34E : RED APPLE
- U+1F34F : GREEN APPLE
- U+1F3F1 : WHITE PENNANT
- U+1F3F2 : BLACK PENNANT
- U+1F3F3 : WAVING WHITE FLAG
- U+1F3F4 : WAVING BLACK FLAG
- U+1F3F6 : BLACK ROSETTE
- U+1F446 : WHITE UP POINTING BACKHAND INDEX
- U+1F447 : WHITE DOWN POINTING BACKHAND INDEX
- U+1F448 : WHITE LEFT POINTING BACKHAND INDEX
- U+1F449 : WHITE RIGHT POINTING BACKHAND INDEX
- U+1F44A : FISTED HAND SIGN
- U+1F499 : BLUE HEART
- U+1F49A : GREEN HEART
- U+1F49B : YELLOW HEART
- U+1F49C : PURPLE HEART
- U+1F4D7 : GREEN BOOK
- U+1F534 : LARGE RED CIRCLE
- U+1F535 : LARGE BLUE CIRCLE
- U+1F536 : LARGE ORANGE DIAMOND
- U+1F537 : LARGE BLUE DIAMOND
- U+1F538 : SMALL ORANGE DIAMOND
- U+1F539 : SMALL BLUE DIAMOND
- U+1F53A : UP-POINTING RED TRIANGLE
- U+1F53B : DOWN-POINTING RED TRIANGLE
- U+1F53C : UP-POINTING SMALL RED TRIANGLE
- U+1F53D : DOWN-POINTING SMALL RED TRIANGLE
- U+1F53E : LOWER RIGHT SHADOWED WHITE CIRCLE
- U+1F53F : UPPER RIGHT SHADOWED WHITE CIRCLE
- U+1F546 : WHITE LATIN CROSS
- U+1F57E : WHITE TOUCHTONE TELEPHONE
- U+1F57F : BLACK TOUCHTONE TELEPHONE
- U+1F588 : BLACK PUSHPIN
- U+1F597 : WHITE DOWN POINTING LEFT HAND INDEX
- U+1F598 : SIDEWAYS WHITE LEFT POINTING INDEX
- U+1F599 : SIDEWAYS WHITE RIGHT POINTING INDEX
- U+1F59A : SIDEWAYS BLACK LEFT POINTING INDEX
- U+1F59B : SIDEWAYS BLACK RIGHT POINTING INDEX
- U+1F59C : BLACK LEFT POINTING BACKHAND INDEX
- U+1F59D : BLACK RIGHT POINTING BACKHAND INDEX
- U+1F59E : SIDEWAYS WHITE UP POINTING INDEX
- U+1F59F : SIDEWAYS WHITE DOWN POINTING INDEX
- U+1F5A0 : SIDEWAYS BLACK UP POINTING INDEX
- U+1F5A1 : SIDEWAYS BLACK DOWN POINTING INDEX
- U+1F5A2 : BLACK UP POINTING BACKHAND INDEX
- U+1F5A3 : BLACK DOWN POINTING BACKHAND INDEX
- U+1F5AA : BLACK HARD SHELL FLOPPY DISK
- U+1F5AB : WHITE HARD SHELL FLOPPY DISK
I think you can’t mention their colour properly in the traditional way, maybe you can try alternate way to mark the colour to their glyph for web browser or office software, but other types of program may can’t recieve this way; if you embedding the colour glyph for them, some programs can get the way to displaying properly as their name mentioned.

I am not certain others’ attitude on the colour glyph support in FontForge, I suggest you can try to build a branch to providing a test, which affording support to write any colour glyph(s). If anyone else get no problem, then you can try to merge into main branch.

**Comment by KrasnayaPloshchad** [comment] 2015-10-27 14:07
Since Mozilla started implementing colored glyphs support, I think FontForge can providing this support based on Gecko’s implementation.

https://bugzilla.mozilla.org/show_bug.cgi?id=889401
https://hacks.mozilla.org/2014/10/svg-colors-in-opentype-fonts/

**Comment by Crissov** [comment] 2017-04-21 08:55
Duplicate of #677, no?

**Comment by jtanx** [comment] 2017-04-21 09:22
Oh yeah, good spot

**Closed by jtanx** 2017-04-21 09:22 UTC
Labels: feature
