### ISSUE TITLE
Rethink nonextcp/noprevcp for cubic splines

### ISSUE THREAD

**Issue by skef** [fontforge/fontforge#4125] opened 2020-02-02 09:33 UTC
#2601 is an example of a more pervasive problem: FontForge doesn't systematically address the problem of a missing cubic spline control point. There are many cases where FF will let you just eliminate one CP and then produce poor output downstream.

A cubic spline with two missing (or, equivalently, on-curve-point-colocated) control points is a line, and is fine. It should be output in point form without both points. A cubic spline with one missing control point is mostly a problem -- ideally there would be none of these. 

One can of course just check to see if one is outputting a cubic spline and output a co-located control point, and just editing our various "output" routines would be one approach. However, these splines have undefined slopes at the co-located end, which could screw up some calculations in external tools. It would be better, either always or optionally, to output a control point 1) very slightly away from the on-curve point at 2) the slope calculated at a small t-jump away (small such as 1e-10). That would retain the shape while creating a fully defined spline.

However, there are many contexts *within* FontForge where one would want that correction. So one could imagine doing this instead on setting nonextcp/noprevcp and every subsequent change to the on-curve points or the remaining control point. The place for that is probably in SplineRefigure(); I suppose the question with that is whether and when folks consider it kosher to modify SplinePoint values via that function. Given that SplineRefigure (often through SplineMake) is supposed to be called on every geometry change it would be a tidy place to implement the change. 

I suppose the problem with "always" instead of "optionally" doing that is that some people will want rounded point values and therefore  won't be happy with the "tiny-slope" fix. But we can check nonextcp and noprevcp on behalf of those folks and just output the colocated point, given some Pref.

**Comment by ctrlcctrlv** [comment] 2020-05-08 06:23
@skef Question: I thought a bit about the rounding problem. If someone asks for rounded control points, and a control point is almost colocated, I suppose the problem is that the point will become colocated, with no "almost".

So, in the rounding routine, why can't we correct for this? If rounding will cause a control point that is not already colocated to become colocated, increase the tiny-slope until it's above where rounding would happen.

That way we can always write out colocated CPs.

**Comment by skef** [comment] 2020-05-08 06:36
Since I wrote this I've browsed the cubic spline code in more tools and it seems as though most just special-case the co-located point problem. (Which, to be explicit, is that there is no mathematically defined tangent at the endpoint of the spline.) 

My idea of positioning the point to reproduce the "implicit tangent" may be nifty but it's probably impractical. 

So for the purposes of this issue #2601 can be considered a special case: A co-located control point is fine, and therefore rounding a control point to its on-curve point is fine, or mostly fine. Marking it as "missing" is the problem. With a cubic spline there should always be two or zero control points.

**Comment by ctrlcctrlv** [comment] 2020-05-08 06:51
Oh, so in that case it shouldn't be a problem to always colocate in `SplineRefigure`, as colocated control points are allowable anyway, so tools that can't deal with them are wrong, not FontForge...

**Comment by skef** [comment] 2020-05-08 07:05
Yes -- the overhaul I was envisioning was to remove any explicit manipulation of `noprevcp/nonextcp` and always derive those values from the spline, presumably when its refigured. However:

1. That change still requires a bunch of analysis and care, because it's my impression that some code sets those flags in order to "zero out" a control point, so those need to be replaced with different code, and
2. There are a bunch of corner cases, such as on-curve points that have control points "hanging off" the end of an open contour.

**Comment by ctrlcctrlv** [comment] 2020-05-08 23:08
@skef There's no time like the present, early on in our release cycle, to risk breaking stuff. I think you ought to PR it. The UFO manifestation of the issue is quite severe, and I can't imagine what other skeletons are lurking if that obvious case isn't being accounted for

**Comment by skef** [comment] 2020-05-08 23:44
@ctrlcctrlv I'll consider it.

**Comment by ctrlcctrlv** [comment] 2020-05-09 00:45
@skef Hate to ping you again, but please let me know what you decide, so I can patch #4327 the other way if you decide against it. I could of course patch `SplineRefigure` and open the PR, but I trust your ability on this way more than my own to get it right.

**Comment by skef** [comment] 2020-05-09 01:46
@ctrlcctrlv If the thought is that I would do this in a matter of hours or a day (which I guess is the literal meaning of "present") I doubt that will happen.

**Comment by ctrlcctrlv** [comment] 2020-05-09 01:51
@skef I meant more like "this week"

**Comment by skef** [comment] 2020-05-09 02:00
It's Friday evening!

**Comment by skef** [comment] 2020-05-09 02:01
Oh, you edited.  Never mind!

**Comment by ctrlcctrlv** [comment] 2020-05-09 02:50
@skef Like many people, days of the week have become a meaningless distinction for me now :o)

**Comment by frank-trampe** [comment] 2020-05-09 04:06
The current direction here makes sense to me. Given that a cubic spline with a control point on the on-curve point is valid under the standard Bézier model, we probably need to avoid changing such geometry. I think that we could just incrementally deal with that behavior where still problematic internally and warn for export purposes. Just to make sure we're on the same page, the main remaining work is likely to revolve around disentangling `nonextcp` and `noprevcp` from the position of the control point, right?

**Comment by skef** [comment] 2020-05-09 06:09
> Just to make sure we're on the same page, the main remaining work is likely to revolve around disentangling `nonextcp` and `noprevcp` from the position of the control point, right?

My implementation idea has been roughly:

1. Eliminate all code that explicitly sets either of these values outside of `Refigure`. 
2. Replace code that sets either flag to true with the intention of eliminating (for Quadratic splines) or co-locating (for Cubic splines) a control point with a function that "does the right thing" with the control point value and calls `Refigure` to set the flag. 
3. In `Refigure` for cubic splines base the flag settings on whether *both* control points are co-located. That way a spline with one non-co-located control point will always be treated as having two defined control points, so for a spline they're always either both true or both false.

One consequence of this is that in the UI a control point will be depicted as co-located for any non-line cubic spline (you see a little X in the middle of the point). I think this is probably desirable rather than a problem. 

There may be other special cases. Still, I believe the general idea of driving the flag values by the control point locations, and also always maintaining control point values that are map the spline to a line, can be adapted to any of them.

**Comment by skef** [comment] 2020-05-09 06:21
But I guess I should ask @frank-trampe: FontForge currently supports dangling control points on open contours, I think even in save files. Should I be careful to retain this support? Or eliminate it?

**Comment by skef** [comment] 2020-05-09 09:06
```
$ grep -R nonextcp | wc
    445    2876   31550
```
mrrrph.

**Comment by skef** [comment] 2020-05-12 02:54
I'm thinking about other stuff right now and doubt I'll work on this in the near future.

**Comment by ctrlcctrlv** [comment] 2020-05-12 03:02
@skef Thanks. I'll probably patch just #4321 tomorrow, then, as it's quite a bad bug. If you do decide to do this, you can just rollback the #4321 patch in the same PR that would close this issue.

**Comment by frank-trampe** [comment] 2020-05-12 03:17
@skef, sorry for the late reply. The dangling control point issue is not an easy one. I suppose that we need to support such a thing in internal state because of the way the drawing tools work. And SFD must then support it. What ambiguities/problems does it create not fixed by the proposed changes?

**Comment by frank-trampe** [comment] 2020-05-12 03:18
@ctrlcctrlv, be sure to add some comments on the denser portions of #4321 now that it is on a merge trajectory.

**Comment by ctrlcctrlv** [comment] 2020-05-12 03:30
@frank-trampe I meant #4327 in my comment above. :-)

But _yes_, #4321 also needs further work, which I will hopefully also get to tomorrow!

**Comment by skef** [comment] 2020-05-12 04:50
> What ambiguities/problems does it create not fixed by the proposed changes?

Maybe none? It just seems like something to address (or not) while poking at the other problem. I haven't really thought it through yet but if it's a desirable feature then it can presumably be retained.

**Closed** 2021-07-12 09:27 UTC
