### ISSUE TITLE
FontForge crashes despite being in a "recontra recontra healthissimo" state (the most healthiest state of a program)

### ISSUE THREAD

**Issue by bedriczwaleta** [fontforge/fontforge#4571] opened 2021-01-10 19:45 UTC
Title explains it, and this time I want to remove the glyphs from DF Kai SB. Why it crashes despite being in a healthy state?

**Comment by ctrlcctrlv** [comment] 2021-01-10 20:22
Programs don't have states of health measurable by other programs. Your question makes no sense. If some software is attempting to measure FontForge's “health” (whatever on Earth that would even mean) that has nothing to do with FontForge.

You need to post exact reproduction steps, font used, a video if possible, and a backtrace if you can.

**Comment by yg8ijvjvjv** [comment] 2021-01-10 21:45
A healthy program state is the opposite of a glitchy program state. A lot of the time when the state is glitchy it might lead to a crash, such as copying bitmap references to another font to make glitchy state of cross-font reference. However, in this issue FontForge is in a "recontra recontra healthissimo" state (the most healthiest state of a program) and a crash would not be expected by the user.

**Comment by yg8ijvjvjv** [comment] 2021-01-10 21:48
It is important to create of issue as soon as possible in this case because this crash will be the most difficult to fix, as normally FontForge crashes are fixed by preventing the glitchy state that caused it but it is not possible in this case. That is why not much detail is known.

**Comment by ctrlcctrlv** [comment] 2021-01-10 21:51
OK Piotr, very funny.

**Closed by ctrlcctrlv** 2021-01-10 21:51 UTC

**Comment by skef** [comment] 2021-01-10 21:57
> However, in this issue FontForge is in a "recontra recontra healthissimo" state (the most healthiest state of a program) and a crash would not be expected by the user.

Just to check, have you tried sacrificing a chicken (or other medium-sized bird) every two hours to maintain this state?
