### ISSUE TITLE
Downloading FontForge On Mac

### ISSUE THREAD

**Issue by dzhmartin** [fontforge/fontforge#3407] opened 2019-01-11 09:11 UTC
Hi everyone, I'm not able to download this software on my mac. When I go to the download page -- https://fontforge.github.io/en-US/downloads/mac/ -- and enter in my email address, nothing happens; I don't see anything in my Downloads directory. I've tried using different web browsers but it never works. Is there another way I can download FontForge?

**Comment by skef** [comment] 2019-01-13 06:04
Try the workaround described in issue #3351 .

**Comment by dzhmartin** [comment] 2019-01-13 06:21
That worked thanks!

**Comment by skef** [comment] 2019-01-13 06:59
Duplicate of #3351

**Closed by skef** 2019-01-13 06:59 UTC
