### ISSUE TITLE
Pasting always crashes FontForge latest version 

### ISSUE THREAD

**Issue by waykyi** [fontforge/fontforge#4474] opened 2020-11-02 10:32 UTC
Using Fontforge latest version March 2020, Windows 10 ( all updated ), CorelDraw X7.
1. Creating graphics objects ( no image ) in CorelDraw ( size between 600mm to 2000mm ) and paste them into Fontforge Outline Windows - Back Layer. Sometimes it went ok, usually the first time or second time. But crashed third time or the first time pasting after crash. 
2. I reduced the size to around 600mmx600mm, it went ok, but crashes again after a few pastes. I did not have these problem with last year version. 
3. Please tell me what to avoid or sizes that are limited in copy/paste at Fontforge.

PS: It wasn't happen in the beginning, but after copy/pasting over 200 glyphs ( some are over 6500em top and 5800em bottom ) , Fontforge started crashing every copy/paste. At the end, I no longer copy/paste and ended with crashes. And can't open the sfd file I created. But I was able to open with 8/2019 version and not able to copy/paste either. Seemed to me I hit the limit of file size or something. Check sfd file attached. Please help. Thanks

![image](https://user-images.githubusercontent.com/73824794/97858150-1ea81d80-1d2d-11eb-8cd2-f8e833983f60.png)

[Mandalathu1.zip](https://github.com/fontforge/fontforge/files/5479564/Mandalathu1.zip)

**Comment by waykyi** [comment] 2020-11-02 15:39
I reinstalled Fontforge 3/20 version and now I can't even open the sfd file I created. It is about 6.6Mb files and now I can't do any editing. Please help. Here is the file.

[Mandalathu1.zip](https://github.com/fontforge/fontforge/files/5476133/Mandalathu1.zip)

**Comment by ctrlcctrlv** [comment] 2020-11-03 02:58
I can't reproduce this on Linux, but @jtanx tagged it so I suppose he can.

**Comment by xerrf** [comment] 2020-11-03 04:30
I am encountering a similar problem on windows 10 with copying and pasting glyphs within FontForge. For example, if I copy "A" and paste it in "a", FontForge usually crashes. It doens't tell me that it is crashing, it just closes and when I try to reopen my file, it just says that "it looks like you are opening an old session."
<img width="484" alt="ff-strange" src="https://user-images.githubusercontent.com/45602390/97949944-74db8780-1d52-11eb-9479-27fda0c3d0f6.PNG">

**Comment by waykyi** [comment] 2020-11-03 05:13
Thanks ctrlcctrlv. You mean you are able to open the .sfd file I provided or just tried the steps in first msg. I also got the same message restarting after crashes as xerrf. But I was able to copy or cut/paste any numbers of glyphs within Fontforge.

**Comment by ctrlcctrlv** [comment] 2020-11-03 05:35
I meant that I am able to open the sfd.

**Comment by jtanx** [comment] 2020-11-03 09:15
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x67bbe6e0 in ImageAlterClut (image=0x0) at ../fontforge/cvimages.c:919
919         struct _GImage *base = image->list_len==0?image->u.image:image->u.images[0];
(gdb) bt
#0  0x67bbe6e0 in ImageAlterClut (image=0x0) at ../fontforge/cvimages.c:919
#1  0x67bbeaf1 in SCAddScaleImage (sc=0x6820068, image=0x0, doclear=false, layer
=1, ip=0x681b9c00 <ips>) at ../fontforge/cvimages.c:992
#2  0x67bc54ef in SCCheckXClipboard (sc=0x6820068, layer=1, doclear=0) at ../fon
tforge/cvundoes.c:2174
#3  0x67bc8439 in _PasteToCV (cv=0x6885800, cvsc=0x6820068, paster=0x681b9c60 <c
opybuffer>) at ../fontforge/cvundoes.c:2997
#4  0x67bc8f00 in PasteToCV (cv=0x6885800) at ../fontforge/cvundoes.c:3177
#5  0x00452018 in _CVPaste (cv=0x6885800) at ../fontforgeexe/charview.c:8633
#6  0x00452086 in CVPaste (gw=0x68c3df8, UNUSED_mi=0x68d8f28, UNUSED_e=0x0) at .
./fontforgeexe/charview.c:8642
#7  0x006354b7 in GMenuBarCheckHotkey (top=0x68c3df8, g=0x68d62e8, event=0x104f7
50) at ../gdraw/gmenu.c:1966
#8  0x00635676 in GMenuBarCheckKey (top=0x68c3df8, g=0x68d62e8, event=0x104f750)
 at ../gdraw/gmenu.c:2015
#9  0x0060b88f in _GWidget_TopLevel_Key (top=0x68c3df8, ew=0x692e420, event=0x10
4f750) at ../gdraw/gcontainer.c:507
#10 0x0060c005 in _GWidget_TopLevel_eh (gw=0x68c3df8, event=0x104f750) at ../gdr
aw/gcontainer.c:673
#11 0x0061aa07 in _GGDKDraw_CallEHChecked (gw=0x68c3df8, event=0x104f750, eh=0x6
0bccb <_GWidget_TopLevel_eh>) at ../gdraw/ggdkdraw.c:346
#12 0x0061cda0 in _GGDKDraw_DispatchEvent (event=0x4219a60, data=0x39e8c80) at .
./gdraw/ggdkdraw.c:1249
#13 0x65faf13c in ?? () from C:\msys64\mingw32\bin\libgdk-3-0.dll
#14 0x65fe5768 in ?? () from C:\msys64\mingw32\bin\libgdk-3-0.dll
#15 0x65897fcb in ?? () from C:\msys64\mingw32\bin\libglib-2.0-0.dll
#16 0x6589b283 in ?? () from C:\msys64\mingw32\bin\libglib-2.0-0.dll
#17 0x6589b59a in ?? () from C:\msys64\mingw32\bin\libglib-2.0-0.dll
#18 0x0061f44c in GGDKDrawEventLoop (gdisp=0x39e8c80) at ../gdraw/ggdkdraw.c:220
5
#19 0x0060f3dc in GDrawEventLoop (gdisp=0x39e8c80) at ../gdraw/gdraw.c:731
#20 0x005e1bf8 in fontforge_main (argc=1, argv=0x392ef98) at ../fontforgeexe/sta
rtui.c:1413
#21 0x004015f0 in main (argc=1, argv=0x392ef98) at ../fontforgeexe/main.c:33
(gdb)
```

**Comment by jtanx** [comment] 2020-11-03 09:25
Actually this is pretty straight forward. Windows builds are 32-bit, they are also not large address aware, so the max addressable memory is 2gb. I presume FontForge also keeps all images loaded in memory, so it's literally running out of memory when you try to paste in another image. 

e.g. with your SFD loaded:
![image](https://user-images.githubusercontent.com/5137410/97968433-bd5a7a00-1e12-11eb-93d4-8398d87e8546.png)

**Comment by waykyi** [comment] 2020-11-03 17:19
Thanks a lot jtanx. This fixed the problem. Now I am able to copy/paste more and work as designed. Just a note that my anti-virus program reported about potrace.exe, I think it is tracing program FontForge uses and it went well when I allow to run it. Thank you very much for your help and a quick reply. Thanks

**Comment by frank-trampe** [comment] 2020-11-06 15:17
This is some combination of fixed and unfixable, so I'm closing.

**Closed by frank-trampe** 2020-11-06 15:17 UTC
Labels: I-bug, I-crash, Windows
