### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by bedriczwaleta** [fontforge/fontforge#4564] opened 2021-01-09 04:35 UTC
No cidmap file when I try to open Noto Sans CJKs (currently I only have TC installed, which supports 7800 characters (frequently used in documents) Big5, HKSARG, MSARG and the Republic of China) 

only 52 Fullwidth characters appear and the others are identity of adobe (like name me)

**Comment by yg8ijvjvjv** [comment] 2021-01-09 18:55
What is cidmap? I only make TrueType fonts.

**Comment by bedriczwaleta** [comment] 2021-01-09 18:56
https://fontforge.org/docs/techref/cidmapformat.html

**Comment by yg8ijvjvjv** [comment] 2021-01-09 18:57
So you would like to convert CID to TrueType?

**Comment by bedriczwaleta** [comment] 2021-01-09 19:01
yes

**Comment by yg8ijvjvjv** [comment] 2021-01-09 19:02
FontForge might not have complete cid support. It might not be a well known format.

**Comment by bedriczwaleta** [comment] 2021-01-09 19:06
But no website says how many characters Noto Sans TC has.

**Comment by bedriczwaleta** [comment] 2021-01-09 19:07
I recently maded a copyright infringement (CI) of Microsoft's Dotum and nothing was affected but no CID.

**Comment by yg8ijvjvjv** [comment] 2021-01-09 19:08
Try using external CID converters

**Comment by yg8ijvjvjv** [comment] 2021-01-09 19:09
Once you convert you might be able to successfully CI the font

**Comment by bedriczwaleta** [comment] 2021-01-09 19:10
Towards my attention, to what?
OTF to CID?

**Comment by yg8ijvjvjv** [comment] 2021-01-09 19:12
cid to ttf

**Comment by yg8ijvjvjv** [comment] 2021-01-09 19:14
Once you convert the resulting ttf is both TI and CI. To remove the trademark infringement change the font name but to keep TI keep the font name. To keep the CI keep the glyphs but to remove CI do Autotrace

**Comment by bedriczwaleta** [comment] 2021-01-09 19:16
noto sans CJK has no CID

**Comment by yg8ijvjvjv** [comment] 2021-01-09 19:17
FontForge might be misinterpreting the font as CID. The developers might be able to fix this.

**Comment by bedriczwaleta** [comment] 2021-01-09 19:28
OTF to CID  does not works

**Comment by yg8ijvjvjv** [comment] 2021-01-09 19:29
Try requesting the font developers to make TrueType version

**Comment by ctrlcctrlv** [comment] 2021-01-09 19:46
Duplicate of #4350, #1831 etc.

**Closed by ctrlcctrlv** 2021-01-09 19:46 UTC

**Comment by yg8ijvjvjv** [comment] 2021-01-09 19:56
be careful you are [banned](https://typedesign.miraheze.org/wiki/Banned_from_Type_Design)

**Comment by yg8ijvjvjv** [comment] 2021-01-11 12:05
Only close the issue and thousands of duplicates if it is fixed
