### ISSUE TITLE
PPA installs an outdated version -- Bad SFD number Version 3.2

### ISSUE THREAD

**Issue by greytomorrow** [fontforge/fontforge#4444] opened 2020-09-12 13:23 UTC
The Download page at https://fontforge.org/en-US/downloads/gnulinux-dl/ says...

> ##### Ubuntu
> 
> Installing on Ubuntu is easy with our Ubuntu PPA
> 
```
> sudo add-apt-repository ppa:fontforge/fontforge;
> sudo apt-get update;
> sudo apt-get install fontforge;
``` 

I did as instructed and after launching got the exact same errors as https://github.com/fontforge/fontforge/issues/4439. Reading further...

> ctrlcctrlv commented 10 days ago
> 
> Yeah for sure. You're using some ancient 2014 version of FontForge. You need to use something from at least the last two years. I can't remember exactly when we bumped the SFD version but I think it was in 2019.
> 

> ctrlcctrlv commented 10 days ago
> 
> Well you are using a very old version of Ubuntu so I don't know that you can blame even the maintainer of the PPA. It is unsupported to use a file from a new version on an old one of course.

That's insane. If that is the case, **take that link off your Downloads page**. You are doing yourselves and everybody a disservice. If you insist on either compiling or only supporting AppImage, so be it. But don't include **ancient, incompatible software** on your Downloads page. The "maintainer" of the PPA isn't blameless either, but mostly whoever maintains your fontforge.org site is really to blame, especially if what @ctrlcctrlv says is accurate.

Now, if you'll excuse me I have PPAs to delete and have to purge and reinstall FontForge. I had nothing better to do with my Saturday. Or maybe somebody there wants to come over and fix it for me?...I didn't think so.

**Comment by ctrlcctrlv** [comment] 2020-09-12 13:33
What version of Ubuntu are you using?

**Comment by ctrlcctrlv** [comment] 2020-09-12 14:01
Actually, you know what, fine, I agree with you. Even if you're using unsupported Ubuntu version, our PPA hasn't been updated for _any_ Ubuntu version in over a year:

![image](https://user-images.githubusercontent.com/838783/92996757-df92e400-f4c2-11ea-88ab-ad8297b96fa2.png)

The idea of PPA is at the end of the day an old way of thinking. I don't see a reason to argue with you on that front. And I very much doubt @frank-trampe wants to continue maintaining this PPA given he hasn't been doing so and it's just a headache in the days of AppImage. Really, any problem a user will have with PPA, I will always say same thing, "please try again on the AppImage". Since @skef and I are the main ones still providing support here on the tracker and mailing list, it's reasonable to remove PPA option from downloads page.

So, let's continue discussion on specific wording at https://github.com/fontforge/fontforge.github.io/pull/151. Closing as moved to proper repo.

**Closed by ctrlcctrlv** 2020-09-12 14:01 UTC

**Comment by greytomorrow** [comment] 2020-09-12 17:00
The archaic 18.04.5 LTS...supported until 2023 (extended support until 2028). I have to blow the dust off it every time I boot up.

Forgive my insolence but your comments in https://github.com/fontforge/fontforge/issues/4439 were glib and irresponsible, especially in light of the fact that it was all avoidable merely by removing a few lines from your website. I just spent my Saturday afternoon removing the PPA, uninstalling FontForge, "installing" the AppImage and all the peripheral fun involved in making that work (permissions, .desktop files, preferences, etc.).

**Comment by ctrlcctrlv** [comment] 2020-09-12 17:20
Sorry, I didn't know Ubuntu releases are supported for so long.

Thank you for showing that the issue is not only on i686, as I thought.

The lines will most probably be removed, I can't make such a unilateral decision, but I proposed one be made and if no one objects to my wording within a few days I'll merge it. @frank-trampe maintains the PPA and I'd like to hear from him over on the other issue tracker before merging it.

We try not to step on each other's toes around here, which is why I was reluctant to remove the PPA if _only_ i686 was no longer being built.

**Comment by ThaDaVos** [comment] 2021-11-28 11:32
Uhm.... it's still mentioned on the http://designwithfontforge.com/en-US/Installing_Fontforge.html page...
Also, the PPA gives an error now: 
![image](https://user-images.githubusercontent.com/5251028/143765951-374ac10d-27bd-4b6b-83c2-75c1e95e31d4.png)

**Comment by ctrlcctrlv** [comment] 2021-11-28 13:22
Thanks, that page seems out of date in many respects, if no one objects I'll just make it link to https://fontforge.org/en-US/downloads/gnulinux-dl/ and delete all the other Linux advice.

**Comment by frank-trampe** [comment] 2021-11-28 14:15
Probably the best course of action at this point.
