### ISSUE TITLE
Where do you put your small caps ?

### ISSUE THREAD

**Issue by Gwenouille** [fontforge/fontforge#2448] opened 2015-08-11 23:04 UTC
Hello,

I was wondering what was the right way to deal with small caps: I mean, the ISO encoding doesn't seem to have a nice clean place for them, as they appear to be scattered around several ranges…
An inspection of some professionnal fonts shows that they are sometimes placed into a "corporate use" range.

Do you have some advice for me ? Where do you order them ?

**Comment by mskala** [comment] 2015-08-12 06:51
It's best to treat small caps as a different style, not as different characters.  Thus, they should be in unencoded slots with a substitution feature directing the renderer to switch to those glyphs when the user requests small caps.

If you put small caps in Unicode code points that belong to other characters that only happen to resemble small versions of Latin capital letters (for instance, κ for small-cap K), then you destroy cut and paste, search, spell check, keyboard input, compatibility with anything (for instance, the Greek language) that may actually use κ in its true meaning... the problem is that κ is *not* small uppercase Latin K, it is full-size lowercase Greek kappa.  Any software that expects character codes to mean what Unicode defines them to mean, will interpret κ as a Greek letter and completely unrelated to the Latin letter K.

Similarly, ligatures like f-i should be in unencoded slots with substitution features, so that when cut and pasted they will turn into "fi" and not into little boxes.  This is a very common complaint from font users; you'll certainly see many commercial fonts attempting to give code points to ligatures and small caps, but you shouldn't follow them as examples.

If it's absolutely necessary to have distinct character codes for small caps for technical reasons, then they should go in the Private Use Area - and since Adobe has historically put them into the range from U+F761 to U+F77A, it'd make sense to use that range.  However, Adobe doesn't do that anymore and now recommends against it.  You shouldn't do it, you should use unencoded slots.  All forms of uppercase Latin K should be character code 113 (that is, U+004B), and style differences such as italic or small cap should be implemented by other things outside of the character code.

The "math alphabets" of Unicode Math, which include some stylistic information specified in the characters, are a special case intended for use in mathematical expressions where the visual appearance of the letters is part of their meaning.  They should _never_ be used as a substitute for styles in text, and I'm not convinced that their introduction was a good idea for math, either.

**Comment by Pecita** [comment] 2015-08-12 09:32
Small caps can...
* either be include in the unicode base plan applying ISO/IEC JTC1 SC2/WG2 N4068
* either anywhere in private area, referred by the lookup table "simple substitution/smcp" (it's call a *variant*)
* better both, as in [my font ;-)] (http://pecita.eu/b/Pecita.otf)

Use for example CSS to activate the variant, like this:
`
.smcp {
	font-feature-settings: "smcp" on;
	-ms-font-feature-settings: "smcp" on;
	-o-font-feature-settings: "smcp" on;
	-moz-font-feature-settings: "smcp" on;
	-webkit-font-feature-settings: "smcp" on;
}
`

**Comment by Gwenouille** [comment] 2015-08-12 09:37
Thanks a lot mskala, very kind of you to produce such a detailed reply !

Until now, I was using the dedicated slots in several ranges. So i had GNRYBHL at a place, then ACDEJ etc… and FS at another place… Crazy…
So I should simply have additionnal unencoded slots, with "A.sc" sharing the Unicode number of "a", ie 0061 and so on ?
This is in essence what I've done with my numbers: normal, subscript, superscript, numerals and denominators all share the same ISO number (0030 and so on…), so I guess i will manage that…

But I don't get it with ligatures…
In my file, I use standard ligatures and a few personnal ones (one for P i and one for F i). I don't know what to do with them, so they are on code FB07 (Alphabetic Presentation Forms)…
If i add an encoding slot, then i have to specify a name and unicode value don't I ? and what will the value be ? I mean "P i" replaces a set of characters, not a single one, so it can't share P's unicode value… There is something that eludes me…

**Comment by mskala** [comment] 2015-08-12 11:56
You should have additional slots, for instance one for "a.sc", but they shouldn't have Unicode numbers at all.  That's why they are called "unencoded."  When someone using the font types "a", they type U+0061 (lowercase a) and the Unicode number table maps that to a glyph that is probably called "a".  If they turn on small caps, then their software should use an additional mapping table (the "smcp" feature, which you will have to create) that maps the glyph called "a" to a glyph called "a.sc".  That mapping doesn't use Unicode numbers, it works on the glyph names (and their associated internal numbers, which you don't edit directly).

Ligatures are the same way, and your point about how a ligature might not have a natural Unicode number is a good part of the reason _why_ they have to work this way.  A ligature like "Pi" should be in an unencoded slot.  That means it has _no_ Unicode number.  In the FontForge GUI, unencoded slots appear at the end of the listing, after all the encoded slots that have Unicode numbers.  Then the user can't get that glyph directly by typing a Unicode number; instead they type U+0050 U+0069 (the letters "P" "i"), then those Unicode numbers map to glyphs that are probably called "P" "i", then the substitution mapping changes those two glyphs into one glyph which is your "Pi" glyph.

It's probably not a good idea to make up your own codes inside the "Alphabetic Presentation Forms" block.  If you ever need to make up your own codes for some reason, you should be using the PUA (Private Use Area).  But for ligatures, it's better not to give them code numbers at all.

In my own project, I assign PUA code numbers to a lot of these glyphs for internal use (in choosing which glyphs to include in different styles of the fonts) but then there's a script that removes them, leaving the glyphs in unencoded slots, when it creates the final font files.

**Comment by Gwenouille** [comment] 2015-08-12 14:07
Allright, I think i get it.
But then, if you let these glyphs unencoded (smallcap "A" as well as ligature "Pi") and only available through a competent substitution mapping a la opentype smcp or liga, doesn't it mean that the users won't be able to use these glyphs in less-competent softwares ?
If i use Libre-Office for instance, and want to insert a special character, I can pick it up in the table. Same in InDesign.
That is then impossible if characters are unencoded, am i right ?

**Comment by mskala** [comment] 2015-08-12 15:18
Yes.  If it's important to support that scenario, then I think you'd better put them in the PUA.  But doing that does create the risk of screwing up things like cut'n'paste with systems that really support the standards.  Unfortunately, there isn't really a good way to please all users.

**Comment by adrientetar** [comment] 2015-08-12 19:45
InDesign glyph panel sees unencoded glyphs. I do not know about other software.

**Comment by Gwenouille** [comment] 2015-08-12 20:50
Al-right mskala, that what I was afraid of.
The problem is that I am only experimenting at the moment. I can't really tell what is most important for my font…
Thanks Adrien, that's good to know ! My evaluation for InDesign CC ended at noon today, and I am not sure I want to pay 35 € a month.
And yet I am not so enclined to jump into the lualatex bath, Adrien… seems to high a step for me right now…

**Comment by adrientetar** [comment] 2015-08-12 21:12
```
\documentclass{scrartcl}
\usepackage{microtype}
\usepackage{fontspec}

\setmainfont[ExternalLocation, UprightFont = MyFont.otf]{My Font}

\begin{document}
    Hello World.
\end{document}
```

I often use sharelatex.com to make and compile my documents online, you just have to change the compiler to lualatex in project settings after creating one.

Syntax for font features is described at Page 23 of [the fontspec manual](http://get-software.net/macros/latex/contrib/fontspec/fontspec.pdf) onwards, e.g.:

```
{\addfontfeature{Numbers=OldStyle} 1923, w oldstyle numerals.}
```

**Comment by Gwenouille** [comment] 2015-08-12 21:55
That's very kind of you !
I've dug a little bit during the last 30 minutes, in order to understand what that is all about, and i must say I am even more confused now! LuaTex XeteX pdfTeX LaTeX ?
Even on the LuaLaTex homePage, downloading the windows builds is … [cumbersome](http://minimals.contextgarden.net/current/bin/luatex/mswin/bin/). Am i supposed to download all these files one by one ?
I mean,it really seems to be a tool that is designed for hardcore users. I am completely at a loss here. It seems I would spend 50+ hours installing and learning how to make one simple document…

**Comment by adrientetar** [comment] 2015-08-12 22:34
LuaTeX is most recent and supports OpenType through luaotfload.
On Windows you can just download MikTeX, it's an installer for LaTeX softwares.

**Comment by adrientetar** [comment] 2015-08-12 22:35
What you posted seems a ready-to-run build directory, just do `lualatex document.tex` from command-line.

**Comment by mskala** [comment] 2015-08-13 03:33
Don't try to install LuaTeX by itself.  It needs a LOT of support packages.  Get a TeX distribution from CTAN.  http://ctan.org/  Right-hand column, "Download a TeX system."

**Comment by jtanx** [comment] 2015-08-13 05:36
Yeah for Windows I would recommend MikTeX. It downloads packages as you need them. If you want more of a GUI, you can also use TeXworks, which comes bundled with MikTeX by default. Just change the target (top left corner) to `LuaLaTeX` and hit the green button.

**Comment by Gwenouille** [comment] 2015-08-13 16:32
Thanks a lot, MikTeX seems to be a bit simpler to use that the rest so far…
I managed to create a document form a template. But even that was fun, believe me…

So now, I've set it up so that LuaLaTeX is the default engine. Only have to learn TeX syntax I guess now ! And it doen't seem THAT easy from a novice's point of view.

Meanwhile I stumbled on that: http://clagnut.com/sandbox/css3/
and that : http://www.impallari.com/testing/index.php
It seems to be great for previewing a font's capability and display !

What do you think ?

**Comment by skef** [comment] 2020-02-02 19:02
"I'll tell you were I put my small caps!"

This issue seems more or less closed-out to me, closing.

**Closed by skef** 2020-02-02 19:02 UTC
Labels: question
