### ISSUE TITLE
Unable to open any font on font forge: Unauthorized - operation not permitted

### ISSUE THREAD

**Issue by lucilatblanco** [fontforge/fontforge#4240] opened 2020-03-26 13:55 UTC
Hi, I'm Lucila from Buenos Aires, Argentina.
I own a macbook pro from mid 2012 with macOS Catalina version 10.15.3.

![image](https://user-images.githubusercontent.com/62671456/77654459-d97a6c80-6f4f-11ea-8ff5-8001ce2ba36c.png)

I have downloaded the lastest version of Font Forge, but when I run the program, I'm unable to open any kind of font. It pops up an error message stating "Unauthorized - operation not permitted". I cant navigate through any of my macbook's folders.

![image](https://user-images.githubusercontent.com/62671456/77654551-f9119500-6f4f-11ea-929a-131e3baef11e.png)

Could you help me, please? I dont know what's happening.
Thank you very much!!
Kind regards

Lucila

**Comment by ctrlcctrlv** [comment] 2020-03-26 14:43
Duplicate of #4082.

**Closed by ctrlcctrlv** 2020-03-26 14:43 UTC
