### ISSUE TITLE
cant open files from desktop for FontForce!!! anyone has the problem?

### ISSUE THREAD

**Issue by NaomiLIU94** [fontforge/fontforge#4869] opened 2021-12-24 17:42 UTC
Description:
I freshly installed the latest version downloaded from FontForge's website on my Mac (see version info below) and launched it for the first time. i cant open or import any files from desktop and so on  
cant use it !!!
Versions:
FontForge: FontForge version 20201107 based on sources from 2020-11-07 20:56 UTC git:21ad4a18fb3d4becfe566d8215eba4483b0ddc4b
Mac OS: Version 12.0.1 (Monterey)

Screenshot:
<img width="828" alt="Screenshot 2021-12-25 at 1 23 50 AM" src="https://user-images.githubusercontent.com/92449682/147367413-2b196c18-8ba2-4135-acc5-5d32def12a23.png">

**Comment by ctrlcctrlv** [comment] 2021-12-24 20:28
Duplicate of #4082 per https://github.com/fontforge/fontforge/issues/4520#issuecomment-738293398.

**Closed by ctrlcctrlv** 2021-12-24 20:28 UTC

**Comment by ctrlcctrlv** [comment] 2021-12-24 20:31
See also the workaround in #2344.
