### ISSUE TITLE
SplineSetRemoveOverlap crash, calling SSRemoveTiny with a NULL SplineSet (test case inside). Triggered via «Change Weight...» operation.

### ISSUE THREAD

**Issue by fundamentals-fontdevelopment** [fontforge/fontforge#4364] opened 2020-06-06 07:30 UTC
In the process of making a **bold** font (why does Github make it **semibold** when that's barely any different from Regular?), I encountered an issue called Glyph of glitch. When the glyph is attempted to be emboldened, it causes glitches in all of FontForge. Use the Element\\Style\\Change Weight... operator (within the interactive grid of glyphs) and set to embolden by 51 units. Not only this will crash FontForge, but also create a glitched recovery file. Using the operator within the glyph editor will work, but will lead to glitches later, like attempting to clear the glyph from the interactive grid of glyphs will crash.

[Glyph of glitch.zip](https://github.com/fontforge/fontforge/files/4739538/Glyph.of.glitch.zip)

**Comment by fundamentals-fontdevelopment** [comment] 2020-06-06 08:33
The glitch is reproduced if Cleanup Self Intersect is selected on. Therefore disabling it is a workaround to this glitch, because Glyph of glitch can happen in several glyphs in one font.

**Comment by fundamentals-fontdevelopment** [comment] 2020-06-06 12:11
The glyph sample is from
1. my font
2. public domain font
So there shouldn't be any issues with reproducing it.

**Comment by ctrlcctrlv** [comment] 2020-06-06 19:04
Thank you for your bug report. Here is the backtrace:

```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x000000000164fc83 in SSRemoveTiny (base=0x0) at ../fontforge/splineoverlap.c:3624
3624                    if ((sp->next) && (sp->next->order2) && (sp->next->to)) sp->next->to->prevcp.x = sp->me.x;
(gdb) bt
#0  0x000000000164fc83 in SSRemoveTiny (base=0x0) at ../fontforge/splineoverlap.c:3624
#1  0x00000000016509e9 in SplineSetRemoveOverlap (sc=0x0, base=0x5d56ec0, ot=over_remove)
    at ../fontforge/splineoverlap.c:3971
#2  0x00000000015b0e3a in BoldSSStroke (ss=0x43e9b50, si=0xadd040, order2=1, ro=1) at ../fontforge/scstyles.c:102
#3  0x00000000015c762c in SCEmbolden (sc=0x43eee00, zones=0xadd160, layer=1) at ../fontforge/scstyles.c:4079
#4  0x00000000015c872c in CVEmbolden (cv=0x5c972d0, type=embolden_auto, zones=0xadd160)
    at ../fontforge/scstyles.c:4342
#5  0x0000000000653849 in Embolden_OK (g=0x5d4edf0, e=0xadd3c0) at ../fontforgeexe/scstylesui.c:1878
#6  0x00000000006b04c2 in GButtonInvoked (b=0x5d4edf0, ev=0xadd6c0) at ../gdraw/gbuttons.c:257
#7  0x00000000006b129b in gbutton_mouse (g=0x5d4edf0, event=0xadd6c0) at ../gdraw/gbuttons.c:485
#8  0x00000000006bb178 in _GWidget_Container_eh (gw=0x5d46330, event=0xadd6c0) at ../gdraw/gcontainer.c:304
#9  0x00000000006bcad6 in _GWidget_TopLevel_eh (gw=0x5d46330, event=0xadd6c0) at ../gdraw/gcontainer.c:743
#10 0x00000000006ce7d6 in _GGDKDraw_CallEHChecked (gw=0x5d46330, event=0xadd6c0, eh=0x6bc265 <_GWidget_TopLevel_eh>)
    at ../gdraw/ggdkdraw.c:346
#11 0x00000000006d0faf in _GGDKDraw_DispatchEvent (event=0x3c1f970, data=0x4209a70) at ../gdraw/ggdkdraw.c:1249
#12 0x000000006c1cf5ba in libgdk-3-0!gdk_event_free ()
   from C:\msys64\home\Fred\Workspace\fontforgebuilds\ReleasePackage\bin\libgdk-3-0.dll
#13 0x000000006c20640f in libgdk-3-0!gdk_win32_drag_context_get_type ()
   from C:\msys64\home\Fred\Workspace\fontforgebuilds\ReleasePackage\bin\libgdk-3-0.dll
#14 0x00000000649f7414 in libglib-2.0-0!g_clear_list ()
   from C:\msys64\home\Fred\Workspace\fontforgebuilds\ReleasePackage\bin\libglib-2.0-0.dll
#15 0x00000000649fa4e6 in libglib-2.0-0!g_main_context_check ()
   from C:\msys64\home\Fred\Workspace\fontforgebuilds\ReleasePackage\bin\libglib-2.0-0.dll
#16 0x00000000649fa801 in libglib-2.0-0!g_main_context_iteration ()
   from C:\msys64\home\Fred\Workspace\fontforgebuilds\ReleasePackage\bin\libglib-2.0-0.dll
#17 0x00000000006d3c24 in GGDKDrawProcessOneEvent (gdisp=0x4209a70) at ../gdraw/ggdkdraw.c:2194
#18 0x00000000006c05ae in GDrawProcessOneEvent (gdisp=0x4209a70) at ../gdraw/gdraw.c:711
#19 0x0000000000657b2d in EmboldenDlg (fv=0x0, cv=0x5c972d0) at ../fontforgeexe/scstylesui.c:2260
#20 0x000000000045f3fc in CVMenuEmbolden (gw=0x5cd30e0, UNUSED_mi=0x5ce80b0, UNUSED_e=0xadf4c0)
--Type <RET> for more, q to quit, c to continue without paging--
    at ../fontforgeexe/charview.c:6920
#21 0x00000000006ec381 in gmenu_mouse (m=0x5d409a0, event=0xadf4c0) at ../gdraw/gmenu.c:948
#22 0x00000000006eddeb in gmenu_eh (w=0x5d43af0, ge=0xadf4c0) at ../gdraw/gmenu.c:1389
#23 0x00000000006ce7d6 in _GGDKDraw_CallEHChecked (gw=0x5d43af0, event=0xadf4c0, eh=0x6edd1c <gmenu_eh>)
    at ../gdraw/ggdkdraw.c:346
#24 0x00000000006d0faf in _GGDKDraw_DispatchEvent (event=0x3c1fa10, data=0x4209a70) at ../gdraw/ggdkdraw.c:1249
#25 0x000000006c1cf5ba in libgdk-3-0!gdk_event_free ()
   from C:\msys64\home\Fred\Workspace\fontforgebuilds\ReleasePackage\bin\libgdk-3-0.dll
#26 0x000000006c20640f in libgdk-3-0!gdk_win32_drag_context_get_type ()
   from C:\msys64\home\Fred\Workspace\fontforgebuilds\ReleasePackage\bin\libgdk-3-0.dll
#27 0x00000000649f7414 in libglib-2.0-0!g_clear_list ()
   from C:\msys64\home\Fred\Workspace\fontforgebuilds\ReleasePackage\bin\libglib-2.0-0.dll
#28 0x00000000649fa4e6 in libglib-2.0-0!g_main_context_check ()
   from C:\msys64\home\Fred\Workspace\fontforgebuilds\ReleasePackage\bin\libglib-2.0-0.dll
#29 0x00000000649fa801 in libglib-2.0-0!g_main_context_iteration ()
   from C:\msys64\home\Fred\Workspace\fontforgebuilds\ReleasePackage\bin\libglib-2.0-0.dll
#30 0x00000000006d3c9f in GGDKDrawEventLoop (gdisp=0x4209a70) at ../gdraw/ggdkdraw.c:2205
#31 0x00000000006c0690 in GDrawEventLoop (gdisp=0x4209a70) at ../gdraw/gdraw.c:731
#32 0x0000000000686c68 in fontforge_main (argc=2, argv=0x3c2a500) at ../fontforgeexe/startui.c:1413
#33 0x0000000000401563 in main (argc=2, argv=0x3c2a500) at ../fontforgeexe/main.c:33
(gdb)
```

I was able to confirm that, indeed, there is a glitch upon recovery. The glyph is duplicated. However, I was not able to duplicate the reported crash upon clearing the glyphs in the recovered file.

![image](https://user-images.githubusercontent.com/838783/83952469-e3d9a200-a7ed-11ea-812b-3dd2d2426a18.png)

I will rename this issue for accuracy.

**Comment by skef** [comment] 2020-06-06 20:03
Poking around with the address sanitizer a little this is looking similar to #4117 which was resolved by #4138, but the problem is in a slightly different place.

**Closed** 2020-06-06 22:10 UTC
Labels: I-crash, stroke

**Comment by fundamentals-fontdevelopment** [comment] 2020-06-07 04:41
"I was able to confirm that, indeed, there is a glitch upon recovery. The glyph is duplicated. However, I was not able to duplicate the reported crash upon clearing the glyphs in the recovered file."

The clear crash is done by using the Change Weight operation on the original file within the glyph editor, then performing the Clear operation in the 2D glyph list.

**Comment by ctrlcctrlv** [comment] 2020-06-07 09:41
How can you do a Clear on the original file if Change Weight crashes FontForge?
