### ISSUE TITLE
Inkscape copy&paste always a bitmap

### ISSUE THREAD

**Issue by franzrogar** [fontforge/fontforge#4291] opened 2020-04-22 13:12 UTC
= SYSTEM =
FontForge 2020-03-14
Windows 10, x64, up-to-day
Inkscape 0.92.4

= ISSUE =
If you copy & paste the char "o", FontForge renders it as a bitmap image always.

If you try to import it, FontForge will crash always.

Note 1: the output doesn't change if you try to import it as two paths or as a single one.
Note 2: the output doesn't change if you try to import a "plain SVG" version of the file.
Note 3: copy & paste seems broken as everything that is pasted from Inkscape is rendered as a bitmap image.

= EXPECTED BEHAVIOR =
To be able to copy the shapes as intended.

= HOW TO REPRODUCE =
Open SVG in Inkscape. Copy the shape. Open the character in FontForge and paste it: it will be a bitmap.

Open the character in a new font in FontForge and try to import the SVG. It will crash.

Thanks in advance,
   Franz

[o.zip](https://github.com/fontforge/fontforge/files/4516267/o.zip)
(Seriously... add support for SVG files...)

**Comment by KamilLanda** [comment] 2020-04-22 14:54
I have FontForge version 06-04-2020 (also Win10x64) from https://sourceforge.net/projects/fontforgebuilds/files/i686/Installer/
and for me it doesn't crash during import SVG - I imported your file o.svg to the new font and also to the some my font, and it was OK, no crash. 

I confirm CtrlCV from Inkscape (same version) as bitmap.

**Comment by ctrlcctrlv** [comment] 2020-04-22 17:00
I confirm both @franzrogar's and @KamilLanda's observation. This bug has been fixed, probably by #4250. 

Closing as duplicate of #4248.

Regarding the fact that copying paths from Inkscape results in a bitmap in FontForge, this is expected behavior from the system clipboard. Better integration may or may not be possible. If interested in discussing it further, please open a new issue just for this question with some research into if it's actually possible to pass SVGs through the clipboard.

**Comment by skef** [comment] 2020-04-22 17:02
Incidentally I have some more SVG fixes/improvements on the way. Nothing dramatic.

**Comment by franzrogar** [comment] 2020-04-22 17:52
@KamilLanda Thanks for the info and the link. I confirm it loads properly as you stated.

@ctrlcctrlv Regarding the "bitmap" copying, it's a bug (or a regression, as you prefer call it). The first font I ever created (oh so many years ago...) was copying and pasting from Inkscape to FontForge on-the-fly (as I didn't even knew there were a "typography" extension).

Windows clipboard (though terrible by design) does keep the vector info between programs (if they do support it). Also, the only, let's call it "tutorial", that most people look at also explained (very lightly) the copy&paste as a way to import char by char (section 3.c of this page https://www.reddit.com/r/neography/comments/8186cc/creating_fonts_with_inkscape_and_fontforge_part1/ )

So, I think, as you point, that it should require a new ticket for "bitmap" copy&paste on Windows.

And, of course, thank you very much for your hard work :-)

@skef Any SVG improvement/fixes are always welcomed, mostly because I've never been able to "draw" the characters directly on any typography software (be it FontForge or FontLab), as I find the tools too... pedestrian to me: that's why I like to work with Inkscape as I can easily manipulate the shapes. Thanks to you too for your work.

Sincerely,
   Franz

**Comment by skef** [comment] 2020-04-22 18:01
@franzrogar I'm afraid there isn't anything very sexy in the next bundle. The most significant has to do with rounded SVG rectangles, which are completely broken in the current implementation. There are also problems with stroked contours that have non black/white colors and polygon parsing.

**Comment by ctrlcctrlv** [comment] 2020-04-22 18:08
@franzrogar Thanks for the clarification. If it's a recent regression, it might be related to #4242. Reopening and tagging @jtanx.

**Comment by jtanx** [comment] 2020-04-22 23:06
This is unrelated to #4242. That was wrt issues copying out, and you'd have to be using a build off sourceforge to even have that patch.

That you can even paste into FontForge at all on Windows is an improvement, pre-gdk nothing would have happened at all.

Anyway, this is most likely something to do with gdk clipboard handling itself (i.e. an upstream issue). Inkscape is probably offering the SVG in addition to the image in the clipboard, but GDK (on Windows) only understands the image and not the SVG format. So any fixes would likely have to be there and not in FF.

**Closed** 2020-05-01 22:14 UTC
