### ISSUE TITLE
alphanumeric characters turns to japanese  half-width katakana

### ISSUE THREAD

**Issue by jinhirano** [fontforge/fontforge#4577] opened 2021-01-13 16:47 UTC
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [x] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

I am a Japanese user.
In the windows version released on 2020-11-07, there was a bug in which half-width katakana was entered when entering alphanumeric characters when changing the font name or saving the font.
![キャプチャ48](https://user-images.githubusercontent.com/77402935/104482314-25df8780-560a-11eb-84b7-5b9fe5f127da.PNG)
For example, I entered "myfont" for its fontname.
In the version released on 2020-03-14, alphanumeric characters could be input correctly.

**Comment by skef** [comment] 2021-07-08 20:21
I keep seeing references to this on social media. I dunno how we would tackle it but it seems like the community is losing a fair amount of Japanese users to this.

**Comment by jtanx** [comment] 2021-07-09 00:31
Thanks @jinhirano for filing the issue, I can reproduce this. Seems to be some regression in glib and/or how we're using it, I'm looking further.

> I keep seeing references to this on social media. I dunno how we would tackle it but it seems like the community is losing a fair amount of Japanese users to this.

Yeah, I mean if no one files an issue and the only place people complain about it is on social media, I think it's fair to say nothing will be done about it.

**Comment by skef** [comment] 2021-07-09 00:51
@jtanx it's often in Japanese messages that I right-click translate. I don't know how much different language communities are hooked into the whole open source support framework. I've sometimes communicated with machine-translated messages but it's hard to tell how well that works.

**Comment by jtanx** [comment] 2021-07-09 04:45
Found the cause: just a plain old bug in gdk - https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/3741/diffs

**Comment by jtanx** [comment] 2021-07-09 05:21
As it's an upstream issue, the fix might take a while to be available.

As a workaround, you can use the 64-bit build (https://sourceforge.net/projects/fontforgebuilds/files/x86_64/Portable/FontForge-mingw-w64-x86_64-f8bbd6-r1.7z/download) - seems like the uninitialised state in that is 'ok' for it to work as expected.

**Comment by jtanx** [comment] 2021-07-10 11:24
Changes pushed upstream, should be fixed in the next release.

**Closed by jtanx** 2021-07-10 11:24 UTC
