### ISSUE TITLE
Selecting "bitmap strikes available" from the element menu causes a crash

### ISSUE THREAD

**Issue by tbodt** [fontforge/fontforge#3701] opened 2019-05-19 19:06 UTC
- [x] The FontForge version and the operating system you're using
13-Apr-2019, macOS 10.13.6
- [x] Steps to reproduce the behavior
Create a new document, select "bitmap strikes available"
- [x] The behavior you expect to see, and the actual behavior
Crash. Expected no crash. Did a little debugging and it's a segfault on this line: https://github.com/fontforge/fontforge/blob/7aa255908ecd75f216a529b6a594f0820c36c635/fontforgeexe/bitmapdlg.c#L406

**Comment by skef** [comment] 2020-03-05 16:24
@jtanx Seems like this might have been `oldsystem` not being initialized correctly. Could there have been/be a problem with it being non-static?

**Comment by jtanx** [comment] 2020-03-05 21:04
I don't think so, it looks like it's non-static because it's used as a preference.

**Comment by skef** [comment] 2020-03-06 06:16
Huh -- well, I've looked at this some and can't figure out what the problem might be. 

@tbodt Is there anything you can add -- maybe more specific instructions on how to reproduce?

**Comment by jtanx** [comment] 2020-03-06 21:43
@tbodt did you somehow set this preference `DefaultScreenDpiSystem`?

**Comment by hierophect** [comment] 2020-05-06 14:54
Just commenting that I've also encountered this problem, makes FontForge useless for my purposes. This is an [important](https://learn.adafruit.com/custom-fonts-for-pyportal-circuitpython-display/conversion) program for our application, and I hope it can get some attention again.

**Comment by jtanx** [comment] 2020-05-06 21:54
It's pretty hard to provide help when you don't provide any information. What OS, what version, do you have a sample font, what are the exact steps you took?

**Comment by hierophect** [comment] 2020-05-07 14:20
It's identical to the issue in the OP, though with OS 10.15.4 in my case. I did ultimately find a workaround which was not checking the Use Freetype radio button.

**Comment by jtanx** [comment] 2020-05-08 13:42
I can't repro. As I said before, do you have a sample font?

**Comment by hierophect** [comment] 2020-05-08 16:31
It occurs for all fonts for me, an example could be [NotoSansJP](https://fonts.google.com/specimen/Noto+Sans+JP?query=J) for instance. 

For the record, I'm not seeking any help, I just wanted to make note that this issue was still coming up in case it benefited other contributors. However, as I've explored the app further, it's only one of many segfaults and freezes I've encountered, and I don't think I can justify spending more time on it. Best of luck.

**Comment by ctrlcctrlv** [comment] 2020-05-08 22:36
Closing due to:
1. combative, entitled behavior by @hierophect (as if we're supposed to care about his problems at work);
2. linked font and steps do not cause a crash on 20200314.

If a font and backtrace are provided, I'll reopen this. 

Until then, we've all managed to work FontForge into our workflows. It has many flaws, but for 20 years in November has powered a large part of the FOSS font movement, and even now with the UFO ecosystem, AFDKO, and `fontmake`, remains a very important part of the toolkit.

I am highly amused that one minute FontForge was an "important program for [your] application" and the next it's not worth the time.

Consider this a warning for trolling.

**Closed by ctrlcctrlv** 2020-05-08 22:36 UTC
Labels: spurious

**Comment by tbodt** [comment] 2020-05-08 23:21
This seems to reproduce consistently for me. I'll see if I can come up with something.
