### ISSUE TITLE
Error when trying to brew from source on mac

### ISSUE THREAD

**Issue by larsenwork** [fontforge/fontforge#2296] opened 2015-05-27 12:31 UTC
See the terminal output here: 
https://gist.github.com/andreaslarsen/ee78d2f28880ec26c405

I tried to follow this guide: 
https://github.com/fontforge/fontforge/blob/master/INSTALL-git.md

Installing dependencies without problems. But building source or release gives me the same build error

```
BuildError: Failed executing: ./bootstrap 
```

**Comment by andreaslarsen** [comment] 2015-05-27 12:33
Running a backtrace gives me this:
```
Choose an action: backtrace
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
/usr/local/Library/Homebrew/formula.rb:873:in `block in system'
/usr/local/Library/Homebrew/formula.rb:830:in `open'
/usr/local/Library/Homebrew/formula.rb:830:in `system'
/usr/local/Library/Formula/fontforge.rb:85:in `install'
/usr/local/Library/Homebrew/debrew.rb:22:in `block in install'
/usr/local/Library/Homebrew/debrew.rb:97:in `debrew'
/usr/local/Library/Homebrew/debrew.rb:22:in `install'
/usr/local/Library/Homebrew/build.rb:129:in `block in install'
/usr/local/Library/Homebrew/formula.rb:521:in `block in brew'
/usr/local/Library/Homebrew/formula.rb:911:in `block in stage'
/usr/local/Library/Homebrew/resource.rb:91:in `block in unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/forwardable.rb:171:in `stage'
/usr/local/Library/Homebrew/formula.rb:909:in `stage'
/usr/local/Library/Homebrew/formula.rb:517:in `brew'
/usr/local/Library/Homebrew/build.rb:107:in `install'
/usr/local/Library/Homebrew/build.rb:179:in `<main>'
```

**Comment by jtanx** [comment] 2015-05-27 12:35
May be related: #2019

**Comment by andreaslarsen** [comment] 2015-05-27 15:15
Ok, maybe @DomT4 can shed some light :)

**Comment by DomT4** [comment] 2015-05-28 00:52
Thanks for the ping, Happy to try and help. I can't reproduce locally, even without `argz.m4` existing in `/usr/local/share/aclocal`. Typically when this has happened before it's the result of dead symlinks, can you supply a `brew doctor` output?

**Comment by andreaslarsen** [comment] 2015-05-28 08:37
Yep, had bad symlinks - it fixed it. I feel like I'm missing something obvious but the resulting fontforge.app created is still only 5.6 mb and won't launch. 

Log: https://gist.github.com/andreaslarsen/f2fb50446841ce552649

**Comment by larsenwork** [comment] 2015-05-28 16:50
I updated the [instructions](https://github.com/fontforge/fontforge/blob/master/INSTALL-git.md) to include tip about `brew doctor` 

It looks like it builds successfully but the generated .app file doesn't work for me @DomT4

**Comment by DomT4** [comment] 2015-05-28 16:52
> but the generated .app file doesn't work for me @DomT4

Yeah, I can repro this. Will look into it tonight.

**Comment by larsenwork** [comment] 2015-05-29 09:29
@DomT4 I'm assuming it wasn't easily fixable? Let me know if I can help.

**Comment by DomT4** [comment] 2015-05-29 16:39
It seems to be a packaging problem. I'm not sure whether it's us or you yet:

The App crashes, but if you run the FontForge script inside the `.app` directly via the Terminal you run into: 

```
PKGBASE: /Applications/FontForge.app
/Applications/FontForge.app/Contents/MacOS/FontForge: line 127: /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge: No such file or directory
```

**Comment by larsenwork** [comment] 2015-05-29 16:50
There seems to be a lot of files missing inside the app (files size of 5-6 mb vs +380mb normally)
Looks like it's more or less just a copy of the fontforge.app on the repo without any files moved into it by homebrew.

**Comment by DomT4** [comment] 2015-05-29 17:12
I presume there's an additional step FontForge use to create applications that Homebrew doesn't. Most other app-generating projects run something like `make dist` which often isn't tenable for Homebrew because it can require root permissions to execute.

Consequently, it's not moving all of the Homebrew-installed generated "stuff" into the application (Which is fine IMO, we don't want to dupe a huge amount of stuff and create a massive install when the tools are already created and installed), and then when the application is moved the script inside isn't tweaked to expect the Homebrew locations.

As an aside, [this PR](https://github.com/Homebrew/homebrew/pull/39868) is going to cause trouble for you guys. I can tweak your testing mechanisms so they still work even after it's merged, but it's not clear at this point whether Homebrew will still support the FontForge GUI. IMO it may be a good idea to create your own Homebrew/fontforge tap and maintain whatever you need to maintain to support your setup long-term. It's not ideal for you guys I'm aware.

**Comment by larsenwork** [comment] 2015-05-29 17:33
@DomT4 ok, @davelab6 would probably want to read that and knows more (or know who knows more) about what steps FontForge needs to be created.

**Comment by DomT4** [comment] 2015-05-29 19:00
Aye. Talking to Dave has been on my schedule but I wanted to be sure of the implications/process of the outstanding Homebrew PR for FontForge beforehand.

**Comment by davelab6** [comment] 2015-05-29 19:42
Thanks for the heads up Dom!

Therefore, in my opinion, fontforge GUI via homebrew is dead.

I don't think anyone in the FF community (aside from possibly DomT4) would want to maintain a tap for all the packages; homebrew has a very high churn rate and I think it would be quite a big commitment. 

And since brewing the `.app` never worked for me, I'm okay with requiring GUI users to get a macports-based pre-build package. @larsenwork has been putting in a great effort to make the installation of a pre-built package even better on OS X, so I think we should now drive users to that. 

I think its important that fontforge's native and python scripting is available via homebrew.

**Comment by larsenwork** [comment] 2015-05-29 20:04
@davelab6 maybe a stupid question but how do we build the OS X app that we release - are there instructions for that anywhere?

**Comment by DomT4** [comment] 2015-05-29 20:12
Thanks for the quick reply Dave. I wouldn't be surprised if that was the outcome, no. I did voice some concerns about surprising you guys with this development, and had started thinking about a stop-gap PR here to keep your Travis up and running in the medium term.

In the end though the outstanding PR is likely the right move for Homebrew, the X11 backend in GTK+ has caused a decent amount of increasing complexity for a while. I had some thoughts about maintaining a personal GTK-Quartz tap, but I don't particularly have the time on top of everything else.

I use it personally so keeping a Homebrewed Fontforge GUI would have been ideal for me, but ideal for me does not always = ideal for Homebrew, heh.

> I think its important that fontforge's native and python scripting is available via homebrew.

The plan is for this to remain. CLI and Python scripting via that CLI will still be supported per the current PR.

**Comment by davelab6** [comment] 2015-05-29 20:24
yeah travis can still run after the pr right?

**Comment by DomT4** [comment] 2015-05-29 20:37
If you just want to test the build, sans X11, and the CLI element of FontForge - Yeah, Travis will be fine.

If you want to test the build with X11, you'll need to revert back to a previous version of the formulae involved, much as you already do for a couple of the formula. They will continue to function when scoped like that at least until a major Pango/Cairo update lands that you need to use. Unless Cairo/Pango do something unexpected, I'd expect Travis changes to ensure your testing mechanisms sustain for at least 6+ months.

**Comment by larsenwork** [comment] 2015-05-30 23:05
my initial issue is answered so @davelab6 can close this or change title or... :)

**Comment by bagong** [comment] 2015-06-11 13:58
Maybe it would be good not to advertise the homebrew (is it --HEAD?) option then. It's pretty frustrating to be positively surprised that the build works and then to find that you can't use it...

**Comment by DomT4** [comment] 2015-06-11 18:13
This hasn't been merged yet, It's still pending some fairly major review. For now the status quo remains (I'm using it myself) - You just launch FF from the CLI rather than an `.app` bundle.

**Comment by davelab6** [comment] 2015-06-11 19:56
you need the --with-x11 arg, not --HEAD (though it works with --HEAD too)

**Comment by bagong** [comment] 2015-06-11 21:54
Yes, I followed exactly the instructions (https://github.com/fontforge/fontforge/blob/master/INSTALL-git.md) and I find exactly what larsenwork found. So if your own statement `Therefore, in my opinion, fontforge GUI via homebrew is dead.` is valid it might be better not to suggest the homebrew distribution as primary installation source in the instructions. It makes sense, btw, homebrew is not really intended for gui-centered apps, they do not encourage the use of homebrew for this purpose.

**Comment by DomT4** [comment] 2015-06-11 23:13
I opened [this PR](https://github.com/caskroom/homebrew-cask/pull/11849) for discussion at the Caskroom, which would allow FontForge users to just do `brew tap caskroom/cask && brew cask install fontforge`.

**Comment by davelab6** [comment] 2015-06-12 14:36
The gui doesn't build at the moment anyway

```
$  brew install fontforge --HEAD --with-x11;
...
==> Summary
🍺  /usr/local/Cellar/fontforge/HEAD: 1304 files, 43M, built in 5.4 minutes
✔ ~ 
10:31 $ fontforge 
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 10:29 EDT 12-Jun-2015-ML-D.
 Based on source from git with hash: e3de383ac3bd721ec03468a169a4cf8454f715b5
no xdefs_filename!
TESTING: getPixmapDir:/usr/local/share/fontforge/pixmaps
TESTING: getShareDir:/usr/local/share/fontforge
TESTING: GResourceProgramDir:/usr/local/bin
trying default theme:/usr/local/share/fontforge/pixmaps/resources
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6
$
```

**Comment by DomT4** [comment] 2015-06-12 14:46
I haven't checked the HEAD in the last couple of weeks but was building fine before that, I'll try and free up some time to look into that this weekend. The Caskroom merged the FontForge cask, so you may wish to add that to your `INSTALL` documentation - Anyone who uses `brew` can use `brew cask`.

**Comment by davelab6** [comment] 2015-06-12 15:49
Brilliant, thanks Dom!

**Comment by frank-trampe** [comment] 2015-06-12 20:13
Uh. I missed this discussion. How many other packages does the change (dropping X11 support for GTK) break?

**Comment by davelab6** [comment] 2015-06-12 20:38
As I understand it, none, because homebrew generally didn't allow gui apps to be packaged into homebrew

**Closed** 2019-06-11 10:15 UTC
Labels: Homebrew, Mac OS X
