### ISSUE TITLE
Feature Request: Support for Variable Fonts

### ISSUE THREAD

**Issue by typedesigner** [fontforge/fontforge#2960] opened 2016-11-26 16:57 UTC
Hello @jtanx , @frank-trampe , @davelab6 

to cut a long story short, you can now export single- and multiple-axis Multiple Master files as Variable Fonts. And Brace Layers are supported too, by the way.
https://glyphsapp.com/blog/new-features-in-glyphs-2-4

Can you program this for FontForge?
https://github.com/mekkablue/ShowInterpolations

**Comment by davelab6** [comment] 2016-11-26 17:03
I suggest to wait for the next trufont release and then use that :)

**Comment by typedesigner** [comment] 2016-11-26 17:29
@davelab6 
I hope the new trufont will be released soon.
Unfortunately Glyphs-App  is not for Windows. FontForge is a good software to make a font. If you want to create multiple fonts from thin to black the FontForge does not interpolate.

**Comment by Gaudenz77** [comment] 2018-11-15 13:46
Are there any people still working on fontforge? For I have not enogh cash to get a Mac and so the reat Glyphs-App, I have to use fontforge, which therefor is a great opensource font app. But ther should be a variable font update, because this is the feature of the future (al´most through).

**Comment by MaddTheSane** [comment] 2019-03-16 22:54
There is already support for variable fonts: It's under the MM menu. It's also outdated: it doesn't support OpenType's version, but PostScript Multiple Masters and QuickDraw GX variable fonts.

This is better tracked in issue #2882.

**Comment by Gaudenz77** [comment] 2019-03-19 11:34
Thanks @MaddTheSane for answering!

**Comment by DanielRuf** [comment] 2019-08-20 07:09
So can we close this issue then?

**Comment by ctrlcctrlv** [comment] 2019-08-20 07:13
Closed as duplicate of #2882.

**Closed by ctrlcctrlv** 2019-08-20 07:13 UTC
