### ISSUE TITLE
Mouse-over tool tips do not always appear in opentype lookup editor windows

### ISSUE THREAD

**Issue by tisimst** [fontforge/fontforge#3597] opened 2019-03-28 17:56 UTC
Not sure how long it's been this way, but I've noticed that the mouse-over tool tips no longer appear like they used to when wanting to see, for example, what happens with a specific GSUB 'liga' rule. You used to could mouse over any line and it would show you a preview of the [after <- before] transformation, but nothing appears anymore. This could be bypassed by showing an actual plot, like in the kerning editor, of the before and after states, but I imagine that's probably a lot more work than getting the tool-tips working again. I love working with the recent build and would love to have something to preview these lookup rules.

Here's the kind of tool-tip I mean (font shown: Linux Libertine G):
![mouse-over-tool-tip](https://user-images.githubusercontent.com/2730119/55180802-f23f1f00-514f-11e9-873c-00f0d2e05492.png)

This is the FF version the above screenshot came from (latest public release, if I'm not mistaken):
![mouse-over-tool-tip-good-ff-version](https://user-images.githubusercontent.com/2730119/55180846-06831c00-5150-11e9-8ef7-f328c1183b9b.png)

And here's the FF version that won't show it anymore:
![mouse-over-tool-tip-bad-ff-version](https://user-images.githubusercontent.com/2730119/55180872-169afb80-5150-11e9-8191-e73507b17ff1.png)

I've tested this on Win 8.1 and 10.

**Comment by jtanx** [comment] 2019-03-28 20:24
This is a duplicate of #3550, it should be fixed if you try a more recent dev build.

**Closed by jtanx** 2019-03-28 20:24 UTC

**Comment by tisimst** [comment] 2019-03-28 21:47
Perfect! I promise I tried searching the issues, but didn't come up with anything. So I created this. Where can I find one of the recent appveyor builds?

**Comment by tisimst** [comment] 2019-03-28 21:51
Never mind. I found it. Thanks so much! Pardon the noise.
