### ISSUE TITLE
Problem generating BDF fonts

### ISSUE THREAD

**Issue by byouki-onna** [fontforge/fontforge#4102] opened 2020-01-22 13:56 UTC
Hello. Ive been directed here from the users mailing list. 
Im not sure this is actually a bug exactly, since I might just not quite understand the software, but im trying to work with bdf fonts using fontforge, and any font that I generate with the software is mangled, as so:
![2020-01-22-083819_758x500_scrot](https://user-images.githubusercontent.com/26748253/72899398-eaaac100-3cf3-11ea-98c9-d9c170ce4471.png)

The correct-looking font is a bdf untouched by font forge, the messed up looking one is one it generated. In this case, they're different fonts, but the problem is the same when the fonts are the same. If I open the font in fontforge, change nothing, and export it with the correct dpi settings , it looks like that.
Now, theres one unusual thing here, in that im converting the fonts to plan9 subfonts. But, as you can see above, an untouched bdf converts correctly, so that conversion ought to work correctly too. Ive also tried using the various compatibility and kerning options in the generate fonts dialogue to no avail.
[biwidth.tar.gz](https://github.com/fontforge/fontforge/files/4097594/biwidth.tar.gz)
Here is an example of one of the fonts im working with. 

Apologies if this is some trivial newbie problem. I admit Im really not familiar with this software, Its the only free program that seems to let me do what I'd like with the fonts im working with. (that being, merge together parts of two fonts selectively, not that it matters much here.)

**Comment by jtanx** [comment] 2020-01-22 21:32
What version of FontForge are you using?

**Comment by byouki-onna** [comment] 2020-01-22 23:34
version 20190801.

**Comment by ctrlcctrlv** [comment] 2020-01-23 01:38
Hello @byouki-onna. I'm the one on the list that told you to open an issue.

As you describe, I opened the font and generated another font. Except, unlike your description, it works fine for me, at least in KFontView.

We need to know what terminal program you are using and how you run it. Do you point it at the BDF file or is `fontconfig` involved as well? You are using 75 DPI, right, which seems to be default? Et cetera.

![2020-01-23-093923_502x158_scrot](https://user-images.githubusercontent.com/838783/72949732-17c6a480-3dc4-11ea-98d7-c0a8cbf9d076.png)

**Comment by byouki-onna** [comment] 2020-01-23 05:15
I see. I am indeed using 75 dpi. 
Until this point I havnt been viewing the fonts on unix, since I thought(wishful thinking maybe) that this wasnt a bug with either unix or plan9 font software, just user error, since the un-touched and mergebdf-ed fonts converted correctly with the bdf2subf utility.(for what its worth, theres nothing like fontconfig involved at any point here.) Feel free to dismiss me here if youd rather not hunt down some incompatibility with a foreign system whos only tell seems to be that it doesnt happen with openlab/efont files.  [http://openlab.jp/efont/](url)
(furthermore, I cant find a good utility to view/test font *files* without installing them on unix, without pulling all of KDE)
If you're still interested after that, someone else helped me find an interesting difference between the original font and the one generated by fontforge- the bounding boxes are all different.
00:09:33 khm → all the bounding boxes are different.:
00:09:52 khm → -BBX 16 16 0 -2
00:09:52 khm → -BITMAP
00:09:52 khm → -0000
00:09:52 khm → +BBX 15 14 0 -1
00:09:52 khm → +BITMAP
00:09:57 khm → etc
00:10:52 khm → some of the bounding boxes are WAY different
00:10:57 khm → -BBX 8 16 0 -2
00:11:02 khm → +BBX 1 10 4 0
00:12:36 ⇐ so probably, Id have to manually set spacing options in fontforge to get this to work, because its not importing that info from the original
00:12:47 ⇐ and unix programs correct it somehow

**Comment by frank-trampe** [comment] 2020-01-23 05:56
@byouki-onna, we don't mean to be difficult, but it should be easier for us to investigate if you would do the footwork of relating the possible aberrations to the actual expected values via the design intent and [the file format specification](https://www.adobe.com/content/dam/acom/en/devnet/font/pdfs/5005.BDF_Spec.pdf). Ideally, this would reveal one of the following.
* FontForge is emitting bounding box data that do not correspond to the bounding box that it displays in the character view.
* FontForge is displaying bounding box data that do not correspond to the bounding box data from the original input file.
* The input file has inconsistent or incorrect data.

**Comment by ctrlcctrlv** [comment] 2020-01-23 13:25
Plan 9 contains its own font format (`subf`) and has system commands to render fonts in that format, and no other format. Plan 9 does not support TrueType or OpenType fonts. 

So yes you do need to show that the problem is not the conversion to `subf` because, as demonstrated, FreeType understands FontForge's output fine. I guess a more targeted question is: **Why are the changes FontForge is making _wrong_ as per the spec, and why does FreeType, which is the standard font renderer, understand these changes when `bdf2subf` does not? That's the bar to clear here.**

And @frank-trampe, bless his heart, might not mean to be difficult, but I reserve my right to be difficult. If you're going to experiment with dead operating systems from the 90's, (instead of e.g. Redox OS,) you are going to be expected, at least by me, to do a level of legwork not required of a normal user coming to us with a Mac problem.

**Comment by byouki-onna** [comment] 2020-01-24 13:47
I do intend to investigate this. Ive been busy the past few days. Apologies.

**Comment by byouki-onna** [comment] 2020-01-24 13:53
Though, for what its worth, plan9 is actively developed to this day and does support TTF fonts secondarily.
And my attempts to use FF's output on plan9 are not 'experiments.' I use the system to do my daily computing wherever Im able to, and want fonts I think look nice.
I didn't think this was a bug at first, but the fact that it works fine with one BDF but not with the same as generated by FF is what makes me doubt it.
Im not here to harass you over obscure software you dont use. Again, Ill investigate more this afternoon and this weekend, and update if I find anything useful.

**Comment by byouki-onna** [comment] 2020-01-24 22:18
@frank-trampe 
Fontforge is most certainly outputting both bounding box files and bitmap data that *do not* correspond to the input file. In fact, not only are the bounding boxes different, the bitmap data is different- padding 0's are stripped from the input file.
Heres an example: character 0x61(97('a')) in the original bdf file, its bounding box and bitmap info:
`
BBX 8 16 0 -2
BITMAP
00
00
00
00
00
3c
42
02
3e
42
82
82
86
7a
00
00
ENDCHAR`
and the one generated by fontforge:
`ENCODING 97
SWIDTH 480 0
DWIDTH 8 0
BBX 7 9 0 0
BITMAP
3C
42
02
3E
42
82
82
86
7A
ENDCHAR`
from glancing at the bdf spec, this looks wrong to me, though I dont suppose I understand the spec thoroughly. The spec says:

> BITMAP introduces the hexadecimal data for the character bitmap. From the BBX value for h, find h lines of hex-encoded bitmap, padded on the right with zero’s to the nearest byte (that is, multiple of 8)

Id guess that fontforge thinks it can strip the padding zeros by changing the bounding box, and this relates to some special feature of the X server or of fontconfig or something like that that supports this because someone didnt like the padding at some point, but it breaks it on implementations.
In either case, it ought to respect the spec, yes? That way it'd work everywhere. 
or do I misunderstand the spec, or what im looking at? I may.

**Comment by byouki-onna** [comment] 2020-01-24 22:20
(this test was done with this input file, not b16.bdf, since this is smaller and easier to test. apologies for not including it in that post.)
[8x16.tar.gz](https://github.com/fontforge/fontforge/files/4110948/8x16.tar.gz)

**Comment by jtanx** [comment] 2020-01-24 23:43
The spec only mentions padding to the nearest byte, so the BITMAP data as generated by FontForge is valid.

It looks like the input keeps a fixed bounding box for all glyphs, and pads the BITMAP data as required, whereas FontForge is recalculating it for all glyphs:

https://github.com/fontforge/fontforge/blob/118ae04228110d4788670c257ec6e1133b1a2849/fontforge/splinefill.c#L730

**Comment by byouki-onna** [comment] 2020-01-25 00:00
I see.
Is there any way for me to prevent it from doing this in the UI?
I just want the font to come out like it went in.

**Comment by jtanx** [comment] 2020-01-25 00:00
No.

**Comment by jtanx** [comment] 2020-01-25 00:27
Clarifying, if you were to comment out `BCCompressBitmap`, and recompile FF, it might be enough to get away with what you want, but the problem is ultimately that whatever conversion tool you're using isn't parsing BDFs properly, and ideally that should be fixed instead.

**Comment by ctrlcctrlv** [comment] 2020-01-25 01:07
Closing.

This by the way is completely wrong:

> Though, for what its worth, plan9 is actively developed to this day and does support TTF fonts secondarily.

:roll_eyes: 

Yes, if you compile FreeType on Plan 9, and then run a font through `ttf2subf`, you can get a "TTF font in Plan 9", sort of, but of course not really, because Plan 9 only understands `subf` format, and the font you get will not even be scalable.

**Closed by ctrlcctrlv** 2020-01-25 01:07 UTC
Labels: dubious

**Comment by byouki-onna** [comment] 2020-01-25 01:10
Its not developed by labs anymore. Its still actively developed by the community. I use the most developed distribution.
I was not referring to ttf2subf. I was referring to truetypefs. Which provides actual, real support for true type fonts.
Plan 9 understands the ttf format since 2018. 
@jtanx
Your suggestion worked perfectly. Thank you for your help. Im greatly appreciative.

**Comment by frank-trampe** [comment] 2020-01-25 01:15
@byouki-onna, it might be worth filing a bug on the Plan 9 side now that we have specifics on the problem.

**Comment by byouki-onna** [comment] 2020-01-25 01:18
@frank-trampe 
In this case itd be fixing the problem myself. Ill most likely look into it, though.

**Comment by ctrlcctrlv** [comment] 2020-01-25 01:23
It is my understanding that `truetypefs` works internally by parsing TTF fonts and outputting `subf` fonts on demand, similar to how the old FreeType hack worked. I could be wrong though, the 9front developers would know for sure.

**Comment by byouki-onna** [comment] 2020-01-25 01:26
Indeed, but the fonts are scaleable. it generates them at a given size on demand.

**Comment by ctrlcctrlv** [comment] 2020-01-25 02:00
That's not my understanding of scalable, but I really think we're just splitting hairs at this point.

**Comment by byouki-onna** [comment] 2020-01-25 02:12
Im not sure what you mean. 
The user doesnt generate unifont.ttf.16 to use with truetypefs, or something like that. If you say that your font is /n/ttf/unifont.ttf.24, then start a graphical program, it will ask for that font, and truetypefs looks in /lib/ttf for unifont.ttf, your program will display a size 24 version of unifont. If you say unifont.ttf.16/font, itll display a size 16 verison. There are no 'real' files in /n/ttf. 
Of course, no programs I know of support changing your font without restarting the program, though I suppose they probably could if someone wanted that. If thats what you meant, yeah, its a matter of what one cares about I suppose.

**Comment by ctrlcctrlv** [comment] 2020-01-25 02:19
That's not exactly what I meant. Outside of Plan 9, user programs are expected to parse and rasterize outline fonts. (Which in my opinion is the best way to do it, mind you.) User programs, then, _could_ rasterize the whole font at the size they need and store it all in memory, but that's not how it usually works in practice. 

I saw you join #fontforge on Freenode and am happy to discuss it further with you there if you rejoin, but I think that any further replies to this topic are needless noise for other developers not interested in Plan 9/9front.
