### ISSUE TITLE
No file name showing in latest release...

### ISSUE THREAD

**Issue by JonathanMagus** [fontforge/fontforge#2361] opened 2015-06-13 08:06 UTC
I have just installed the 12th June 2015 build taken from here and then tried the 13th June Windows Builds release from SourceForge to make sure they were the same. In both cases 'VcXsvr X' shows consistently at the top left of the window (of all windows) where the file name should be. This is really unhelpful when alternative versions of a file are in use (as in a master and a copy), or when more than one font file is open at the same time and characters are being opened in new windows.

It is good to have the bug fixes and improvements, however, this is a usability issue that has forced me to reinstall an earlier version from the 1st May 2015 where the file name is shown. The intermediate releases also appear to have this error.

**Comment by jtanx** [comment] 2015-06-13 09:07
Oops, looks like something is interfering with setting XLOCALEDIR on your configuration. Quick questions:

1. What is your Windows setup (Windows 7? English? US? 32 bit?)
2. Do you have any non ASCII characters in your installation path?

**Comment by JonathanMagus** [comment] 2015-06-13 09:45
It is a Windows 7 Professional 64 bit system (English UK) and the installation path is to the default Program Files (x86) location chosen by the installer, which is "C:\Program Files (x86)\FontForgeBuilds\run_fontforge.exe". That has been used consistently.

This also occurs with the 26th May release, which I had downloaded previously though had not installed before downloading and installing the 12th June version today. It is not a problem for the 1st of May release that I have reverted to and was previously using.

**Comment by jtanx** [comment] 2015-06-13 09:56
Yes, it's due to a change in how window titles were handled on Windows. Could you please try this? Edit `fontforge.bat` (in the Program files location) so that lines 5 and 6 are this:

    set "XLOCALEDIR=%FF%bin\VcXsrv\locale"
    set "XLOCALELIBDIR=%XLOCALEDIR%"

And try running again. If it still doesn't work, can you try starting the 'interactive console' (fontforge-console.bat), running fontforge once (type `fontforge`, press enter, wait for it to open then close it), then enter:

    echo %XLOCALEDIR%

What is the result of that?

**Comment by jtanx** [comment] 2015-06-13 10:00
Oh, I think I might know why. It's probably unrelated to my previous comment.

--------

I see this comment in `locale.alias`: `# parser doesn't grok embedded spaces in locale name`. I'm guessing `English_United Kingdom.1252` is your locale. Hmm... I need to investigate more.

**Comment by JonathanMagus** [comment] 2015-06-13 10:35
OK. I’ll leave it with you.

**Comment by jtanx** [comment] 2015-06-13 13:16
I've done some testing and I can't seem to replicate the issue. Could you please try the steps I outlined before?

**Comment by JonathanMagus** [comment] 2015-06-13 14:26
I have tried this, which doesn’t fix it either.

 

The original fontforge.bat file (12th June 2015 version) has an extra backslash in the 5th line. Removing it, which then gives the two lines as suggested, has no effect. Trying this again exactly as in your reply, so including the inverted commas that are not in the original file does nothing either.

 

Starting via fontforge-console.bat, as suggested, closing and then entering echo %XLOCALEDIR% gives a line that says this:

 

C:\Program Files (x86)\FontForgeBuilds\bin\VcXsrv\locale

 

Reinstalling the 1st May 2015 version that picks up the file name correctly, I note that line 6 is not in its fontforge.bat file at all. Repeating the process gives a line in fontforge-console.bat with two backslashes before bin like this:

 

C:\Program Files (x86)\FontForgeBuilds\\bin\VcXsrv\locale

 

Not sure what this means, though hope it helps.

 

For now I have reverted to the 1st May 2015 version.

**Comment by jtanx** [comment] 2015-06-13 15:07
Thanks for taking the time to perform those tests. It seems that at least that variable is being set correctly. I'll have to look further into this tomorrow, but just to confirm - you weren't running FontForge during installation? Also just check that (when FontForge is closed) VcXsrv is not running (you normally see it in your system tray area, it shows up in the task manager as vcxsrv.exe)

**Comment by JonathanMagus** [comment] 2015-06-13 15:50
No. Fontforge was not running during installation on each of the occasions I have done this and VcXsrv is not showing when it is closed. I have just checked that again in Task Manager.

 

I was installing over the top of the previous installation though, which is what I have usually done before. And there may be an old version of the 64 bit portable version on the hard drive, not currently in use. I cannot see that either of those are likely to be relevant, as neither has created issues previously. There is nothing unusual about the Windows set up as far as I am aware. Service pack 1 is installed.

 

Whatever it is it is only present in Fontforge versions after 1st May 2015.

**Comment by jtanx** [comment] 2015-06-13 23:54
Thanks for confirming. I've been able to reproduce it in a VM set to UK so I'll see what I can find.

**Comment by jtanx** [comment] 2015-06-14 01:07
Okay, I know why this is happening.`setlocale` is called with an empty string at [`start.c:107`](https://github.com/fontforge/fontforge/blob/126811791952e6b10b3742c0cb6f7dc78413b2a4/fontforge/start.c#L107), which in turn sets the locale to the ['implementation-defined native environment'](https://msdn.microsoft.com/en-us/library/x99tb11d.aspx) - i.e. `English_United Kingdom.1252`.

When Xlib processes this, it converts the spaces in the name to dashes at [`SetLocale.c:192`](http://cgit.freedesktop.org/xorg/lib/libX11/tree/src/SetLocale.c#n192), i.e. `English_United-Kingdom.1252`.

So when it searches `locale.alias` (in the bin/VcXsrv/locale folder) which has the name with spaces in it, it cannot find the right locale to use. 

I have altered `locale.alias` to match this behaviour of having dashes in the names. 

--------

@JonathanMagus, please try the latest build from [here](https://sourceforge.net/projects/fontforgebuilds/), it should be dated `FontForgeSetup-14-06-2015.exe` (portable version is `99da6f-r2`)

**Comment by jtanx** [comment] 2015-06-14 01:22
@JonathanMagus I've updated the official binary now too so you can [download that](https://github.com/fontforge/fontforge/releases/download/20150612/FontForge-2015-06-12-Windows.exe) if you prefer

**Comment by JonathanMagus** [comment] 2015-06-14 11:19
Thanks! That has fixed it. The file names are showing correctly now.

**Closed** 2015-06-14 11:54 UTC
Labels: I-bug, regression, Windows
