### ISSUE TITLE
Stroke expansion regressions

### ISSUE THREAD

**Issue by joshuakraemer** [fontforge/fontforge#2025] opened 2015-01-02 15:27 UTC
Until now, I have used Fontforge version 2012-07-31.  I tried version 2014-11-26 now and found two regressions in the stroke expansion tool.  The attached images show the correct expansion result from the old version on the left, and the faulty result from the new version on the right.  The green line shows the original stroke in the background.  The strokes have been expanded with the "round" setting for line cap and line join.  The problems are the following:

(1) At some line joins, the expanded stroke is cut off:

![3](https://cloud.githubusercontent.com/assets/10373011/5597013/4f72147a-929b-11e4-8264-178a9a8549be.png)

(2) At some line joins, the expanded stroke is distorted:

![5](https://cloud.githubusercontent.com/assets/10373011/5597012/4f7214b6-929b-11e4-8e80-4e87fabddc56.png)
![w](https://cloud.githubusercontent.com/assets/10373011/5597014/4f768b72-929b-11e4-80c5-48126b69c1a0.png)

**Comment by dimitre** [comment] 2015-04-01 16:18
Second this issue, same thing happening here

**Comment by dimitre** [comment] 2016-07-05 18:37
hello @joshuakraemer did you find any way of avoiding this issue? I'm keeping an 2012 verion installed in an old system.

**Comment by frank-trampe** [comment] 2016-07-05 18:50
@dimitre, is there any chance that you could bisect the problem? I'm stretched rather thin right now, and this is a lot easier for me to fix if I know which commit caused it.

**Comment by dimitre** [comment] 2016-07-05 18:53
I'll seek information on how to do it and try it @frank-trampe

**Comment by joshuakraemer** [comment] 2016-07-05 22:14
@ <https://github.com/dimitre>dimitre <https://github.com/dimitre>,
unfortunately not. I'm keeping an old version, too.

**Comment by jtanx** [comment] 2016-07-08 05:15
Would you be able to provide a sample to test this on?

**Comment by dimitre** [comment] 2016-07-08 13:40
Great @jtanx I've just generated a sample to test here:
The last two lines are just useful if you are in OS X so it opens the generated file. You will recognize the regression because this generates a bump in the center of W letter. 

```python
# -*- coding: UTF-8 -*-
'''
cd ~/Desktop/WORK_DMTR/syntype_python/
python regression.py

'''

import fontforge
import random
font = fontforge.font()
font.encoding = "UnicodeBmp"
font.familyname = 'test' + str(random.randint(0,99999))

caracter = 'W'
font.createMappedChar(caracter).unicode
pen = font[caracter].glyphPen()
contorno = fontforge.contour()
aresta = 100.0
coords = "0,6 1,0 2.5,5 4,0 5,6".split(' ')
for c in coords:
	p = c.split(',')
	tipo = 3
	if len(p) > 2:
		tipo = int(p[2])
	contorno.insertPoint((float(p[0]) * aresta, float(p[1]) * aresta))
raio = 30
contorno.draw(pen)
espessura = 90
font[caracter].stroke('circular', espessura, 'round', 'round')  #butt round square -- miter round bevel
fontfilename = '_generate/'+font.familyname+'.otf'
#fontfilename = ''+font.familyname+'.otf'

print fontfilename
print font.generate(fontfilename)
import os
os.system('open '+fontfilename)
```

**Comment by jtanx** [comment] 2016-07-09 04:20
Thanks @dimitre, after some searching, I think I've found the issue - 4f883fddfffb1c5d19a58468bd8f4e7bbb4f381e

Although that commit was supposed to fix another bug...

**Comment by jtanx** [comment] 2016-07-09 08:07
I've made #2739 which seems to work, but I'm not completely certain that it's the right fix either - i.e. not sure if it breaks expand stroke for other cases. It's also difficult to compare the output from the SFDs since it looks like the 2012 version rounds to the nearest 3/4 decimal places(??) whereas the latest version doesn't. 

Funnily enough, the Windows build of the 2012 version doesn't seem to suffer from the infinite loop issue which resulted in 4f883fd. If someone could see if the following results in either a segfault or an infinite loop on the 2012 version on Linux or OS X, that'd be great:

~~~~~
fontforge -lang=py -script test1003.py fonts/StrokeTests.sfd
~~~~~

(Get [test1003.py](https://github.com/fontforge/fontforge/blob/master/tests/test1003.py) and [StrokeTests.sfd](https://github.com/fontforge/fontforge/blob/master/tests/fonts/StrokeTests.sfd) from the testing folder of current master)

**Comment by dimitre** [comment] 2016-07-09 12:23
Thank you @jtanx this is great news! 
I can only build FF here using homebrew so I think I can only test after it is merged in HEAD branch. 
I can try to generate different cases for expand stroke if you think it is useful.

**Comment by joshuakraemer** [comment] 2016-07-11 18:08
@jtanx: The test seems to works for me.
`> fontforge -lang=py -script test1003.py StrokeTests.sfd
Copyright (c) 2000-2012 by George Williams.
 Executable based on sources from 14:57 GMT 31-Jul-2012-ML.
 Library based on sources from 14:57 GMT 31-Jul-2012.
triangle
square
pentagon
circular
caligraphic
>`

**Comment by dimitre** [comment] 2016-07-20 04:21
I'm writing you to thank you all, and notice @joshuakraemer that the issue is fixed now and can be closed.

**Closed** 2016-07-21 08:23 UTC
Labels: I-bug
