### ISSUE TITLE
FF compiled with Python 3 extension loads "empty" fontforge module.

### ISSUE THREAD

**Issue by tobltobs** [fontforge/fontforge#2966] opened 2016-11-30 22:25 UTC
I am trying to compile fontforge from source with Python 3. I recently manged to compile it on Ubuntu workstation and now have to install it on a Debian or Ubuntu Server and run into a strange error.

I am using the Version https://github.com/fontforge/fontforge/archive/20161012.tar.gz
as imho this one has the `import psMat` problem solved.

My compile steps:
```
./bootstrap
PYTHON="python3" ./configure
make -j3
make install
```
The relevant configure output:
```
Configuration:

  Source code location	.
  Build code location	
  Destination prefix	/usr/local
  Compiler		gcc -std=gnu99 -std=gnu99

Summary of optional features:

  real (floating pt)	double
  programs		yes
  native scripting	yes
  python scripting	yes
  python extension	yes
  freetype debugger	no
  raw points mode	no
  tile path		no
  gb12345 encoding	no
  potrace or autotrace	yes
...
```

But when I do `python3 -c "import fontforge; f = fontforge.font()"` it results in:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'font'
```
A `python3 -c "import fontforge; print(dir(fontforge))"` gives a:
`['__doc__', '__loader__', '__name__', '__package__', '__path__', '__spec__']`
Somehow the fontforge module is empty?

**More details**
`make install` outputs an 
```
Libraries have been installed in:
   /usr/local/lib/python3.4/site-packages
```
And indeed:
```
ls -la /usr/local/lib/python3.4/site-packages
total 48
drwxr-sr-x 2 root staff  4096 Nov 30 21:53 .
drwxrwsr-x 4 root staff  4096 Nov 30 21:53 ..
-rwxr-xr-x 1 root staff  1429 Nov 30 21:53 fontforge.la
-rwxr-xr-x 1 root staff 13992 Nov 30 21:53 fontforge.so
-rwxr-xr-x 1 root staff  1405 Nov 30 21:53 psMat.la
-rwxr-xr-x 1 root staff 13968 Nov 30 21:53 psMat.so
```
I tried it on Debian 8 and Ubuntu 16.04. I also tried it with the additional `--enable-python-scripting --enable-pyextension --enable-python-extension` options for `./configure`. Also a `ldconfig` after make install didn't help.
When I did install it on my Workstation I did use a Virtual Enviroment and a custom` --prefix`. However, I also also tried this on the Debian server but without success.
The servers have been fresh installs before testing.
I also tried with the latest version from git.

Does anybody has an idea what is wrong with my installation process?

**Update**
I did another test, this time with an virtual env again. When I did a 
```
python -c "import fontforge;print(fontforge)" 
<module 'fontforge' (namespace)>
```
it seems that an import fontforge doesn't load the .so file but the fontforge directory in `/root/venv/lib/python3.4/site-packages` which contains the .so file. 

Moving those .so files to the parent dir and remove the fontforge dir:
```
mv /root/venv/lib/python3.4/site-packages/fontforge/* /root/venv/lib/python3.4/site-packages
rm /root/venv/lib/python3.4/site-packages/fontforge
```
But now:
```
python -c "import fontforge" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: libuninameslist.so.1: cannot open shared object file: No such file or directory
```
But the libuninameslist.so.1 file is in `/usr/local/lib`.

***Update 2***
If I add `/usr/local/lib/python3.4/site-packages` to the `sys.path` everything looks fine.
```
python3 -c "import sys; sys.path.append('/usr/local/lib/python3.4/site-packages'); import fontforge; f=fontforge.font(); print(f)";
<Font: Untitled1>
```

**Comment by felipesanches** [comment] 2019-03-14 00:09
@tobltobs, on your **Update 2** you mention a workaround. Have you been using it this way in the past couple years? Or did you give up?

I tried to experiment with similar workarounds but it does not work to me. I sincerely do not even understand exactly why should it work as a solution.

i would like to better understand what is the root cause of this bug so that it can be fixed. I have been investigating it and I have written about it elsewhere (https://github.com/googlefonts/fontbakery/issues/2261#issuecomment-472568531), but I will copy that report in here, which seems to the best place for it to be shared among fontforge developers.


----

**frank-trampe** had said on Dec 28, 2018:
> Was there an issue compiling FontForge against Python 3 in your environment? If so, please report so that I can fix it. Much easier than starting from zero.

@frank-trampe, I came back to this problem earlier this week. I tried to compile FontForge with python 3 on Debian stretch. By doing `PYTHON=3.7 ./configure` I got it built sucessfully. The python scripting checks all pass when doing `make check`. But after `sudo make install`, I tried to run `import fontforge` on a python 3 interpreter and got exactly the same problem described here by @tobltobs. It seems to load an "empty" module.

Then I looked more carefully at the testsuite and I noticed that on `fontforge/tests/testsuite.at`, this is how python checks are invoked:
```
#--------------------------------------------------------------------------
# Fontforge Python Scripting test functions

m4_defun([run_python],[(${abs_top_builddir}/fontforgeexe/fontforge -lang py -script "${abs_srcdir}/$1" "$2" || /bin/false)])
```

It means that the check code is not running on a standalone python interpreter, but by invoking fontforge which then does something which I presume is to load its embedded copy of the python interpreter, or something like that.

**Comment by skef** [comment] 2019-03-14 00:35
I have been working with recent revisions of FontForge by compiling and installing them in the normal way on my Arch Linux box, which is python 3-based. I've also done extensive python testing with "#!/usr/bin/env python" scripts and invoking scripts with python directly. A number of python-3 specific bugs have been fixed recently, but the install infrastructure hasn't changed as far as I know. 

To work through this let's concentrate on the differences between our two builds/install sequences. Start replacing
```
PYTHON=3.7 ./configure
```
with
```
PYTHON=python3 ./configure
```
or if "python" on your system is python 3, just do `./configure`.

**Comment by felipesanches** [comment] 2019-03-14 12:42
Sorry, I just noticed that I had a typo on my previous message. I actually did use `PYTHON=python3.7 ./configure`. I have just edited the message to fix the typo.

**Comment by skef** [comment] 2019-03-14 12:58
OK, so: Is "python3.7" the name of the python binary or execution script on your system? That's what the `PYTHON` environmental variable is for -- a hook to configure to tell it the name of the python program to use, from which it extracts the version information, install directories, etc.

To confirm, `configure` prints a couple stanzas of information about what systems it will use to build and install when it finishes. Can you cut-and-paste those here?

**Comment by anthrotype** [comment] 2019-03-14 13:00
I suspect that your python3 is attempting to import a directory with that name "fontforge" in your working directory. Any directory is an implicit namespace package in python3

**Comment by skef** [comment] 2019-03-14 13:07
Before we get into more esoteric explanations, let's just determine:

1. What configure says about the python version,
2. Whether the build process is actually building the modules
3. Where, if anywhere, it is installing them. 

configure prints out information like this:
```
Configuration:

  Source code location  .
  Build code location
  Destination prefix    /usr
  Compiler              gcc

Summary of optional features:

                        UseIt?  HaveIt?
  real (floating pt)            double
  programs              yes     yes
  native scripting      yes     yes
  python scripting      check   yes3.7
  python extension      check   yes
  freetype debugger             no
  raw points mode               no
  tile path                     no
  gb12345 encoding              no
  fontforge-extras      yes     no
  potrace or autotrace  yes

Summary of optional dependencies:

Optional Library        UseIt?  HaveIt? WebsiteURL
  giflib                check   yes     http://giflib.sourceforge.net/
  libjpeg               check   yes     http://en.wikipedia.org/wiki/Libjpeg
  libpng                check   yes     http://www.libpng.org/
  libreadline           check   yes     http://www.gnu.org/software/readline
  libspiro              check   yes     https://github.com/fontforge/libspiro
  libtiff               check   yes     http://en.wikipedia.org/wiki/Libtiff
  libuninameslist       check   no      https://github.com/fontforge/libuninameslist
  python-dev            check   yes     https://www.python.org/
  woff2                 no              https://github.com/google/woff2

Graphical UI Choices    UseIt?  HaveIt? WebsiteURL
  X Window System                       http://www.x.org/
    cairo               check   yes     http://www.cairographics.org/
  GDK backend           yes     GDK3    http://www.gtk.org/
  zeromq (libzmq)               no      http://www.zeromq.org/
```
That's step 1.

**Comment by anthrotype** [comment] 2019-03-14 13:10
sorry, but this is not esoteric. It's actually what's happening by looking at felipe's earlier comments:

```
python -c "import fontforge;print(fontforge)" 
<module 'fontforge' (namespace)>
```

that's what you get if you happen to have a folder named in this case "fontforge" in the current working directory. See that the module repr has "(namespace)" in it, meaning python things it's a PEP420 implicit namespace package (which fontforge is not supposed to be).

Try to cd into a different directory where there's no "fontforge" sub-folder. I expect you to get ImportError in that case.

**Comment by skef** [comment] 2019-03-14 13:18
Ok, but @tobltobs and @felipesanches are different users, the latter of which is updating a bug filed by the former 3 years earlier. @felipesanches is not indicating that they are running that command putting any particular interpretation on its output. And the fundamental issue is why the modules aren't being found.

**Comment by anthrotype** [comment] 2019-03-14 13:20
> the fundamental issue is why the modules aren't being found

agreed. I was just pointing out the reason for that "empty" fontforge module Felipe is seeing (which is also the title of this issue report). I haven't followed the rest of the issue, sorry for the noise anyway.

**Comment by felipesanches** [comment] 2019-03-14 13:26
Earlier this week I started studying Debian packaging and considered creating a python3-fontforge package (as mentioned at https://github.com/fontforge/fontforge/issues/1731#issuecomment-471242141). I created a git repo to document my efforts, but later stumbled on this bug. So, the contents of the repo are not actually debian-packaging rules anymore, so please ignore the repo name below:

This is a build log of FontForge being built with python 3.6:
https://travis-ci.com/felipesanches/FontForge-Debian-Packaging/builds/104362513

And here is the corresponding Travis config:
https://github.com/felipesanches/FontForge-Debian-Packaging/blob/39d10e4cb48d8b133994b72b217c0a03075ce31c/.travis.yml

As you can see, in that example I use `PYTHON=python3.6 ./configure` and get this output:
```
Summary of optional features:
			UseIt?	HaveIt?
  real (floating pt)		double
  programs		yes	yes
  native scripting	yes	yes
  python scripting	check	yes3.6
  python extension	check	yes
```

**Comment by felipesanches** [comment] 2019-03-14 13:28
It seems to me that @anthrotype's comments make a lot of sense. Maybe the bug is indeed related to a fontforge directory somehow messing up the python module loading.

**Comment by skef** [comment] 2019-03-14 13:37
I haven't done this particular debugging in the past, but I would say the relevant lines are these:
```
Packaging/fontforge/pyhook'
 /bin/mkdir -p '/home/travis/fforge_stuff/lib/python3.6/site-packages'
 /bin/bash ../libtool   --mode=install /usr/bin/install -c   psMat.la fontforge.la '/home/travis/fforge_stuff/lib/python3.6/site-packages'
libtool: warning: relinking 'psMat.la'
libtool: install: (cd /home/travis/build/felipesanches/FontForge-Debian-Packaging/fontforge/pyhook; /bin/bash "/home/travis/build/felipesanches/FontForge-Debian-Packaging/fontforge/libtool"  --silent --tag CC --mode=relink gcc-8 -Werror=implicit-function-declaration -Werror=int-conversion -fdiagnostics-color=always -Wall -Wno-switch -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wrestrict -Wnull-dereference -Wjump-misses-init -Wdouble-promotion -Wshadow -no-undefined -module -shared -avoid-version -o psMat.la -rpath /home/travis/fforge_stuff/lib/python3.6/site-packages psMatpyhook.lo ../Unicode/libgunicode.la ../gutils/libgutils.la ../gutils/libgioftp.la ../fontforge/libfontforge.la -lX11 -lm -lltdl )
libtool: install: /usr/bin/install -c .libs/psMat.soT /home/travis/fforge_stuff/lib/python3.6/site-packages/psMat.so
libtool: install: /usr/bin/install -c .libs/psMat.lai /home/travis/fforge_stuff/lib/python3.6/site-packages/psMat.la
libtool: warning: relinking 'fontforge.la'
libtool: install: (cd /home/travis/build/felipesanches/FontForge-Debian-Packaging/fontforge/pyhook; /bin/bash "/home/travis/build/felipesanches/FontForge-Debian-Packaging/fontforge/libtool"  --silent --tag CC --mode=relink gcc-8 -Werror=implicit-function-declaration -Werror=int-conversion -fdiagnostics-color=always -Wall -Wno-switch -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wrestrict -Wnull-dereference -Wjump-misses-init -Wdouble-promotion -Wshadow -no-undefined -module -shared -avoid-version -o fontforge.la -rpath /home/travis/fforge_stuff/lib/python3.6/site-packages fontforgepyhook.lo ../Unicode/libgunicode.la ../gutils/libgutils.la ../gutils/libgioftp.la ../fontforge/libfontforge.la -lX11 -lm -lltdl )
libtool: install: /usr/bin/install -c .libs/fontforge.soT /home/travis/fforge_stuff/lib/python3.6/site-packages/fontforge.so
libtool: install: /usr/bin/install -c .libs/fontforge.lai /home/travis/fforge_stuff/lib/python3.6/site-packages/fontforge.la
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin" ldconfig -n /home/travis/fforge_stuff/lib/python3.6/site-packages
----------------------------------------------------------------------
Libraries have been installed in:
   /home/travis/fforge_stuff/lib/python3.6/site-packages
If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'
See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
```
This is what you would expect, given this output from `configure`:
```
Configuration:
  Source code location	.
  Build code location	
  Destination prefix	/home/travis/fforge_stuff
  Compiler		gcc-8
```
So first try this: In your shell do `export PYTHONPATH=$PYTHONPATH:/home/travis/fforge_stuff/lib/python3.6/site-packages`. Then also in that shell do a test passing "python3.6" some fontforge scrpt. With luck it will import and make successful use of the `fontforge` module. 

If that works, the next step is verifying that a "non-experimental" build puts the objects in the right location.

**Comment by anthrotype** [comment] 2019-03-14 13:42
> Maybe the bug is indeed related to a fontforge/ directory somehow messing up the python module loading.

I don't think so. If the fontforge module was correctly built and found in the python path, then the mere presence of a "fontforge" folder in your working directory would not take precedence.

**Comment by felipesanches** [comment] 2019-03-14 13:45
just a quick note: I know the destination prefix is named unconventionally. The reason for that choice was to separate it form the rest of the travis VM system libraries so that I could pack it all into a tarball and publish it to the gh-pages branch.

Later I did unpack the tarball into `/usr/local/` and had the import failure (the "empty" module was loaded). The only workaround I was able to find was to run python scripts using this build by passing them to fontforge just like the `testsuite.at` file does. But that's a hack! I hope we can figure out the proper way of installing the module so that it can be cleanly imported in any simple python 3 script with a plain `import fontforge` and nothing else.

**Comment by felipesanches** [comment] 2019-03-14 13:47
Is there any other aspect of my local setup that could help us figure out what's not quite right yet on the current build/install rules?

**Comment by skef** [comment] 2019-03-14 13:47
@felipesanches : OK, then what you first need to do is determine where Debian wants python 3.6 site-packages installed on its system. If python doesn't look in under `/usr/local` for them, putting them there won't help.

**Comment by anthrotype** [comment] 2019-03-14 13:48
run 
```
$ python3.6 -m site
```

**Comment by skef** [comment] 2019-03-14 13:48
"You're" installing in a temporary place and then moving binaries. That will generally work, but they need to end up in the right places and that's "you're" responsibility. ("You" being the install infrastructure.)

**Comment by felipesanches** [comment] 2019-03-14 13:49
On the experiments in my local computer I did put them on `/usr/local/lib`, but on Travis I did place them directly on `/usr/lib`.

**Comment by skef** [comment] 2019-03-14 13:50
What does @anthrotypes's suggested command say?

**Comment by felipesanches** [comment] 2019-03-14 13:52
>  "You're" installing in a temporary place and then moving binaries

I started making experiments after the base `sudo make install` did not work. Regardless of all variations of experiments that I did afterwards, the default install target of the build rules (which was my very first attempt, and seems to have been the case with @tobltobs in the past) should be sane/working.

**Comment by skef** [comment] 2019-03-14 13:59
Our configure infrastructure is designed for a "direct" installation. I believe it attempts to determine the correct site-path directory when used that way. You're "redirecting" the installation, and I don't know what configure does in that case. If you say `--prefix=/usr/local` or `--prefix=/home/xxx/yyy` and python's preferred site-path isn't under that directory, the script has to make a weird decision about where to put things. 

What directory are you expecting the modules to wind up in and why?

**Comment by felipesanches** [comment] 2019-03-14 14:00
my first install attempt was to the default prefix and did not work.

**Comment by skef** [comment] 2019-03-14 14:01
In any case, can we do things in the verify-and-then-debug order? First try moving the modules it built by hand to the location python3.6 expects them and see if the script runs. If that works, everything else is configuration.

**Comment by felipesanches** [comment] 2019-03-14 14:07
This was my first attempt:
```
git clone https://github.com/fontforge/fontforge.git
cd fontforge
./bootstrap
PYTHON=python3.6 ./configure
make
sudo make install
```

![Screenshot at 2019-03-14 11:06:54](https://user-images.githubusercontent.com/213676/54363238-724e8a80-4662-11e9-90f3-b5b4338fef3b.png)

**Comment by felipesanches** [comment] 2019-03-14 14:10
> What does @anthrotypes's suggested command say?

![Screenshot at 2019-03-14 11:09:44](https://user-images.githubusercontent.com/213676/54363449-dec98980-4662-11e9-99c7-a92ed62e2385.png)

**Comment by skef** [comment] 2019-03-14 14:11
@felipesanches : From that first build you quoted above, do you have the part from the "sudo make install" phase that I quoted from your later travis build? The part where the modules moved to their install locations?

**Comment by felipesanches** [comment] 2019-03-14 14:14
I am re-doing that same initial default clean build so that I can capture that log to post here.

**Comment by skef** [comment] 2019-03-14 14:15
Cool!

**Comment by skef** [comment] 2019-03-14 14:22
On that other issue see: https://stackoverflow.com/questions/42582712/relocation-r-x86-64-32s-against-py-notimplementedstruct-can-not-be-used-when . When python isn't built with --enable-shared there's not much FontForge can do -- the whole module is implemented with C-API.

**Comment by felipesanches** [comment] 2019-03-14 14:23
great, thanks!

**Comment by felipesanches** [comment] 2019-03-14 14:29
On Travis and on my personal laptop I'm running python 3.6 but on the my computer (the ssh one running Debian 10 on a laptop plugged to the wall in my living room) I am using python 3.7. All images that I sent in this thread are equivalent, except for this difference in the python versions.

**Comment by felipesanches** [comment] 2019-03-14 14:32
just to be sure here's the same thing now on Debian 10:

![Screenshot at 2019-03-14 11:30:37](https://user-images.githubusercontent.com/213676/54364931-cdce4780-4665-11e9-988c-57ab3cab4192.png)

![Screenshot at 2019-03-14 11:32:10](https://user-images.githubusercontent.com/213676/54365020-f7876e80-4665-11e9-9031-7575456a9b96.png)

**Comment by skef** [comment] 2019-03-14 14:43
We should also verify the `python3.7 -m site` output on the other system.

**Comment by felipesanches** [comment] 2019-03-14 15:03
Ok... there we go...
First of all, before installing, while everything is still clean, this confirms @anthrotype's theory:

![Screenshot at 2019-03-14 11:47:23](https://user-images.githubusercontent.com/213676/54366771-23582380-4669-11e9-9f47-0e0e54102026.png)

----

> We should also verify the python3.7 -m site output on the other system.

Here it is:
![Screenshot at 2019-03-14 11:58:08](https://user-images.githubusercontent.com/213676/54367020-98c3f400-4669-11e9-8eb4-ea1d565760d6.png)

----

Then, let's see the content of the lib dirs before and after installing:

![Screenshot at 2019-03-14 11:22:35](https://user-images.githubusercontent.com/213676/54365193-4cc38000-4666-11e9-8c87-04e07a02a554.png)

...

![Screenshot at 2019-03-14 11:51:45](https://user-images.githubusercontent.com/213676/54366665-f572df00-4668-11e9-9321-96c38ace0268.png)

...

![Screenshot at 2019-03-14 11:52:53](https://user-images.githubusercontent.com/213676/54366622-e1c77880-4668-11e9-8dd6-34585ba7c455.png)

This last picture shows that it is still not finding the installed module. But I think now I also see that the modules are in site-packages while python only looks on dist-packages. Can you help us here, @anthrotype ?

----
From the Debian Python Wiki:

**"dist-packages instead of site-packages. Third party Python software installed from Debian packages goes into dist-packages, not site-packages. This is to reduce conflict between the system Python, and any from-source Python build you might install manually."**

**Comment by skef** [comment] 2019-03-14 15:10
So our job now is to work through this stuff: https://www.gnu.org/software/automake/manual/html_node/Hard_002dCoded-Install-Paths.html#Hard_002dCoded-Install-Paths

**Comment by skef** [comment] 2019-03-14 15:41
Alright, here's the deal. Debian has made this policy decision and updated a number of tools to conform with it: https://www.debian.org/doc/packaging-manuals/python-policy/ap-packaging_tools.html . However, those tools are python-packaging focused and don't directly help here. 
 
There are two high-level models for handling this sort of problem. One is to apply a patch to the configuration stuff before building so that it does the desired thing. Since you're building Debian packaging that would be a fine approach. You would likely be patching aclocal.m4 after `bootstrap` and before `configure`, but I'm not positive about that. 

The other model is to fix things up at the very end of the installation. This seems to be what @frank-trampe did in 2014 in `Packaging/debian/cp-src`. So that may be a useful reference. 

Either way, Debian wants this unusual thing to happen, and autoconf isn't currently designed to handle it automatically (understandable), or with an easy manual override (less understandable). So as the packager the problem falls in your lap.

**Comment by felipesanches** [comment] 2019-03-14 15:49
I only ever considered creating a Debian package because there was a rumor spreading for the past several years that fontforge python bindings are python-2-only.

The deeper / more fundamental issue does not seem to have relation to Debian packaging at all. An install built directly from the the source tree fails. Fixing hypothetical Debian packages will still leave the build rules in the source in bad shape.

**Comment by skef** [comment] 2019-03-14 15:51
Here is Debian Wiki advice on this general problem: https://wiki.debian.org/AutoTools/autoconf .

**Comment by skef** [comment] 2019-03-14 15:56
Fontforge has supported python 3 for some time, in the sense that it could build and install modules for python 3. However, there were many implementation problems in the previous releases when using python 3, so those rumors are understandable. If a person installs with python 3 and a bunch of things don't work, they might describe that to someone else as FontForge being "python 2 only". 

I doubt things function *perfectly* on python 3 now, but the obvious problems are fixed. I use it routinely. It installs just fine on Arch Linux with unremarkable `configure` arguments.

**Comment by skef** [comment] 2019-03-14 15:58
(I can, for example, run `./configure --prefix=/usr --mandir=/usr/share/man` and then do a `make` and `sudo make install`, and it works. I took those two directives from Arch's default packaging for FontForge. When I build I usually add `--enable-debug` and sometimes `--enable-gdk`.

**Comment by felipesanches** [comment] 2019-03-14 16:00
A user (@tobltobs) had a problem with this 4 years ago and got no feedback. I had this very same problem this week. I would then guess that lots of people experienced the problem and got no fix (and no clue) as well.

Sounds like it deserves a mention on the README ;-)

**Comment by skef** [comment] 2019-03-14 16:00
We can, of course, easily verify this: just move the modules the build process makes into the `dist-packages` directory Debian wants them in and then do some tests.

**Comment by felipesanches** [comment] 2019-03-14 16:01
It really deserves a `proper fix`. But while we don't figure that out, it seems at least a mention in the README would be a good thing to do.

**Comment by felipesanches** [comment] 2019-03-14 16:05
> We can, of course, easily verify this: just move the modules the build process makes into the dist-packages directory Debian wants them in and then do some tests.

hmmm... It makes a difference as we expected indeed. But it surfaces another problem:

![Screenshot at 2019-03-14 13:04:20](https://user-images.githubusercontent.com/213676/54372299-f872cd00-4672-11e9-831e-8c684d7191c2.png)

**Comment by skef** [comment] 2019-03-14 16:05
So, a message in the README directed at people who a) install for themselves b) on Debian or derived systems c) against the Debian-packaged python. It might help; not a huge audience, though. Most people will install the Debian-packaged version with their package manager. Most of those who don't do that will seek out some package built by another party. I thought that's what you were up to.

**Comment by skef** [comment] 2019-03-14 16:07
> But it surfaces another problem:

Have you done a `sudo make install` already? On most installs that would put the needed shared library in an appropriate, `ldconfig`ed place.

**Comment by felipesanches** [comment] 2019-03-14 16:08
yes

**Comment by skef** [comment] 2019-03-14 16:12
Well, we have the build trace, right? Where did that put libgunicode.so.4 (if anywhere)?

**Comment by skef** [comment] 2019-03-14 16:16
The output of `ldd /usr/local/lib/python3.7/dist-packages/fontforge.so` might also be illuminating.

**Comment by felipesanches** [comment] 2019-03-14 16:18
> Well, we have the build trace, right? Where did that put libgunicode.so.4 (if anywhere)?

![Screenshot at 2019-03-14 13:18:17](https://user-images.githubusercontent.com/213676/54373252-d4b08680-4674-11e9-988c-eb08054065c3.png)

**Comment by skef** [comment] 2019-03-14 16:23
If that works as intended, then the question is why the library isn't being found normally. Most contemporary Linux systems support `ldconfig`, and I believe ours tries to run `ldconfig` when installing. It's hard more me to say much at this point without more info (except that this should work -- we don't expect users to set LD_LIBRARY_PATH, and I don't have to on my system).

**Comment by anthrotype** [comment] 2019-03-14 16:30
now that's weird that /usr/local/lib is not in the dynamic linker search path on your system..
Try see what this command prints:
```
$ cat /etc/ld.so.conf.d/*.conf
```

**Comment by felipesanches** [comment] 2019-03-14 16:34
![Screenshot at 2019-03-14 13:34:02](https://user-images.githubusercontent.com/213676/54374428-00347080-4677-11e9-9ed9-f4ff240ab0ef.png)

**Comment by skef** [comment] 2019-03-14 16:36
It's probably just not in the `ld.so.cache`. Rebuilding that cache is easy enough. The question is why it wasn't rebuilt by the `sudo make install` process. 

This is the kind of problem you can fix by hand, convince yourself it's fixed generally, and then the install doesn't work on a fresh system ...

**Comment by felipesanches** [comment] 2019-03-14 16:43
yes, indeed!

![Screenshot at 2019-03-14 13:42:57](https://user-images.githubusercontent.com/213676/54375092-4b9b4e80-4678-11e9-803d-899534b4d663.png)

**Comment by anthrotype** [comment] 2019-03-14 16:44
i'd be curious to know what's the default value on a vanilla debian distribution

**Comment by skef** [comment] 2019-03-14 16:46
Alright, so I don't know why "sudo make install" didn't fix this -- it normally runs `ldconfig` itself. But you can always run it again in your packaging. So it sounds like your problem is more or less resolved other than potential documentation in README and  -- the hard part -- following through on the packaging. 

If only we knew if your problem was the original filer's problem, we could close this issue. *\*sigh\**.

**Comment by felipesanches** [comment] 2019-03-14 16:53
I would truly expect the closing of this issue to be coupled with a commit on master :-)

**Comment by skef** [comment] 2019-03-14 16:54
In the `Packaging/debian` directory, the `README`, or what?

**Comment by felipesanches** [comment] 2019-03-14 16:55
I don't know.

**Comment by felipesanches** [comment] 2019-03-14 16:58
"If you did not fix it, it's still broken." :-D

**Comment by skef** [comment] 2019-03-14 17:00
I'm not a "Debian person", so I don't know what relationship the `Packaging/Debian` stuff has to Debian's (the organization) actual building and packaging process. It's fairly recent, though.

How about this: why don't you make a pull request that adds a note under "Common Problems" in `INSTALL-git.md` about having to move the modules on Debian after installation. Then make @frank-trampe the reviewer. He wrote the last Debian stuff he can weigh in on whether and how the messaging should work.

**Comment by felipesanches** [comment] 2019-03-14 17:04
sounds fair :-)

I'll do so!

**Comment by felipesanches** [comment] 2019-03-14 17:06
(tomorrow. I have to get some rest now)

**Comment by skef** [comment] 2019-03-16 04:34
I believe both aspects of this issue are sufficiently addressed. See #3533 for the documentation update.

**Closed by skef** 2019-03-16 04:34 UTC

**Comment by felipesanches** [comment] 2019-03-16 07:46
Thanks!
