### ISSUE TITLE
Windows 10/Python3.10:no module named fontforge

### ISSUE THREAD

**Issue by noisnemid** [fontforge/fontforge#5114] opened 2022-10-05 07:27 UTC
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [x] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [x] \(optional) Possible solution/fix/workaround

---

FontForge Version 20220308,Windows 10, Python 3.10.2

```
    import fontforge
ModuleNotFoundError: No module named 'fontforge'
```

I suggest that a package could be published to pip(pypi.org) to adapt various python versions.

**Comment by skef** [comment] 2022-10-07 03:37
Duplicate of #4377

**Closed by skef** 2022-10-07 03:37 UTC
