### ISSUE TITLE
Sometimes outlines in the Fore layer will "fall" into Back layer after the SFD is parsed though the SFD says that it is in the fore layer.

### ISSUE THREAD

**Issue by be5invis** [fontforge/fontforge#2218] opened 2015-04-24 10:03 UTC
FF version: March 30 release for windows.

![image](https://cloud.githubusercontent.com/assets/240091/7316617/0d9fefd2-eaab-11e4-8584-b88f3f07666e.png)
This image shows that the glyph `uni1DC8`'s outline has disappeared. FF tells me that this glyph's outline is in the Back layer:
![image](https://cloud.githubusercontent.com/assets/240091/7316643/4123531c-eaab-11e4-917e-d7c3f8ff2d52.png)
However the [SFD file](https://gist.github.com/be5invis/b1d764250a7b75fa32c6) ([mirror](http://pan.baidu.com/s/1dD4IQiP)) tells me that it IS in the foreground layer:
```
StartChar: uni1DC8
Encoding: 7624 7624 1018
Width: 0
GlyphClass: 4
Flags: W
AnchorPoint: "Anchor-5" -251 458 mark 0
AnchorPoint: "Anchor-0" -251 674 basemark 0
AnchorPoint: "Anchor-0" -251 458 mark 0
LayerCount: 2
Back
Fore
SplineSet
-463 665 m 0,0,1
 -463 676 -463 676 -454 685 c 128,-1,2
 -445 694 -445 694 -434 694 c 128,-1,3
 -423 694 -423 694 -414 686 c 128,-1,4
 -405 678 -405 678 -364 635 c 2,5,-1
 -313 580 l 1,6,7
 -215 683 -215 683 -204 690 c 0,8,9
 -198 694 -198 694 -190 694 c 0,10,11
 -178 694 -178 694 -158 674 c 0,12,13
 -134 649 -134 649 -100 613 c 0,14,15
 -59 570 -59 570 -49 558 c 128,-1,16
 -39 546 -39 546 -39 537 c 0,17,18
 -39 526 -39 526 -48 517 c 128,-1,19
 -57 508 -57 508 -68 508 c 128,-1,20
 -79 508 -79 508 -93.5 522 c 128,-1,21
 -108 536 -108 536 -189 622 c 1,22,-1
 -190 622 l 1,23,24
 -205 606 -205 606 -229 581 c 0,25,26
 -279 529 -279 529 -290.5 518.5 c 128,-1,27
 -302 508 -302 508 -312 508 c 0,28,29
 -324 508 -324 508 -343 527 c 0,30,31
 -358 543 -358 543 -374 559.5 c 128,-1,32
 -390 576 -390 576 -400 586.5 c 128,-1,33
 -410 597 -410 597 -420 607.5 c 128,-1,34
 -430 618 -430 618 -435.5 624 c 128,-1,35
 -441 630 -441 630 -446.5 636.5 c 128,-1,36
 -452 643 -452 643 -454.5 646 c 128,-1,37
 -457 649 -457 649 -459.5 653 c 128,-1,38
 -462 657 -462 657 -462.5 659.5 c 128,-1,39
 -463 662 -463 662 -463 665 c 0,0,1
EndSplineSet
EndChar
```

**Comment by adrientetar** [comment] 2015-04-24 18:02
Duplicate of #2103. 
Duplicate of #1918.

**Closed by adrientetar** 2015-04-24 18:02 UTC
Labels: duplicate
