### ISSUE TITLE
Mass cleanup, build system reforms, fixing those compiler warnings

### ISSUE THREAD

**Issue by jtanx** [fontforge/fontforge#3512] opened 2019-03-09 09:09 UTC
After the current release is done, I'll be looking at doing some things about how FontForge is currently built. There's a lot of cruft in the way of actually making improvements, and detecting potential issues early enough.

- Compiling with `-Wall` is a disaster; there's so many compiler warnings that it's hard to spot real issues
- Compilation itself is slow, or at least slower than it needs to be.
   - On Windows, build times are atrocious; running `./bootstrap` takes a good 10-15 minutes on my system, running configure another 10 minutes or so, and building it another 45 minutes or so. 
     - Linking in particular is very slow, although I'd put that down to libtool/mingw

Those two points in particular impedes on debugging issues, because it takes so long just to iterate on builds; worse still if those changes affect the build system in any way.

So because of that, at the top of my list is to:

- Delete a bunch of old stuff out of the repo, namely:
  - breakpad and the collab feature; both are seriously unmaintained, and never really worked all that well; as far as I know, breakpad in particular was only ever built to work on mac, and I have doubts that it's doing anything useful now.
  - The gtkui folder, no one ever uses it (besides, it'll still be in git history, that's what it's for)
- The nodejs (related to collab) and win folders. The win folder contains nothing useful (except maybe the icons, which can be moved out).
- Remove gnulib. Using gnulib is a mistake, for the things we use it for, we can just use glib, or write our own - more importantly, this means we can move off autotools.
- Switch to a different build system, either cmake or meson. It actually wasn't too bad to get something in cmake off the ground (see https://github.com/fontforge/fontforge/tree/cmake), but that's mostly because I'm already familiar with cmake.
- Get rid of the plugin system, no one uses it, and if I recall correctly, the only plugin that exists is gb12345, which again, is also broken. This means that we can not depend on libltdl, which is fairly unix specific.

Full wishlist here: https://github.com/jtanx/fontforge/wiki/Wishlist

**Comment by skef** [comment] 2019-03-09 09:18
After my exposure to the code base the past couple months I agree with just about all of this. 

An alternate possibility with collab is to cut it off at the roots rather than remove it entirely. If it were ever to be revived almost all of the existing code -- especially the zeromq stuff -- would belong in python, but the code close to the UI changes might be worth leaving in.

**Comment by ctrlcctrlv** [comment] 2019-03-09 09:31
Yes, please remove all the node.js stuff, I don't think it has a single user. It was a cute idea but never should have been in the core release, it should be an extension, and making it one isn't our responsibility.

**Comment by mskala** [comment] 2019-03-09 15:37
My current life situation doesn't really give me the chance to spend time contributing to projects like FontForge, but I saw this issue scroll by and thought I'd at least make a few brief comments.

Streamlining the FontForge codebase and removing unnecessary cruft is definitely a good idea.

Most purported replacements for Autotools are worse than it, from the user's point of view.  One of the last things I want to be told when I unpack a distribution of a piece of free software is that now I have to go find and install some weird build tool instead of typing "./configure".  If you removed the cruft that makes Autotools hard to work with and should be removed anyway for other reasons, then Autotools would not be a bad way to build the leaner non-crufty FontForge.  If you must use a non-Autotools build system, cmake is preferable to meson because it is more standard, and being more standard is really important.  Basic principle of usability:  users use other packages, not yours, most of the time.  So if your package does something much different from what other packages do, then that will require adaptation from users and is _in itself_ a usability problem even if you think the different thing you're doing is better than the consensus.

As I proposed years ago (issue  #1253), FontForge could be improved greatly by putting an end to its extensive use of shared libraries to divide up the code.  Having shared libraries makes the build system much more complicated (whether in Autotools or anything else), harms cross-platform compatibility, and more or less necessitates the use of "libtool," which is a disaster in itself.  The benefits of putting bits of FontForge into shared libraries are mostly of use for features either that were never used (e.g. FontForge itself embedded in other applications) or used only by features that can and should be eliminated (e.g. "collab").

You should seriously consider removing printer support (issue #2171).  It is disproportionately expensive, requires a whole bunch of extra platform-specific dependencies, doesn't work well, and it's not really a very important feature.

If you're willing to remove cruft, you should also consider running the whole code base through an indenter to standardize it.  The peculiar indentation preferences of the original author have been preserved 17 or 18 years because people were concerned about breaking "git blame"; but doing that, and requiring the same style to be applied to new code, has a high ongoing cost that will continue having to be paid forever or until the project makes up its mind whether developer time today, or "git blame," is to be master.

FontForge should consider removing "native scripting" (if you haven't already?  I haven't been keeping up).  I use it myself, to the exclusion of Python, but I saw the way the wind was blowing and forked the project, because FontForge's team didn't look like reliably supporting "native" into the future - and I removed Python and the entire GUI from my fork.  It just doesn't make sense to continue maintaining two scripting languages.

**Comment by skef** [comment] 2019-03-09 15:57
> Most purported replacements for Autotools are worse than it, from the user's point of view. One of the last things I want to be told when I unpack a distribution of a piece of free software is that now I have to go find and install some weird build tool instead of typing "./configure". If you removed the cruft that makes Autotools hard to work with and should be removed anyway for other reasons, then Autotools would not be a bad way to build the leaner non-crufty FontForge. If you must use a non-Autotools build system, cmake is preferable to meson because it is more standard, and being more standard is really important. Basic principle of usability: users use other packages, not yours, most of the time. So if your package does something much different from what other packages do, then that will require adaptation from users and is in itself a usability problem even if you think the different thing you're doing is better than the consensus.

This was discussed elsewhere recently. The issue is less about kruft or taste than wanting to be able to use other compiler tool chains. Python's standard Windows distribution is compiled with Visual Studio. Autotools makes it at least difficult and likely impossible to build with very different compilers.

**Comment by frank-trampe** [comment] 2019-03-09 16:20
We can't pull the rug out from under the collab users, and I need to check on the plugin interface. Everything else is fine, and removing gnulib would be a great help.

**Comment by skef** [comment] 2019-03-09 16:27
> We can't pull the rug out from under the collab users 

The collab code makes use of outdated GTK calls and the basically obsolete `pygtk`. To not pull the rug out someone will have to revive it to work with the current code base or somehow work around the custom UI elements (which are also currently hooked up in a gxdraw-only way).

**Comment by frank-trampe** [comment] 2019-03-09 16:44
Let's just stop building it by default and say that we're open to patches to update it. Nobody can ask any more than that.

**Comment by jtanx** [comment] 2019-03-09 20:57
For collab - how about this:
- Stop building/enabling by default, mark/announce as deprecated, will be removed unless someone steps in to maintain it
- Barring any complaints (and from more than one person) or someone maintaining it, a few releases later, remove it

I would be surprised if anyone was still using collab, given how buggy it is. I'm not in favour of keeping old code around for the sake of someone *possibly* using it, especially if we know it isn't used, and if it gets in the way of making future improvements.

Regarding autotools, I agree that being able to just run `./configure` is nice, but not a good enough reason for me to not consider switching to cmake/meson, for all the drawbacks that autotools has. Many projects use cmake, so I don't buy the argument that it's an obscure tool.

I can somewhat agree with that on meson, although all the gnome products are migration to using it. The reason I would be considering it, is that it's a little closer to how autotools works in terms of the arguments you pass in, whereas cmake is quite different. I think the self-discovery on meson is also better than cmake (in terms of the help provided, like `./configure --help`, just from what I recall with trying to build the latest pango release).

**Comment by khaledhosny** [comment] 2019-03-09 22:16
FWIW, as far as autotools replacements goes, I find meson more pleasant to work with than cmake and more “unixy” (if that means anything).

**Comment by MaddTheSane** [comment] 2019-03-09 22:51
As far as indentation, `clang-format` is fairly decent for indenting C, Objective-C, and C++ code.

**Comment by frank-trampe** [comment] 2019-03-16 09:41
We can't reindent. The impact on git blame usability is significant, and the main comprehensibility issue with FontForge is not the formatting anyway.

**Comment by frank-trampe** [comment] 2019-03-16 09:41
I'm fine removing collab and the plug-in interface if it turns out nobody is using them. After the release, I'll put out a dedicated notice on the mailing list, and we'll see if anybody responds.

**Comment by bagong** [comment] 2019-03-16 12:48
> FWIW, as far as autotools replacements goes, I find meson more pleasant to work with than cmake and more “unixy” (if that means anything).

Maybe, but Cmake has been taken into a massive embrace by Microsoft since a few years, it is natively supported by Visual Studio now, and it is the language of VCPKG, the library repo designed to play the role Homebrew is playing in the Mac-world. Cmake ist natively supported by QtCreator, and Qt as a whole is enhancing Cmake support continuously. Cmake also has robust MSYS2 support. Although I haven't found good data on this I am pretty sure Cmake adoption rate must be many times higher than Meson's. I can see how the core strengths of Cmake are not that important for FF, but the adoption rate should be considered a big plus...

**Comment by khaledhosny** [comment] 2019-03-16 20:01
That is all nice, but I don’t think any of these benefits have much bearing to the development of FontForge. But that is just my 2 qirshs, but in my experience trying to replace autotools with cmake (e.g. in HarfBuzz) ends with a pile of hacks that is even uglier than autotools, which was not the case with meson.

**Comment by jtanx** [comment] 2019-03-21 08:40
Just been playing around with this, a no-gui, no-python, no gnulib, statically linked (for what stuff FF compiles, not external dependencies) build using cmake/ninja (again, haven't yet explored meson) takes 45 seconds, both on Windows and Linux,  vs. 10 minutes on Linux / 45+ minutes on Windows (forking is expensive yo)

Granted, I'm making quite a few assumptions on dependencies and build options, but still, that's a huge improvement over what the current build time is.

**Comment by jtanx** [comment] 2019-03-21 10:47
Also signaling that I'm looking at #3181 to remove HTTP/FTP support from FontForge (that was broken/insecure anyway)

> We can't reindent. The impact on git blame usability is significant, and the main comprehensibility issue with FontForge is not the formatting anyway.

I disagree with this, there have been many times when I would have understood the code far quicker had it been more sanely formatted. Losing immediate git blame is unfortunate, but I think we can deal with that.

**Comment by skef** [comment] 2019-03-21 18:09
I've looked into the `blame` situation a bit; it's not unsolvable, although there would be some compromises. I think it would be best (or at least more revealing) to work out what the style *would* be. I suspect the "we can't do this" is hiding a lot of "we'll never agree on this". 

(I should say "you", really. I've gotten pretty good at not caring about this stuff, as long as the style is specific and consistent enough for a formatting tool to automate.)

**Comment by skef** [comment] 2019-03-31 05:28
Two updates, one inspiried by @jtanx's recent email message:

1. I'll look into the blame thing. I'm thinking of enhancing [git hyper-blame](https://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/git-hyper-blame.html) so that it can work with an optional "database" of line number mappings for a given ignored commit. 
2. I do still favor splitting the collab baby. I want to add low-level python functions and hooks for pushing character state state up and down. That way collab could be rebuilt later as an external facility, and (who knows?) those functions might be put to other uses, such as a live help facility.

**Comment by jtanx** [comment] 2019-03-31 05:38
To put it bluntly, the biggest problem I have with collab, is that it's poorly written. It's also stuck on some old version of czmq/zeromq, which makes it a pain to work with.

Given that, I'm also quite sceptical of just how secure it is, *particularly* because it specifically deals with interacting with events across the network (the same situation as all that FTP/HTTP handling code, which I'd also like to rip out).

If you're willing to maintain it, then I'm ok with that too, but I'd like to see it much more modularised than how it currently works (there's a bunch of code that even though FF is compiled without collab support, still runs, even though there should be no need for it to).

In other news, I've actually had quite a lot of success moving over to having GDraw sit on top of GTK instead of GDK (https://github.com/jtanx/fontforge/tree/gtk-works). Still very much a WIP though.

But what's made life so much better is that I'm already using cmake, which means that I can actually develop on windows and iterate changes in seconds, instead of minutes...

**Comment by skef** [comment] 2019-03-31 05:41
All that stuff would go. Only code directly involved in packing and unpacking character state would remain.

**Comment by frank-trampe** [comment] 2019-04-01 16:20
@jtanx, now that you've looked at this in depth, and now that it seems that nobody is using the collab feature, what are your thoughts on the utility of leaving the collab code but deprecating and disabling it? Does it look like somebody with the time could come back a year later and repair it to an acceptable level, or would it quickly drift so far without mindful maintenance that it would be easier to start over? What about just removing the hooks and documenting where they were in the main collab file?

**Comment by jtanx** [comment] 2019-04-02 08:52
collab code is spread out over quite a few files, and there's a couple of places where some stuff runs regardless of being enabled or not. To be honest, I'd suspect that it'd make little difference effort wise, if someone were to try to resurrect it, between us cleanly removing it in a single commit, vs. trying to just leave it to the side.

**Comment by jtanx** [comment] 2019-07-08 08:31
I've been looking at this intermittently, but I'll lay out what my plans are for the build system:

* Use CMake with a minimum version of 3.1 (or maybe 3.4). This is supported on all *current* versions of Debian/Ubuntu/RHEL. I was looking at meson, but it's too immature imo, you basically need to be using the latest version which no distro ships by default yet.
* The aim is to completely remove the autotools build system. My stance on older distros which don't have CMake >= 3.1: Either use one of the older dist tarballs, or find a way to get a newer CMake installed. I seriously don't want to be in a position where we are supporting two build systems.
* On how the build layout will be - my preference is for a fully static (within FontForge's own code) build, so no more libgdraw, libgutils, libfontforge, libfontforgeexe etc. I'd also prefer to not install any headers, since clearly we do not have a stable API. The only consumer I'm aware of that uses FontForge in this manner is pdf2htmlex, which is already using a custom version of FontForge. It looks like it's also been abandoned. Barring that, my next best choice would be to have just one dll, libfontforge, which contains what was previously libgutils libgunicode and libfontforge. The gui then contains libgdraw and links to libfontforge, while the python hooks link to libfontforge (similar to now).

**Comment by ctrlcctrlv** [comment] 2019-07-08 08:41
Just after I get used to the autotools build system (#3665 #3754), we're going to change it. :rabbit: :hole:

I'd really prefer we didn't without good reason to do so. You can't just make the build static by changing the autotools configuration? I have no experience at all with cmake. What do you think @JoesCat ?

**Comment by jtanx** [comment] 2019-07-08 08:46
The build system changes have been on the plate for a while now, see the start of this issue.

I've already laid out why I think we should switch, I'm currently wasting literally hours on a build that should take minutes

**Comment by ctrlcctrlv** [comment] 2019-07-08 09:12
It seems to me like we mostly talked about removing features and not the switchover. I'm not totally against this, but I do think that the feedback of old time members like @JoesCat could be helpful since he maintains a lot of FontForge's sub-packages and they all use autotools...I don't know the extent to which this will affect him.

**Comment by jtanx** [comment] 2019-07-08 09:26
I mentioned switching the build system multiple times, I even had a [couple](https://github.com/jtanx/fontforge/tree/cmake-trial) of [test](https://github.com/jtanx/fontforge/tree/meson-place) branches trying out cmake and meson. I even mentioned the results:

> [a non-gui] build using cmake/ninja (again, haven't yet explored meson) takes 45 seconds
>  A build with the gui/gdk takes 1.5 minutes on Windows

I'm not sure how much clearer I can make this. I don't really care about switching libspiro/libuninameslist, since they take a trivial amount of time to compile on any build system. 

I'm open to feedback on this, but I'll make my stance clear, just because not all systems (particularly older systems) may have out of the box support for CMake >= 3.1 is not a good enough reason for me to not switch to it. You can't please everyone, but I think I'm already setting the bar pretty low by targeting a version of CMake that is quite widely supported, while still retaining the 'modern' aspects of the later versions of CMake.

**Comment by ctrlcctrlv** [comment] 2019-07-08 10:04
Guess I'll be learning CMake then :nerd_face:

**Comment by frank-trampe** [comment] 2019-07-08 16:00
I'm fine with Cmake 3.1. The earliest piece of hardware on which I need to build FontForge (for the Launchpad builds) has Cmake 3.5.1. The dist tarball ought to keep other people happy. Eliminating autotools is a worthy goal, and the sacrifices to get there seem proportionate to me.

I don't entirely understand the upside of reworking the linking layout. I do think that it is important to continue to supply libfontforge in some form, and I like the organization of the code (which I assume would be invariant under this proposal anyway).

**Comment by jtanx** [comment] 2019-07-08 21:42
Regarding the linking change, I guess my motivation is that there is no real need for dynamic libraries - who else uses gdraw or gutils or gunicode except FontForge? Static linking just makes things easier to work with, such as debugging local builds. Plus we don't have to worry about soversions.

**Comment by skef** [comment] 2019-07-09 00:11
My two cents is that I don't much care about static versus dynamic at this point, mostly because it doesn't seem like a decision that's very difficult to reverse when there's a case for that. (I don't "get" the occasional comments portraying dynamic libraries as an exotic and fragile technology. They're pretty old hat at this point.) 

On the other hand I would be concerned about dumping everything into a single bin, whether static or dynamic. I hope some kind of intermediate linking is retained to enforce what object files can depend on other object files.

**Comment by ctrlcctrlv** [comment] 2019-07-09 01:02
It can sometimes be helpful when debugging gdraw to link to libgdraw... I've done so when working on UI code.

**Comment by skef** [comment] 2019-07-09 02:22
I don't see any obvious standard-enforcing flags in the current Makefiles. Can I assume C99 is OK? Can I switch a struct instantiation to a designated initializer for example?

**Comment by ctrlcctrlv** [comment] 2019-07-09 02:45
Can I use L"" to create unichar_t's?

**Comment by skef** [comment] 2019-07-09 02:58
For reference I believe that `L` is a C11 thing.

**Comment by ctrlcctrlv** [comment] 2019-07-09 04:13
So can I assume C11 is okay? It's almost ten years old!

**Comment by MaddTheSane** [comment] 2019-07-09 04:14
Microsoft's compiler has very limited support for C99, never mind C11.

At least, that was my last experience, which _was_ awhile ago.

**Comment by ctrlcctrlv** [comment] 2019-07-09 04:24
@MaddTheSane Microsoft has been trying to embrace open source and standards lately, so I think we need some confirmation that's still true in modern versions of VS. In any event I think we use GCC on Windows so it might not affect us.

**Comment by jtanx** [comment] 2019-07-09 08:51
> I don't see any obvious standard-enforcing flags in the current Makefiles. Can I assume C99 is OK?  

The current build system targets gnu99, with C++ code targeting (or should be targeting) C++11. https://github.com/fontforge/fontforge/blob/master/configure.ac#L106

I'd actually by trying to see if we can target pure c99 instead.

> Can I use L"" to create unichar_t's?
> For reference I believe that L is a C11 thing.

That's incorrect, L is used for wchar_t literals. For linux this will probably work, on Windows it won't, because the size of a wchar_t is 2 on Windows vs I believe 4 on linux. If you want to write a unichar_t literal, it's usually something like `{'A', 'B', 'C', '\0'}`

> Microsoft's compiler has very limited support for C99, never mind C11.

As of VS2017/2019, this isn't really true any more, support is much better than it was before.

**Comment by khaledhosny** [comment] 2019-07-23 10:51
Re-libraries, I suggest having one `libfontforge` that has all the non-GUI code and that can be used by FontForge GUI and the Python module (for Linux distributions mainly where statically linking the same code in both might be undesired). Everything else should be statically linked into `fontforge` binary and any uses of these libraries outside FontForge should be explicitly declared unsupported.

**Comment by jtanx** [comment] 2019-07-23 10:58
That's the approach I more or less took, https://github.com/jtanx/fontforge/tree/cmake3 is the branch I'm working on. It's more or less feature complete in terms of how it builds FontForge, but I'm still in the process of hooking up the tests and the installation/packaging part of it.

Oh, I'm also targeting a minimum version of 3.5 now, since it looks like nothing really distributes 3.1-3.4 anyway

**Comment by ctrlcctrlv** [comment] 2019-08-12 08:31
Hey guys, this is in re: collab, which was removed. I'm not sure where to put this, it seems improper to open a new issue just for this.

I found a struct element that seems to have been left behind when we removed collab:

https://github.com/fontforge/fontforge/blame/e4cea768bb55fe7138209e5516a26fdeed1b6b62/fontforge/views.h#L478

That's `views.h`, `FontView` struct, member `pid_webfontserver` (type `GPid`).

FYI.

**Comment by skef** [comment] 2020-01-28 10:13
@jtanx did we wind up doing all of this?

**Comment by jtanx** [comment] 2020-01-28 10:16
Mostly done, but I guess not fixing the compiler warnings.

**Comment by skef** [comment] 2020-01-28 10:24
The -Wall problems are, in effect, self-documenting. I think we can -- primarily you -- can declare victory. Closing.

**Closed by skef** 2020-01-28 10:24 UTC
Labels: maybe-done
