### ISSUE TITLE
FontForge Hangs when Importing SVG from Processing

### ISSUE THREAD

**Issue by aswinmohanme** [fontforge/fontforge#3070] opened 2017-05-21 10:07 UTC
I have recently created SVG glyphs of all letters in processing. You can find the SVG files here https://github.com/aswinmohanme/Plexta-FreeFont.

I want to convert it to ttf, but when I try to import it FontForge hangs.
How can I fix this. 

### FontForge Version
Latest Font Forge , on Fedora 25.

### Steps to Reproduce
1. Create a New Font 
2. Select a Letter
3. Import any SVG from the given Repo

**Comment by jrbastien** [comment] 2017-05-24 14:29
Very nice font that you have created.

However you are asking a lot to FontForge.  I have tested 1.svg in Inkscape and see that we have a group of 3777 objects that needs to be converted to path.  Inkscape can handle it relatively well.  This will create 7552 nodes.  But those nodes are not really a shape because they are formed by multiple separate lines with an outline of 2 pixels .  So if you try to make a shape out of it by combining these segments and then converting the outline to a path, Inkscape will choke forever.  I estimate that each segments of 2 nodes will be converted to 6 nodes.  This would create a shape of 22656 nodes.

Fontforge needs to go through the same process.  Perhaps you are better off importing a PNG and then trying the autotrace function.  I did not try.

**Comment by aswinmohanme** [comment] 2017-05-24 16:33
I used deep ungroup to ungroup everything, and then `combine` to convert everything into a single path, and then use `object to path` , and `stroke to path`.
[Converted SVG](http://svgur.com/s/1iF)

Then I created a Typography canvas using inkscape built in tools, and then exported the svg Font.
[SVG Font](http://svgur.com/s/1hv)

I was able to create an SVG Font that would open in Font Forge Glyph view, but font forge would hang when I try to open the individual letters.

**Comment by jrbastien** [comment] 2017-05-24 18:35
Strangely I can't see your converted SVG glyph in Inkscape.  It opens but don't show anything.  In a browser, I can see it fine.

As for the SVG font, I observe the same thing as you.  But I still believe it has too many nodes to be usable because FF is not hang but is using all the CPU to render the glyph.  I couldn't find anything on Google talking about the maximum number of nodes supported by FF but for other programs like Glyphs on the Mac, they say that over 1000 the count is too high and that sub-routinization, hintings and other options must be turned off to support so many nodes.

To prove my point, just draw something that has a reasonable number of nodes (<200).  And see if it works.

And I'm sure such fonts can be drawn.  I'm sorry I just don't know the technique or the application that supports it.

**Comment by aswinmohanme** [comment] 2017-05-25 14:10
So do you have some suggestions on how to package these SVG files as a font ?

Maybe create an SVG Font only ?

Thanks

**Comment by frank-trampe** [comment] 2017-06-03 04:33
In the interest of streamlining testing, it would be nice to have a bit more information. What platform and version are you using? Would you provide a specific input glyph that fails?

**Comment by jrbastien** [comment] 2017-06-03 12:11
@frank-trampe , the glyphs were provided in original issue message and simplified glyphs in 3rd message.  They all fail both on Windows 7 (with the 2016-10-04 release) and on Ubuntu 16.04 with latest FF version compiled from source.

I thought originaly it has to do with the number of nodes but even with a small subset of the glyphs it hangs too.  I no longer have this small sample but if you try with this [simplified one](http://svgur.com/s/1iF) you will see the problem.

**Comment by jtanx** [comment] 2017-06-03 12:26
Each svg is ~700-800KB? Yeah even with that simplified version that is just *way* too complex to be used in a font (or at least to be edited by FontForge). To give you a comparison, just look at http://www.dafont.com/dink.font.

That font is arguably simpler than the sample svgs mentioned here, yet is still visibly slow to render both in the MS font viewer, and also when you try to edit it under FF.

The 'problem' is that FF's editor is not as optimised as say Inkscape for handling such complex cases, so it appears to hang when trying to import/render the file. Even if you got those glyphs bundled into a font, I wouldn't be surprised if rendering performance is bad.

**Comment by frank-trampe** [comment] 2017-07-01 20:16
@jrbastien, I tried importing the file that you linked into FontForge (current master) on Linux, and it worked fine.

**Comment by jrbastien** [comment] 2017-07-02 15:37
@frank-trampe , I just did a fresh build from today's master and no change.  CPU is still at 100% and no import after 15 minutes.

I'm wondering if my PC is too old.  CPU specs:

$ cat /proc/cpuinfo
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 16
model		: 4
model name	: AMD Phenom(tm) II X4 925 Processor
stepping	: 3
microcode	: 0x10000c8
cpu MHz		: 800.000
cache size	: 512 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes

Is there anything you do before importing or just new font, double-click on "C" and import SVG?

Would you be interested to look at a back trace?  I don't know how to do this but if you give me some hints I should be able to manage.

**Comment by frank-trampe** [comment] 2017-07-02 20:31
@jrbastien, that's really odd. Are you running amd64 Linux and compiling to that architecture? To get a backtrace, make a copy of your fontforge launch script (fontforgeexe/fontforge), change `exec "$progdir/$program" ${1+"$@"}` to `gdb "$progdir/$program"` in that script, and run the script. In gdb, use the `run` command to start. When FontForge hangs, press Control + C in gdb and use the `where` command to see where it's stuck.

Also run top in a separate terminal. You do not have a lot of memory, and it could be that it gets wedged because it needs to use swap space on the hard drive. See what memory usage and swap usage are when FontForge hangs.

**Comment by jrbastien** [comment] 2017-07-06 01:10
@frank-trampe ,

> Are you running amd64 Linux and compiling to that architecture?

Yes I am.  Is there anything special to compile to that architecture?  I simply followed the instructions here: https://github.com/fontforge/fontforge/blob/master/INSTALL-git.md

> You do not have a lot of memory

I have 8 GB of ram.  Fontforge uses only uses 56.6 MB.  Total memory consumption is 1.9 GB

[Backtrace for issue 3070.txt](https://github.com/fontforge/fontforge/files/1126454/Backtrace.for.issue.3070.txt)

**Comment by frank-trampe** [comment] 2017-07-06 01:19
@jrbastien, I misread your KiBs of cache as MiBs of memory. There's nothing special about Linux on amd64. I was only asking because that's what I'm running, and I'm not able to reproduce the problem. I guess we'll need a stack trace.

**Comment by jrbastien** [comment] 2017-07-06 11:06
By stack trace, do you mean something different than the backtrace I have attached before?

**Comment by frank-trampe** [comment] 2017-07-06 19:58
Hehe. I need to read things more carefully!

**Comment by jrbastien** [comment] 2017-07-06 20:13
@frank-trampe , please pay attention to the name of the svg file in the backtrace.  Perhaps, we are not using the same sample?

**Comment by frank-trampe** [comment] 2017-07-06 20:26
@jrbastien, I'll look at that tonight.

**Comment by frank-trampe** [comment] 2017-07-06 20:40
@jrbastien, that is the file that I used. I'll poke around the code where it's hanging and see what might be happening. Here's another thing that might narrow the field a bit more. Break where it hangs and get a stack trace, as before, but keep using the `finish` command until it rehangs, and tell me how many times you ran `finish` before that happened. That will tell us which frame isn't exiting.

**Comment by jrbastien** [comment] 2017-07-07 01:52
@frank-trampe see new attached backtrace: 
[Backtrace #2 for issue 3070.txt](https://github.com/fontforge/fontforge/files/1129756/Backtrace.2.for.issue.3070.txt)

It rehung after 11 "finish".

**Comment by frank-trampe** [comment] 2017-07-07 02:15
Well it looks like an unterminated (possibly loopy) splineset. Let me think about the best way to isolate it.

**Comment by jtanx** [comment] 2019-04-13 12:31
This should be improved quite a lot by #3618. With the samples provided, it still slows down quite a fair amount though, so I'd recommend just turning off the outlining feature (File->preferences->Interface->OutlineThickess - set to 0)

**Comment by skef** [comment] 2019-12-14 09:49
I imported a "P" and it worked OK. Given that the relevant part of the SVG import relies on the stroke code I'm going to close this. Someone can reopen if the problems persist and there is interest.

**Closed by skef** 2019-12-14 09:49 UTC
