### ISSUE TITLE
Substitutions don't work in exported font

### ISSUE THREAD

**Issue by ekaunt** [fontforge/fontforge#4545] opened 2020-12-21 18:45 UTC
I added a couple of substitutions to a Japanese font, which would turn このページは編集できます → 此の頁は編輯出來ます. The substitutions work just as expected in the metrics window within FontForge, but when I export the font (whether otf or ttf) the substitutions don't work anymore… (only 編集→編輯 still works)

[the sfd](https://mega.nz/file/f8JDgYaA#uJhASZ2_PtEi49KyNEmMDEDb-N-Pl-qNy2iU3sUCyyg)
[the otf](https://mega.nz/file/TtJ3SQIa#Mz9jXzH-Uv0Nftr07hWAHcbOzkR5G2HMwl8PxyAcSpc)

### When reporting a bug/issue:
- [X] Screenshot
- What I expect:
![image](https://user-images.githubusercontent.com/62402760/102810855-74df2780-4392-11eb-8068-29b363692ff8.png)
- What I get:
![image](https://user-images.githubusercontent.com/62402760/102810877-7c9ecc00-4392-11eb-99f9-e1715fb33ce4.png)

- [X] The FontForge version and the operating system you're using
```
Version: 20200314
 Based on sources from 2020-08-30 10:04 UTC-ML-D-GDK3.
fontforge 20200314
build date: 2020-08-30 10:04 UTC
```
```
OS: Manjaro Linux x86_64
Kernel: 5.9.11-3-MANJARO
WM: bspwm
```

**Comment by KamilLanda** [comment] 2020-12-21 21:04
I changed Contextual chaining subtitutions to the 'By Classes' type, because I don't know exactly how to use the 'Glyph' type. 
I tested it in the LibreOffice and the substitutions 1-4 look OK. 

![test-japanic](https://user-images.githubusercontent.com/61148366/102821874-310f1100-43d8-11eb-885d-84f4dd22656d.png)

I also deleted "redundances" from the SUBs, for example there was: 306E -> 306E in the SUB1. Why to substitute the character to the same character? I think it hasn't a sense. 

And I also deleted some data from the 'Element/ Font Info/ TTF names' because FontForge showed warning about 1 language in these data. 
[edited-marugo.zip](https://github.com/fontforge/fontforge/files/5726524/edited-marugo.zip)

**Comment by ekaunt** [comment] 2020-12-21 21:42
![image](https://user-images.githubusercontent.com/62402760/102824731-68b39400-43ab-11eb-82b4-ca090b7f14a4.png)

Doesn't work for me after I installed your font… 

It does work if I add the same feature file to a different font, but not to this font. Any ideas why?

**Comment by KamilLanda** [comment] 2020-12-21 22:01
Unfortunately no idea why :-(

**Comment by KamilLanda** [comment] 2020-12-21 23:47
I changed the Contextual Chaining Substitutions to the Contextual Substitutions and it looks OK again. If you export some lookup and then load it from the .fea file, then I think the Cont. Chaining Subst. will change to the Cont. Subst.
[edited2-marugo.zip](https://github.com/fontforge/fontforge/files/5727025/edited2-marugo.zip)

**Comment by ekaunt** [comment] 2020-12-22 03:29
> In Libreoffice if I set the language for the selection to the Japanese, it disjointed the characters. But if I set the language to the 'None (do not check spelling)', it substituted the characters. But I don't know what to set in the font for permanent substitutions.

that works!

but it still doesnt work in other programs on my computer

> I changed the Contextual Chaining Substitutions to the Contextual Substitutions and it looks OK again. If you export some lookup and then load it from the .fea file, then I think the Cont. Chaining Subst. will change to the Cont. Subst.

I'm actually creating my substitutions through a feature file. How can I make my substitutions not happen through a chained subtitution in a feature file? `calt` by default makes it a chained substitution, so how can I disable the chaining feature within a feature file?

**Comment by ekaunt** [comment] 2020-12-22 05:03
so the issue was that the font wasnt set as embeddable with pdfs

how can i do this through the python api?

**Comment by ctrlcctrlv** [comment] 2020-12-22 05:47
The fact that changing the language worked means you should explore the `languagesystem` tag of feature files. You might need to add the default language to each substitution subtable.

**Comment by ekaunt** [comment] 2020-12-22 06:09
@ctrlcctrlv thanks for responding!

I already added 
```
languagesystem DFLT dflt;
languagesystem cyrl dflt;
languagesystem geor dflt;
languagesystem grek dflt;
languagesystem hebr dflt;
languagesystem kana dflt;
languagesystem latn dflt;
languagesystem hani dflt;
```
to my feature file, so it should work in japanese and english languages

**Comment by KamilLanda** [comment] 2020-12-22 11:46
The problem is the FontForge really loads from the .fea file the Calt (Contextual) definitons as CCalt (Contextual Chaining). For Arabic script I had the reverse problem, it loaded the saved CCalt as Calt - but I was able to change it manually because there wasn't so many substitutions. 

I didn't find what to do in the .fea file for getting exactly CCalt or Calt. I tried to edit directly the .sfd file, but without success, because there is more differences between CCalt and Calt definitions than 1 or 2 items.

**Comment by ekaunt** [comment] 2020-12-22 15:03
> I didn't find what to do in the .fea file for getting exactly CCalt or Calt. I tried to edit directly the .sfd file, but without success, because there is more differences between CCalt and Calt definitions than 1 or 2 items.

So basically in short I'm screwed?

**Comment by KamilLanda** [comment] 2020-12-22 19:26
Yes, you need to change the CCalt to the Calt. 

I don't know if it will be universal solution for all cases, because sometimes in my Arabic font I had to try both variants -> sometimes it was functional only for CCalt and sometimes only for Calt, sometimes for both ones -> and I didn't know beforehand what will be functional. 
Maybe in some Japanese cases it can be similar "mishmash" -> sometimes maybe only Calt will be functional, sometimes CCalt, and sometimes both ones without problem. But it looks the Calt is OK from the examples. 

The example with Calt was functional, so I compared the .sfd files with CCalt and Calt -> and there is main difference, CCalt has "Lookup: 6" & "ChainSub", and Calt has "Lookup: 5" & "ContextSub" -> there is green line in the prinstscreen and it is easy to change it. 

But there is also problem with other definitions in the .sfd file, I marked it by red box, and I don't know how to change the CCalt variant to the Calt variant correctly. If you will find some informations about these items (probably in some documentation) and right informations how to set correctly these items for Calt, then you maybe will solve your problem. But for my bad English it is difficult (more likely impossible) try to find&browse some documentation. 

![comparison](https://user-images.githubusercontent.com/61148366/102925453-abe93200-4493-11eb-816b-af27f87b7237.png)

**Comment by ekaunt** [comment] 2020-12-24 03:01
Time to throw a wrench into the whole thing. 

When I apply the feature file to [this font ("hanamin")](https://mega.nz/file/z45wyaJR#dJ6at09PaB66Fof7yqGT-G_fGwtbDcXmNZkwtl-7q40), it works everywhere perfectly no matter the language…

I tried finding out the difference between the two fonts, but I can't figure it out, so I thought that maybe you can with your fancy skills

**Comment by ekaunt** [comment] 2020-12-24 04:49
all of yall were right. its *was* the language tag that was causing issues. i had the language tag set to `dflt`, but i shouldve also set it to `JAN` (that means japanese), so my current languagesystemls lines look like this

```
languagesystem DFLT dflt;
languagesystem DFLT JAN;
languagesystem kana dflt;
languagesystem kana JAN;
languagesystem latn dflt;
languagesystem latn JAN;
languagesystem hani dflt;
languagesystem hani JAN;
```

**Comment by ekaunt** [comment] 2020-12-24 04:57
Most of my problems were fixed by setting the language right, but it still doesnt convert everything properly.  

Here you can see within the fontforge window the conversion that's taking place is just as I want it.

![image](https://user-images.githubusercontent.com/62402760/103061764-5a67a280-457a-11eb-89bf-f7ab04dea65f.png)

![image](https://user-images.githubusercontent.com/62402760/103061829-72d7bd00-457a-11eb-9634-2b2aa330dae4.png)

But in all other programs, the え doesn't turn into へ. Only in fontforge's metrics window does it do the substitutions properly. This one doesnt matter which language I have set, it always works in fontforge, and it never works anywhere else. not even with the hanamin font…

**Comment by ctrlcctrlv** [comment] 2020-12-24 09:20
I find that substitution bizarre as someone who speaks the language 

Glad my idea worked... I'll look into it more tomorrow but for tonight I'd say try it with `hb-view`

You could also be running into a classic run segmentation problem. The Han character is getting put into one shaper run and the hiragana in another. Consequently they'll never interact. This is a known deficiency in the OpenType standard. to the point that I have attended meetings where people are discussing ways to patch the standard to fix this.

**Comment by ekaunt** [comment] 2020-12-25 20:58
hb-view does indeed do it correctly. how come?

**Comment by ctrlcctrlv** [comment] 2020-12-25 21:14
So I guess the purpose of this font is to turn modern Japanese into classical Japanese, as well as can be done automatically?

**Comment by ekaunt** [comment] 2020-12-25 21:16
That is correct

**Comment by ctrlcctrlv** [comment] 2020-12-25 21:26
Merry Christmas.

It is certainly an issue of run segmentation, and not a problem in FontForge.

The OpenType standard segments lookups by script. This creates an edge case in the case of Japanese.

This is because Japanese is more than one script. In old versions of OpenType, it was considered three scripts. (`hani`, `hira`, `kana`) Now, it is considered two. (`hani`, `kana`) _Cf._ ISO 15924.

This means that two shaper runs occur on your text. `hb-view` forces one shaper run to happen because `hb-view` knows that only one font will be used and it performs no font fallback.

So, your text...

会えるという

Is being segmented thus:

SHAPER RUN ONE
* 会
SHAPER RUN TWO
* えるという

Because no rule matches, nothing happens.

@khaledhosny taught me about this. There's nothing we can do. You'll need to only use the font in contexts where you can control the number of shaper runs that occur.

You may be interested in contributing to the Font and Text Working Group. @lianghai is the chair.

**Comment by ctrlcctrlv** [comment] 2020-12-25 21:28
(I will say, that doing this in OpenType is probably not wise in the first instance. But my message explains the technical reason this will not work. This level of magic probably should not happen in a font. However, run segmentation causes other issues that should be fixed in the relevant standards.)

**Comment by ctrlcctrlv** [comment] 2020-12-25 21:29
I'll leave this open because the issue raised above by @KamilLanda remains of interest.

**Comment by ekaunt** [comment] 2020-12-26 00:50
> I will say, that doing this in OpenType is probably not wise in the first instance. 

What format would be better?

**Comment by ctrlcctrlv** [comment] 2020-12-26 00:52
I'm not aware of any font format that would be better. 

I don't think a font should do this. You should write a program that does the substitutions on the actual byte stream. That's how I'd solve this particular problem. 

However maybe Apple Advanced Typography or Graphite don't have this limitation of run segmentation? I don't know enough to comment on that, I only target OpenType in my fonts.

**Comment by ekaunt** [comment] 2020-12-27 16:46
I tried doing it with Graphite, and it works much better now, so thanks for that suggestion

**Comment by ctrlcctrlv** [comment] 2020-12-27 22:58
I am interested! Thanks! That's sad but not altogether surprising. Determining the number of shaper runs is seen by many developers as independent of the shaper. Most developers don't even think about the edge case where different scripts coexist in a font and interact in one shaper run.

**Comment by ctrlcctrlv** [comment] 2020-12-27 22:58
We need a real standard for run segmentation, and it should be part of OpenType.

**Comment by ctrlcctrlv** [comment] 2020-12-31 19:03
Closing, correct venue is standards bodies. 

The CCalt thing isn't the issue in this case, I confirmed both meanings are identical.

**Closed by ctrlcctrlv** 2020-12-31 19:03 UTC

**Comment by Yukinoroh** [comment] 2024-10-02 17:18
Hi, I don't know if that helps, but LibreOffice relies on Harfbuzz to apply features, and Harfbuzz is shutting down OpenType features if AAT features are present. A bug has been submitted to LibreOffice but then shut down by the Harfbuzz developer, and the same person has had LibreOffice disable the feature in the UI as well.
See https://bugs.documentfoundation.org/show_bug.cgi?id=160634
and https://bugs.documentfoundation.org/show_bug.cgi?id=163213
Inkscape behaves normally because they are using an older, unaffected version of Harfbuzz. I would recommend referring to Inkscape for now to test your fonts.
