### ISSUE TITLE
Homebrewed FontForge can not run without network access

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#2097] opened 2015-03-02 14:22 UTC
Trying to use fontforge today on a train, I found that it crashes if there is no active network connection:
```
$ fontforge *ttf
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 17:55 EST 14-Jan-2015-ML-D.
 Based on source from git with hash: 
no xdefs_filename!
TESTING: getPixmapDir:/usr/local/share/fontforge/pixmaps
TESTING: getShareDir:/usr/local/share/fontforge
TESTING: GResourceProgramDir:/usr/local/bin
trying default theme:/usr/local/share/fontforge/pixmaps/resources
fontforge.hasUserInterface!
PyFF_onAppClosing() cnt:1
15-03-02 14:17:12 E: (UDP) error 'Can't assign requested address' on bind
Assertion failed: (false), function zsys_socket_error, file zsys.c, line 539.
Abort trap: 6
$
```

**Comment by frank-trampe** [comment] 2015-03-09 23:26
@davelab6, can you provide a backtrace for me?

**Comment by davelab6** [comment] 2015-03-09 23:37
Where is the documentation on how to make a backtrace, again? Sorry I keep
forgetting this :(

**Comment by frank-trampe** [comment] 2015-03-11 01:38
Run the core executable with the `--debug` option. You did it just a few days ago.

**Comment by davelab6** [comment] 2015-03-11 01:49
But this only happens on homebrew, not the app bundle, so that arg isn't
available.

```
$ fontforge --debug
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <
http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read
LICENSE.
 Based on sources from 17:55 EST 14-Jan-2015-ML-D.
 Based on source from git with hash:
no xdefs_filename!
TESTING: getPixmapDir:/usr/local/share/fontforge/pixmaps
TESTING: getShareDir:/usr/local/share/fontforge
TESTING: GResourceProgramDir:/usr/local/bin
trying default theme:/usr/local/share/fontforge/pixmaps/resources
fontforge.hasUserInterface!
PyFF_onAppClosing() cnt:1
else argv[i]:--debug
15-03-11 07:18:00 E: (UDP) error 'Can't assign requested address' on bind
Assertion failed: (false), function zsys_socket_error, file zsys.c, line
539.
Abort trap: 6
$
```

**Comment by frank-trampe** [comment] 2015-03-11 02:01
Oh. Sorry about that.

Run FontForge normally, run `ps -Af | grep fontforge`, get the pid, run `gdb /usr/local/bin/fontforge`, in gdb run `attach` with the pid that you found earlier, `cont`, make it crash, and `where`.

**Comment by frank-trampe** [comment] 2015-04-23 22:30
I think that this is a duplicate of #1987.

**Closed by frank-trampe** 2015-04-23 22:30 UTC
Labels: collab, Homebrew, I-crash
