### ISSUE TITLE
Crash Font/Glyph info window when press any key

### ISSUE THREAD

**Issue by BetaF1sh** [fontforge/fontforge#3360] opened 2018-11-12 04:57 UTC
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [x] Screenshot
- [x] The FontForge version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

### Details

version : 20170731
video: https://youtu.be/-zdWlZhZBz4

Pressing any key in the Font/Glyph information automatically closes the window. But backspace works.

**Comment by skef** [comment] 2019-01-10 11:17
The video you link to is no longer available, and the problem description is a bit vague. Could you update the bug with a bit more detail and, if possible, a screenshot?

**Comment by BetaF1sh** [comment] 2019-01-10 13:06
@skef I've open the video.

**Comment by skef** [comment] 2019-01-11 06:36
This is .. strange. It seems most likely to be some interaction between your environment and the X server that is causing key events to be interpreted wrong. 

Other users are running FontForge under MacOS, the way FontForge works under MacOS is going to change soon, and it's difficult for volunteers to find the cause of this kind of issue. I suggest:

1. Running some other X application to see if it fails the same way
2. Trying to run FontForge on a different but similar computer (same OS) to see if it works there.
3. Seeking out "local" IT support for your case. (Someone who can be in front of your computer and use it directly is better placed to find the problem.) 

Beyond that, I am closing this issue.

**Closed by skef** 2019-01-11 06:36 UTC
