### ISSUE TITLE
Error "Bad image file" when importing image

### ISSUE THREAD

**Issue by Lynzzyr** [fontforge/fontforge#5096] opened 2022-09-01 16:52 UTC
When trying to import a PNG or JPG, FontForge always fails to import with the error:

Bad image file
(PATH OF IMAGE FILE)

This occurs on FontForge version 2022-03-08, on macOS 12.5.1.
Does anyone get this issue, and if so, have a solution?

**Comment by Likenttt** [comment] 2022-11-15 09:51
Same isssue

**Comment by ctrlcctrlv** [comment] 2022-11-16 08:47
Likely duplicate of #4082.

**Closed by ctrlcctrlv** 2022-11-16 08:47 UTC

**Comment by syntactical** [comment] 2023-07-06 13:52
Seconded, I am having the asme error on macOS 12.6 and version 20230101.

I re-saved the image as a .bmp, and reimported it and it worked, however after importing it I got an error window saying `Failed to serialize PNG`, presumably from the previous import attempt.
