### ISSUE TITLE
Require `--without-libuninameslist` to compile when `libuninameslist` is not present

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3612] opened 2019-04-01 04:33 UTC
(This issue started out as a different report that could be resolved by building with libuninameslist installed. I'm updating the description with a comment from below.)

Suppose we were to change the compilation process to that it fails if:

1. libuninameslist is not present, and
2. `--without-libuninameslist` is not specified.

That amounts to a strong hint to installers that libuninameslist should be installed, that you really want to build with it rather than without it. And we can say as much in the instructions. However, installers who don't care about it can still just add `--without-libuninameslist` and have the same effect you get now when compiling without it.

It's a nudge, basically.

**Comment by skef** [comment] 2019-04-01 04:37
I take it part of this criticism is that the tooltip isn't enough help?

**Comment by ctrlcctrlv** [comment] 2019-04-01 04:39
Unicode's name for the glyph doesn't appear in the tooltip for me

**Comment by skef** [comment] 2019-04-01 04:40
Oh, wait, I think I misunderstand. This is really about the namelist more than anything. Even in the best Adobe list a lot are just referred to by codepoint. Are you thinking of names like "Combining Acute Accent"?

**Comment by skef** [comment] 2019-04-01 04:41
Or (to pick a more poetic example) U+3014 "Left Tortoise Shell Bracket"?

**Comment by ctrlcctrlv** [comment] 2019-04-01 04:41
I am thinking of names like that yes. Since I refer to these glyphs in feature files I'm also giving them descriptive names where they don't have them, but to get that far I still have to look it up the first time.

**Comment by skef** [comment] 2019-04-01 04:43
It does seem like more useful information than the Unicode block name.

**Comment by ctrlcctrlv** [comment] 2019-04-01 04:47
I think the block name should be in the tooltip or in "Glyph Info&hellip" if mentioned at all. I can't think of a time where knowing the block name helped me know what to draw, and certainly it's never been more helpful than Unicode's name for the glyph. :wink:

**Comment by skef** [comment] 2019-04-01 04:58
I was wondering about just swapping the glyph name in and the block name out. Having both could be awkward length-wise, but the block would be more appropriate as a label in the "scroll stream", which isn't currently possible because the glyph-group FontView interface (that I recall reading about somewhere) never made it "intro production". 

Hmm. From `fontforgeexe/fontview.c:SCPreparePopup` it looks like the code may already be designed to do this when https://github.com/fontforge/libuninameslist is installed.

**Comment by skef** [comment] 2019-04-01 05:08
I just tested and it works. Let me try to whip up a `PKGBUILD` for you.

**Comment by skef** [comment] 2019-04-01 05:25
Here's an Arch PKGBUILD to install from the git repository: [PKGBUILD.zip](https://github.com/fontforge/fontforge/files/3027862/PKGBUILD.zip)

I doubt it has all the dependencies, but you probably have everything needed already installed. Just unpack this into a directory and do `makepkg -si` and it should install. Then rebuild fontforge and you'll see the desired behavior.

**Comment by JoesCat** [comment] 2019-04-01 05:53
@skef - adding some info here that can help....
makeutype.c extracts combining classes from the unicode tables, and places them in a {0..255} location within the utype.c tables.
You can find it this way:
grep "FF_UNICODE_COMBININGCLASS" -R *

These values are then extracted using a function ffUnicodeUtype2
grep "ffUnicodeUtype2" -R *
This is extra info: GW made a set of handcoded tables Unicode/combiners.h which are/were visually correct in appearance and perhaps fixed a couple of errors, and I added a couple more to the list, but the combiners you probably are interested in are the one in FF_UNICODE_COMBININGCLASS

there is a list of what the values mean located somewhere on the unicode website, sort of looks like this: http://www.unicode.org/notes/tn2/tn2-2.html but I'm not sure where at the moment.
Hope this info helps...

**Comment by skef** [comment] 2019-04-01 05:57
As far as I can tell, @ctrlcctrlv's issue is addressed by compiling FontForge when the libuninameslist library is already installed. So this issue amounts to a documentation/configuration problem. I provided a PKGBUILD because both he and I are Arch Linux users, and that's the normal route on Arch to installing packages.

**Comment by JoesCat** [comment] 2019-04-01 06:03
more info... https://www.gnu.org/software/libunistring/manual/html_node/Canonical-combining-class.html
which shows the list UCD.html, which eventually brings you here
http://www.unicode.org/notes/tn2/tn2-2.html
http://www.unicode.org/reports/tr44/  <-scroll down to 5.7.4 for "combining classes"

**Comment by ctrlcctrlv** [comment] 2019-04-01 06:05
I've renamed the issue. This should be default...we can do use `git submodule` as many other projects do for this type of thing.

**Comment by JoesCat** [comment] 2019-04-01 06:05
> As far as I can tell
ok - thought you were referring to combing classes (this area needs more work).
Glad you figured it out.

**Comment by ctrlcctrlv** [comment] 2019-04-01 06:06
(By the way, thanks for the PKGBUILD.)

**Comment by skef** [comment] 2019-04-01 06:06
@ctrlcctrlv : I think the libuninameslist was factored out of the source base after a lot of controversy. It's not *that* hard to install it and FontForge is designed to work without it being installed. Maybe these sleeping dogs should lie.

**Comment by ctrlcctrlv** [comment] 2019-04-01 06:07
>Maybe these sleeping dogs should lie.

No, wake up sleeping dog! :-P

**Comment by ctrlcctrlv** [comment] 2019-04-01 06:08
By the way, I'm not saying we should pull it back into this repository, rather just try to pull it in by default, and only compile without it if we fail to pull it in. Separation is good.

**Comment by skef** [comment] 2019-04-01 06:10
So basically you're saying `--without-libuninameslist` should become mandatory if the library isn't already installed?

**Comment by ctrlcctrlv** [comment] 2019-04-01 06:13
Nah, autogen.sh can pull it in (`git submodule init; git submodule update`), then we can direct automake to look for it in the local directory. I've worked on other projects that did this. If it can't be found, just build without it.

**Comment by skef** [comment] 2019-04-01 06:15
Pulling it in by default via git just invalidates the separation at a different level. If a distro -- like Debian for example -- packages it separately, and FontForge tries to build its own if it doesn't find it installed, then you get packaging and installation conflicts.

**Comment by ctrlcctrlv** [comment] 2019-04-01 06:16
How can Debian package it separately if you have to rebuild FontForge to use it? Are there two packages?

**Comment by JoesCat** [comment] 2019-04-01 06:16
> So basically you're saying --without-libuninameslist

libuninameslist was designed to be separate, to follow the unicode schedule I believe, plus it was also used in another program called UMap - http://umap.sourceforge.net/
Older 2012 codebuilding was designed to use a local *.h file so that it could lazily pull in libuninameslist afterwards if the user wanted the extra functionality. The newer configure.ac removed the choice, but defaults to -with-libuninameslist if the *.h file and library happen to be available.

**Comment by ctrlcctrlv** [comment] 2019-04-01 06:17
I've worked on plenty of projects that pull in and statically link libraries that might be available on the system just to be sure. This one is very unlikely to be available.

**Comment by skef** [comment] 2019-04-01 06:18
On my hypothetical there would be two packages. Generally speaking distros package things separately when they "come" separately.

**Comment by ctrlcctrlv** [comment] 2019-04-01 06:19
I mean are there two _FontForge_ packages? `fontforge` and `fontforge-with-uninameslist`?

**Comment by ctrlcctrlv** [comment] 2019-04-01 06:19
Because otherwise I don't understand how you get around the conditional compilation

**Comment by skef** [comment] 2019-04-01 06:20
No: in that system there would be a fontforge package and a libuninameslist package, and the former would have a package dependency on the latter.

**Comment by skef** [comment] 2019-04-01 06:20
There is no need for conditional compilation -- the FontForge build process uses the library when it finds it and doesn't use it when it doesn't find it.

**Comment by ctrlcctrlv** [comment] 2019-04-01 06:22
So in your example you couldn't install `fontforge` without `libuninameslist` anyway.

**Comment by skef** [comment] 2019-04-01 06:24
Let me clarify my suggestion for this issue rather than putting it in someone else's mouth:

Suppose we were to change the compilation process to that it fails if:

1. libuninameslist is not present, and
2. `--without-libuninameslist` is *not* specified. 

That amounts to a strong hint to installers that libuninameslist *should* be installed, that you really want to build with it rather than without it. And we can say as much in the instructions. However, installers who don't care about it can still just add `--without-libuninameslist` and have the same effect you get now when compiling without it. 

It's a nudge, basically.

**Comment by skef** [comment] 2019-04-01 06:26
@ctrlcctrlv : right, if you compile FontForge against the library, the library has to be present to run it. But given that they're distributed separately they shouldn't be package together. Or at least not automatically -- if some distro wants to put them in the same package they're free to.

**Comment by ctrlcctrlv** [comment] 2019-04-01 06:27
OK, I approve of that. I've _never_ heard of it and I've used this program since I was in high school seven years ago. If we need `--without-x` when X isn't installed, we should need `--without-libuninameslist`.

**Comment by ctrlcctrlv** [comment] 2019-04-01 06:28
New issue name :sunglasses:

**Comment by skef** [comment] 2019-04-01 06:29
Oops, we overwrote one another ..

**Comment by JoesCat** [comment] 2019-04-01 06:29
FYI - we lacked "the nudge" for a few years because building FontForge from source was already pretty difficult after 2012 with the new configure.ac, and a lot of bugs had to be fixed before it got this much easier to build. Looking at spiro, many distros have already accepted the 2015 version, but libuninameslist is still got many distros hanging onto 2009 versions

**Comment by skef** [comment] 2019-04-01 06:32
@JoesCat: I wouldn't object to a different configuration option that pulls in and compiles `libuninameslist` for "unified packaging and installation", to make things easier for packagers. Especially if it's not that difficult to compile in terms of dependencies. But if its distributed separately the build shouldn't do that by default.

**Comment by JoesCat** [comment] 2019-04-01 06:32
FYI - 20190305 will be appearing soon in the debian world:
https://salsa.debian.org/fonts-team/libuninameslist
Fedora has already got the Redhat side covered: https://src.fedoraproject.org/rpms/libuninameslist

**Comment by skef** [comment] 2019-04-01 06:33
So basically we have relatively good traction now. (But not with Arch. I wonder who to talk to about that ...)

**Comment by JoesCat** [comment] 2019-04-01 06:34
There were a few years to gain acceptance... look into the m4 directory with arg, and it has a lot of version checks.... It takes time for everyone to get onboard :-) , so, we just needed to be patient

**Comment by ctrlcctrlv** [comment] 2019-04-01 06:36
I'm an AUR maintainer but I unfortunately do not maintain `fontforge-git`. I'll leave a comment there&mdash;do you want to push your `libuninameslist` package to the AUR or should I? Once it's in the AUR we would need to get it into the repo, probably `community`. Then we could ask the maintainer of `fontforge`'s PKGBUILD to include it.

**Comment by skef** [comment] 2019-04-01 06:37
I don't trust my PKGBUILD dependency list, and have never pushed anything to AUR, so you're in a better position to negotiate all that.

**Comment by ctrlcctrlv** [comment] 2019-04-01 06:38
[Here's my AUR profile.](https://aur.archlinux.org/packages/?SeB=m&K=fbrennan) I'll push it but put you as a "Contributor", OK?

**Comment by skef** [comment] 2019-04-01 06:38
It might help to prepare an `Extras`-style PKGBUILD for Libuninameslist - version 20190305.

I'm happy to be listed as contributor.

**Comment by skef** [comment] 2019-04-01 06:43
@JoesCat Are there dependencies other than basic build tools and `autoconf`?

**Comment by ctrlcctrlv** [comment] 2019-04-01 06:46
Don't worry, as a professional AUR maintainer&trade;, (:joy:) I compile all of my packages in a VM without anything installed to suss out all the dependencies.

**Comment by skef** [comment] 2019-04-01 06:47
Good to know!

**Comment by JoesCat** [comment] 2019-04-01 06:47
probably malloc() due to building some strings in the functions, beyond that, it's all just a large text file to maintain compatibility. Most dependencies are going to be for the test program.

**Comment by skef** [comment] 2019-04-01 06:48
(And how presumptuous of me to make a PKGBUILD for a professional AUR maintainer!)

@JoesCat: Ah, so strictly low-level stuff. Good.

**Comment by JoesCat** [comment] 2019-04-01 06:52
I was going to say it's greenlight across the board for sid... but appears I'll need to look at what caused them two reds: https://packages.debian.org/sid/libuninameslist-dev
It appears to be well behaved with Fedora various builds

**Comment by skef** [comment] 2019-04-01 06:56
(I used to be a gentoo person but I never updated frequently enough and always wound up in perl package dependency hell. They really haven't solved the dependency problem across timespans of more than a month or two. I do like the idea of source distributions and wish them well.)

**Comment by JoesCat** [comment] 2019-04-01 07:04
know what you mean - FontForge fell into a python dependency quagmire after 2012, where configure.ac required 2.7 due to required build of libunicodenames, but Debian was still 2.6, there are plenty of issues referring to this time period back in 2012..2014. @ctrlcctrlv - let me know if you run into friction.

**Comment by JoesCat** [comment] 2019-04-01 07:10
> Ah, so strictly low-level stuff. Good.

This issue says going retro helps everybody:
https://github.com/fontforge/libspiro/issues/9
...so yes, tried to maintain old K&R and C89 ...but you can only go backwards so far.
Fontforge at the commandline is sort of achievable, but the GUI, no.

**Comment by skef** [comment] 2019-04-01 07:55
Oh -- that was in response to me. I don't mentally classify the "age" of an interface as high- or low-level, its more about libraries and levels of abstraction. I was mostly just happy that the list I guessed at in my PKGBUILD was about right.

**Comment by ctrlcctrlv** [comment] 2019-04-04 12:37
Update:

I've [uploaded the package to the AUR,](https://aur.archlinux.org/packages/libuninameslist) and [asked the FontForge AUR maintainer to begin depending on it.](https://aur.archlinux.org/packages/fontforge-git/#news)

**Comment by RavuAlHemio** [comment] 2019-04-04 14:34
Hi, I’m the AUR (Arch User Repository) maintainer of `fontforge-git`. Currently, it depends on `libunicodenames`. Should I add `libuninameslist` oder replace `libunicodenames` with it?

(As for informing the packager of the `fontforge` package, which is an official Arch Linux package, you can open a bug on the Arch bugtracker, but you can probably just as well release the new version; they will likely simply hunt down the dependency once they try building it.)

**Comment by JoesCat** [comment] 2019-04-04 19:23
Right now libunicodenames has not been updated in years so it will be several hundreds of definitions behind today's information. You can continue to build it as a library for older instances of fontforge but it is recommended to move to the latest libuninameslist instead so that users using today's  fontforge have access to the most recent info which is now unicode version 12.1.
Sometime ago in 2016 or 2017 the configure m4 file was further upgraded and there were some problems in trying to maintain both libunicodenames as well as libuninameslist due to lack of some functionality... it may have been maintaining the configure without python or some other reason which I don't recall at the moment. Mostly due to lack of updates to libunicodenames libunicodenames will not get installed in current fontforge and the configure would need to be edited as well.
To see these libraries in action you can hover the mouse over a font and a pop up will appear with added information.

To make a long story short, At the moment libunicodenames won't be added. It needs updating and nobody appears to be asking for it. Please use libuninameslist. 

-------- Original message --------

**Comment by RavuAlHemio** [comment] 2019-04-04 19:33
Thanks for the explanation; a moment ago, I have replaced the `libunicodenames` dependency with `libuninameslist` in the AUR package `fontforge-git`.

**Closed** 2019-06-06 09:42 UTC
