### ISSUE TITLE
Feature Request: Points of Inflection

### ISSUE THREAD

**Issue by typedesigner** [fontforge/fontforge#3197] opened 2017-10-30 15:44 UTC
@frank-trampe @davelab6 

Hello,
would be very useful to add "Points of Inflection" feature. Comparable to the function: add extreme points.
Can you please program this?

**Comment by Anonrate** [comment] 2017-10-31 22:11
I do believe that this is already a feature.  Check `View>Show>Points of Inflection`  If you can't see anything, try changing the colors around a bit via `File>X Resource Editor...>Outline View>Points of Inflection Color`

**Comment by davelab6** [comment] 2017-10-31 23:07
Yeah but he means too add control points at those locations currently only
indicated visually

**Comment by typedesigner** [comment] 2017-11-01 08:00
What is needed is a feature that automatically adds these "Points of Inflection". Such as exterema points. That would save a lot of time. Adding "Points of Inflection" manually requires a lot of time.

**Comment by linusromer** [comment] 2019-11-28 15:51
Maybe my plugin is useful for you. It can add inflection points automatically:
https://github.com/linusromer/harmonize-tunnify-inflection

**Comment by skef** [comment] 2020-02-02 16:26
Duplicate of #147

**Closed by skef** 2020-02-02 16:26 UTC
