### ISSUE TITLE
GNU freefont requires fontforge before 20120731 to build

### ISSUE THREAD

**Issue by HinTak** [fontforge/fontforge#4261] opened 2020-04-05 00:49 UTC
Conversation about GNU freefont elsewhere - 
https://github.com/HinTak/Font-Validator/issues/54#issuecomment-609110069

Apparently it requires an antique version of fontforge to build the kern table correctly. I did a quick search about open bugs on kern but nothing jumps out - surely either fontforge needs to be fixed or GNU freefont needs to remove that restriction?

@StevanWhite

**Comment by frank-trampe** [comment] 2020-04-05 00:59
There was a lot of chaos between 2012 and 2014. My guess is that any such regressions are now remedied. It is certainly worth testing.

**Comment by skef** [comment] 2020-04-05 01:10
The note says "FontForge versions since 20120731 screw up Arabic kerning tables." The code still doesn't do great with Arabic.

**Comment by HinTak** [comment] 2020-04-05 01:14
There is a handcraft message about new fontforge screwing up Arabic kerning tables; plus a fair number of significant python exceptions (missing __dict__ attributes) using fontforge's python scripting. I'd say @StevanWhite should take a look at current fontforge and follow up...

**Comment by skef** [comment] 2020-04-05 01:48
I'll add that it would be great if there were some source of *reliable* and *comprehensive* data about problems with FontForge's and Arabic scripts. If we could get a fairly definitive list I would be willing to plug away on the fixes.

**Comment by ctrlcctrlv** [comment] 2020-04-05 02:31
GNU FreeFont is a monospace font so I have no idea what type of kerning is even supposed to be done.

Failure to build reports should be accompanied by what is actually failing. Does FontForge fail to execute a script that once worked? Is the output somehow deficient? If so, how?

This bug report is deficient until these questions are answered

**Comment by skef** [comment] 2020-04-05 02:45
@ctrlcctrlv The issue here is a Makefile test ( http://svn.savannah.gnu.org/viewvc/freefont/trunk/freefont/sfd/Makefile?revision=4001&view=markup ). @HinTak is presumably hoping for an updated look into what the issue is and, if necessary, some kind of fix.

**Comment by ctrlcctrlv** [comment] 2020-04-05 05:32
I don't understand why that's our problem. Remove the test and try to build...that's the minimum for opening a bug upstream. We're not even sure *if* there's a problem. We didn't add that test.

**Comment by HinTak** [comment] 2020-04-05 07:02
I have indeed removed the test (as stayed in my comment above), and built. It completed with a pile of python exceptions. No idea if the outcome is correct. Hence it is a question between the font people (the person who put that message there) and fontforge. I could just as well file an issue over there at savannah and cc the fontforge people.

**Comment by HinTak** [comment] 2020-04-05 07:28
As for the monospace kerning question

**Comment by ctrlcctrlv** [comment] 2020-04-05 18:47
So if it's a question between "the font people" and us, where do you come in?

If you don't know whether the outcome is correct, then this entire bug is invalid. The GNU FreeFont maintainer should open a bug if one actually exists.

Closed as invalid.

**Closed by ctrlcctrlv** 2020-04-05 18:47 UTC
Labels: dubious

**Comment by frank-trampe** [comment] 2020-04-05 18:56
Second-hand bug reports tend to be difficult, let's make the most of this. @HinTak, could you patch the Freefont folks into the conversation? I'd like to get this resolved. Whether it's our fault or theirs, they ought to face us like real men rather than writing us off (as might have been appropriate when the project was unmanaged).

**Comment by ctrlcctrlv** [comment] 2020-04-05 19:05
I agree.

Either a new bug should be opened or this one renamed and reopened. "GNU freefont requires fontforge before 20120731 to build" is not, and never could be, a valid FontForge bug; it's a GNU FreeFont bug. If they have some reason for doing this, _that_ might be a valid FontForge bug. 

We need to know the reason though and if you're incapable of determining whether or not 20200314 generates correct output, they need to come here, not you.

**Comment by HinTak** [comment] 2020-04-05 19:10
@StevanWhite is the Freefont folk - at least the name is the same on github and savannah. Please comment.

**Comment by StevanWhite** [comment] 2020-04-06 05:51
Hi,

I'll remove that remark from the Makefile in FreeFont SVN.  It came from an
incorrect assessment.

As far as I know, the Arabic kerning tables are messed up in all versions
of Fontforge.
The last time I tested this (a few years ago now) three different builds
all showed issues.

I confess, I should open a bug report.

**Comment by frank-trampe** [comment] 2020-04-06 05:59
@StevanWhite, do it. We dare you. :grin:

And we want to get this fixed, of course.

**Comment by StevanWhite** [comment] 2020-04-06 06:04
Done

**Comment by HinTak** [comment] 2020-04-06 07:00
@StevanWhite : I think @frank-trampe meant you should re-test with a current-ish version of fontforge, and identify and file arabic kerning issue, if it is not working correctly (in addition to removing the scary warning about having to use an antique version of fontforge). That way everybody benefits.

**Comment by frank-trampe** [comment] 2020-04-06 07:06
I affirm @HinTak's reading. It seems to me that we have an opportunity to solve the underlying issue, and it benefits us all to do so.
