### ISSUE TITLE
Python3 packaging

### ISSUE THREAD

**Issue by vitalyvolkov** [fontforge/fontforge#1731] opened 2014-09-12 19:13 UTC
Hi! Is there any plans to support fontforge for python3? It would be good idea to create debian for that too.

**Comment by ahyangyi** [comment] 2015-08-18 10:55
Just asking, is it possible to import both fontforge and psMat in python3? I have failed to do so so far.

**Comment by jtanx** [comment] 2015-08-18 12:59
Ah yep, looks like this is a bug, introduced by 31d70ea3032041e756d295982e146120a28bbde0.

Python 2 initialisation should be named `initfontforge` and Python3 should be `PyInit_fontforge`

**Comment by eosrei** [comment] 2016-02-16 00:34
*This seems like the correct place to ask. Tell me if I should post elsewhere.*

There is no `python3-fontforge` package on Launchpad: https://launchpad.net/~fontforge/+archive/ubuntu/fontforge/+packages Will it be added? The Python3 build directions by @tshinnic are working. Python2.7 will be dropped from default installs in 16.04: https://blueprints.launchpad.net/ubuntu/+spec/foundations-x-python3-only

**Comment by davelab6** [comment] 2016-02-16 01:33
@eosrei This is the correct place, but, alas, there is not much activity on FontForge these days. If you want something added, you probably need to do it or organize it yourself. @frank-trampe is available for contract work on FF.

**Comment by eosrei** [comment] 2016-02-16 02:21
@davelab6 Yes, I see there isn't much activity. I'm in no rush. I'll add the project to my todo list. Thanks for the quick reply.

**Comment by davelab6** [comment] 2016-02-16 02:27
Awesome!! Thank you!! :D

**Comment by frank-trampe** [comment] 2016-02-16 02:42
I know that this is not the correct venue for this statement, but I think that dropping Python 2.7 from standard repositories is bad. It's not an outdated version of Python 3, it's a different language, and FontForge is not the only piece of software that hasn't made the transition. If ancient languages like Fortran and PHP are still supported, Python 2.7 ought to stick around as well.

**Comment by davelab6** [comment] 2016-02-16 03:03
Maintaining support for both is fine, but this is about not supporting python3 at all, right?

**Comment by frank-trampe** [comment] 2016-02-16 03:08
Right. I'm complaining about Ubuntu dropping support for the Python 2.7 that we all know, love, and depend upon.

**Comment by eosrei** [comment] 2016-02-16 03:10
@frank-trampe It's being dropped from the default install, not the repositories. [Python 2.7 EOL is 2020](https://hg.python.org/peps/rev/76d43e52d978), but it'll probably be available in the repos long after that. PHP 7.0 was just released a few weeks ago and even Fortran has active work.

@davelab6 Yes, Python 3.x is only supported when FontForge is manually compiled.

**Comment by mskala** [comment] 2016-02-16 06:07
Python (1991) is older than PHP (1995)...

**Comment by frank-trampe** [comment] 2016-02-16 06:10
I know, I know. But PHP feels ancient in substance. People still learn Python in school and create new products in it. People generally only use PHP because they already know it or are working on an existing product. I know that that's a sweeping generalization, but that's what it takes to start a flame war.

**Comment by davelab6** [comment] 2016-02-16 16:03
On 16 February 2016 at 01:11, Frank Trampe <notifications@github.com> wrote:

> People generally only use PHP because they already know it or are working
> on an existing product.


I don't think so.

**Comment by jtanx** [comment] 2016-10-04 12:39
I think I've found the cause; https://mail.python.org/pipermail/python-dev/2016-May/144797.html

In short, we shouldn't call PyImport_AppendInittab (or the RegisterAllPythonModules) when we're running system python (as a module).

**Comment by felipesanches** [comment] 2019-03-10 02:58
I have stumbled on this today.

I need a python3-fontforge package and since no-one did it in the last 4 years, I am now attempting to do so. Wish me luck!

**Comment by skef** [comment] 2019-03-10 08:56
This should be at most a packaging issue at this point. #3409, #3436, #3501, and #3458 were worked out primarily on python 3 and then back-tested with 2. `configure` will use the binary named with the `PYTHON` environment variable, or choose `python` from the path. 

I don't believe there is currently complete support for having simultaneous python 2 and 3 installations of FontForge. It will probably "just work" at a scripting level, but if an individual user wants to run a 2-supporting UI some days and a 3-supporting UI other days, they'll likely run into issues.

**Comment by felipesanches** [comment] 2019-03-10 10:15
Thanks for these notes. My major difficulty now is simply the fact that I never packaged software for Debian, so it is a new skill I still have to learn. I am diving into the several packaging guides and it all looks very interesting. Let's see if I can come up with something good enough in here, or if it is just some weekend yak-shaving fever...

**Comment by khaledhosny** [comment] 2019-05-26 02:25
I just found this PPA that builds FontForge with Python 3 https://launchpad.net/~silnrsi/+archive/ubuntu/smith-py3/

**Comment by jtanx** [comment] 2019-06-01 11:46
My plan is to make the next Windows build of FontForge use the Python 3 binding; the CI build is now failing because mys2 changed the default or something

**Comment by frank-trampe** [comment] 2019-06-01 11:49
Let's send a notification to the mailing list.

**Comment by jtanx** [comment] 2019-06-01 11:58
Done.

**Comment by skef** [comment] 2020-02-02 17:50
We're gradually encouraging the shift to python 3 (and may or may not drop python 2). There are no outstanding python 3 issues I'm aware of for this issue to represent, however. Closing.

**Closed by skef** 2020-02-02 17:50 UTC
Labels: maybe-done, packaging, question

**Comment by neilveil** [comment] 2021-01-20 18:54
Any update? I still can't import fontforge in python3
