### ISSUE TITLE
missing "layercontents.plist" in export as UFO format

### ISSUE THREAD

**Issue by aminabedi68** [fontforge/fontforge#3726] opened 2019-06-05 20:51 UTC
l'm a fontforge user for about 4 years and now im designing a variable font from two masters. I'm designing both masters inside fontforge and export them as UFO format. but the program i using ,fontmake, requires "layercontents.plist" file to generate variable font. i opened an issue for fontmake and explain the problem, they said this file is nessesary to fontmake, even if font have only one layer.

**Comment by aminabedi68** [comment] 2019-06-06 20:32
thank you.

**Comment by skef** [comment] 2019-06-11 22:16
@aminabedi68 A fix is in the works but it may take a while and it will be longer before there's another release. The problem is that FontForge is incorrectly skipping this file for single layer fonts. However, with such fonts the file will always be the same. So if you need a workaround just extract the file from this archive and put in in the UFO3 font's top-level directory after generating. That should make `fontmake` happy:

[lcsamp.zip](https://github.com/fontforge/fontforge/files/3278789/lcsamp.zip)

**Comment by aminabedi68** [comment] 2019-06-15 14:57
sorry for answering late @skef 
I created this file already for myself but thank you, it's very kind of you :)

**Closed** 2019-06-15 15:56 UTC
