### ISSUE TITLE
Program crashes when importing certain svgs

### ISSUE THREAD

**Issue by Hydr4gyrum** [fontforge/fontforge#4452] opened 2020-09-18 01:37 UTC
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

Font Forge Version:
202001314
Trying to import the svg in the contained .zip folder crashes the program
Reproduce behavior by importing the svg.

[broken.zip](https://github.com/fontforge/fontforge/files/5242836/broken.zip)

**Comment by skef** [comment] 2020-09-18 01:51
There have been SVG fixes since that release. Try following the advice at https://github.com/fontforge/fontforge/issues/4421#issuecomment-670613963

**Comment by skef** [comment] 2020-09-18 22:13
Actually, never mind. I just tested this with the current master and it still crashes. I'll investigate.

**Comment by skef** [comment] 2020-09-18 22:39
I'm not yet sure what the problem is but the first and last points in the contour are very close to one another but the contour isn't closed. If you add a "z" to the path to close it the crash goes away. 

This makes some sense because the crash is in `HandleCap()` and results from a corruption in the (post-offsetting) SplineSet passed to it (it has a valid `first` but no `last` and the linked list devolves into garbage). 

Given that the offset splines are added to the original `left`/`right` SplineSets in a pretty generic way my initial guess is that this is some problem in `SplineSetJoin()`.

And ... yes. A valid (at least at the linked list level) spline goes into `SplineSetJoin()` and an invalid one comes out. So I'll have to track that down.

**Comment by skef** [comment] 2020-09-21 00:11
If you replace calls to `SplineSetJoin()` in `splinestroke.c` with `SplineSetMakeLoop()` (which I'm going to do anyway because that's a more appropriate function) the crash goes away and is replaced with the warning "Contour start did not close". The resulting open contour is:

![b4452_1](https://user-images.githubusercontent.com/6175836/93724975-651c3100-fb60-11ea-95e4-5fb2f1e76ebc.png)

And the closeup of the relevant area is:

![b4452_2](https://user-images.githubusercontent.com/6175836/93725033-d78d1100-fb60-11ea-8367-cd0a5701bc60.png)

That last loop is just that: a separate closed contour.

Broadly speaking what seems to be going wrong here is a failure of the (round) cap heuristics due to the very small size (about 13 em-units high) and stroke width (just over 1 em unit) of the content. I'll see how easy it is to fix. 

There's a general mismatch between this content and the stroke code, which assumes at a number of points that an em-unit is small. Ideally the accuracy target would correct for that but when you're picking floating point margin cutoff constants based partly on trial and error your code won't work at every "magnification". The fact that SVGs can be specified in a tiny local space and then transformed is a problem. 

There are therefore multiple possibilities with this bug:

1. Get the code fully working for this case.
2. Just improve the code to avoid the crash and live with any incorrect content. (This is the easiest, as just using `SplineSetMakeLoop()` accomplishes that.
3. Provide a new scalar "prescale" parameter that allows the importer to influence the scale at which stroking happens. That way if you have small elements you could set the parameter to scale all points up by `X` on reading them and then scale down by `X` at the end.

**Comment by dstj** [comment] 2020-09-25 13:31
Hi there,

I'm having the same issue: FontForge crashes on just about any SVG import (see attached SVG in the zip). No log, no error message, no nothing, it just closes...

I leave the default options in the import dialog. I'm no font expert (nor SVG expert for that matter). The SVG is created by exporting as SVG from Adobe Illustrator.

Is this the same root cause?

[crashing.zip](https://github.com/fontforge/fontforge/files/5283015/crashing.zip)

Version: 20200314 from Chocolatey

**Comment by ctrlcctrlv** [comment] 2020-09-25 18:07
Did you try following the above advice first?

**Comment by dstj** [comment] 2020-09-25 18:31
@ctrlcctrlv Ahhh, my mistake, I had missed that first comment with a link to an unreleased build. 🤦‍♂️

It works in that one. Never mind me then. Thanks.

**Comment by skef** [comment] 2020-11-06 21:43
If the recent activity is preparing for a release I should do at least a partial fix for this (to protect against crashes). I'll put that on my short term list.

**Closed** 2020-12-04 16:05 UTC
