### ISSUE TITLE
UI Font/Character Set appear unreadable - Unicode issue?

### ISSUE THREAD

**Issue by Whitevinyl** [fontforge/fontforge#3918] opened 2019-09-05 10:01 UTC
macOS 10.12.3

FF versions tried:
2019-08-01
2019-04-13
2019-09-05

When I install & open FontForge it looks like this:
![fontf1](https://user-images.githubusercontent.com/6706406/64331304-72549500-cfca-11e9-8766-16e99a96c7bf.png)
![fontf2](https://user-images.githubusercontent.com/6706406/64331318-77b1df80-cfca-11e9-9af0-9239ba9c7dee.png)

I'm installing into my Applications folder. Could this be a Unicode issue?
My system language & region settings are English, United Kingdom, my system fonts should all be default, I've never touched them and not seen issues with any other software.

When I tried the 2019-09-05 build, it was still messed up but with a different character set - (all in boxes, sorry I didn't get a screenshot of this one).

**Comment by ctrlcctrlv** [comment] 2019-09-06 00:38
I think this is a duplicate of #3592. See https://github.com/fontforge/fontforge/issues/3592#issuecomment-477083104 ...

**Comment by ctrlcctrlv** [comment] 2019-09-06 00:43
We're going to need to see the problems in the more recent build. Just tofu?

**Comment by Whitevinyl** [comment] 2019-09-06 09:24
Ah sorry didn't find the duplicate - ok I have mainly fixed it thanks to the other comment.
I tried installing "Dejavu Sans" but that didn't change it.

I then looked through my Helvetica fonts and found one called "Helvetica GreekP" - once I removed that the UI changed. It's now readable although it's fallen back to another Helvetica variant with a few quirks, I have a lot of Helvetica variants installed so it'll take me a while to narrow down exactly which one.

I tried the latest version from here: http://dl.bintray.com/fontforge/fontforge/ - it looked much like in the other thread, although I can't see a "HelveticaFractions" in my font library.

**Comment by ctrlcctrlv** [comment] 2019-09-06 09:31
Helvetica GreekP is another terribly out of date Helvetica variant and is certainly the cause of the problem.

This is how it displays the text "New Open Recent"
![2019-09-06-173122_1109x233_scrot](https://user-images.githubusercontent.com/838783/64417618-078b8280-d0cc-11e9-97fa-4f1f63fbb0f1.png)

Why would you even want this font in the post-Unicode era? It sounds like you just have a bunch of ancient pirated fonts installed and should delete them.

**Comment by ctrlcctrlv** [comment] 2019-09-06 09:32
These fonts with non-standard encodings are certainly interesting for their historical value, but you should not install them and expect modern day applications to work right.

**Comment by ctrlcctrlv** [comment] 2019-09-07 05:56
No comment, so I'm closing this bug as invalid...

* The problem is in Pango
* I doubt the Pango developers are going to consider this font precedence issue important given how **unimportant** support for ancient fonts like `Helvetica GreekP` is
* I figured out the problem and OP fixed it

**Closed by ctrlcctrlv** 2019-09-07 05:56 UTC
Labels: dubious
