### ISSUE TITLE
ExpandStroke command in script cause no response

### ISSUE THREAD

**Issue by max32002** [fontforge/fontforge#4216] opened 2020-03-09 16:01 UTC
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
no need.

- [x] The FontForge version and the operating system you're using
Version: 20190801
Based on sources from 2020-03-06 21:59 UTC-ML-D-GDK3.
Based on source from git with hash: 428f56f

System Software Overview:
System Version: macOS 10.15.3 (19D76)
Kernel Version: Darwin 19.3.0
Boot Volume: Macintosh HD
Boot Mode: Normal

Hardware Overview:
Model Name: MacBook Pro
Model Identifier: MacBookPro12,1
Processor Name: Dual-Core Intel Core i5
Processor Speed: 2.7 GHz
Number of Processors: 1
Total Number of Cores: 2
L2 Cache (per Core): 256 KB
L3 Cache: 3 MB
Hyper-Threading Technology: Enabled
Memory: 8 GB

- [x] The behavior you expect to see, and the actual behavior
no response

- [x] Steps to reproduce the behavior 
Open("font-project.sfdir")
char_array = Ucs4('狺')
Print('char:',char_array)
Select(char_array[0])
ExpandStroke(11,45,11,11,0,1)

by the way:
ExpandStroke(10,45,1,1,0,1)
still cause process no response.

- [x] \(optional) Possible solution/fix/workaround
ExpandStroke(12,45,11,11,0,1)

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround
[uni72FA.glyph.zip](https://github.com/fontforge/fontforge/files/4307647/uni72FA.glyph.zip)

**Comment by skef** [comment] 2020-03-09 16:23
Dude -- I explained in the last of these you filed, as I closed it, that *this entire subsystem has been substantially rewritten*. And ignoring that you still haven't actually attached the font that matches your test code, so we couldn't reproduce even if that were not the case. 

**Don't file any more `ExpandStroke()` issues without testing with a more recent version**, like one of the `app.dmg` images here: http://dl.bintray.com/fontforge/fontforge/ (such as (http://dl.bintray.com/fontforge/fontforge/:FontForge-2020-03-05-881fbfb.app.dmg). 

Closing.

**Closed by skef** 2020-03-09 16:23 UTC
