### ISSUE TITLE
How do I get VSCode to recognize the fontforge module? 

### ISSUE THREAD

**Issue by fmotion1** [fontforge/fontforge#5286] opened 2023-09-02 18:38 UTC
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [x ] Screenshot

![Code_imfJJJtH9D](https://github.com/fontforge/fontforge/assets/33441569/26215309-6368-4c21-b64c-3643368989ad)

- [x ] The FontForge version and the operating system you're using

FontForge Version: 2023.01.01 (Latest)
OS: Windows 10 Pro x64 22H2

- [x] The behavior you expect to see, and the actual behavior

I'd like / expect to see VSCode recognize the `fontforge` module when I have `import fontforge` - so I can get autocompletion and remove distracting warnings and errors.

- [x] Steps to reproduce the behavior 

Create a new Python file in VSCode and add `import fontforge` at the top.

- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem

I think this is a big problem for FontForge script developers. Intellisense and auto-completion don't work for the module, and the full capabilities of the module can't be inspected in the IDE.

- [x] If the feature changes current behavior, reasons why your solution is better

Developers will really appreciate it. Scripts can be more rapidly developed.

- [ ] \(optional) Possible solution/fix/workaround

I would really appreciate a solution, workaround, patch, bug fix, you name it. If anyone knows how to accomplish this, please let me know!

Jay

**Comment by ctrlcctrlv** [comment] 2023-11-24 00:28
Duplicate of #4377. On Windows, only MinGW Python works, not MSVC Python.

**Closed by ctrlcctrlv** 2023-11-24 00:28 UTC

**Comment by pickaxe828** [comment] 2024-01-13 14:05
For those who wanted VSCode to stop showing that ugly squiggly line
This is the solution:
1. Copy the path to your Python intepreter
    - MacOS: `/Applications/FontForge.app/Contents/MacOS/FFPython`
2. Press this:
![image](https://github.com/fontforge/fontforge/assets/41852594/473a7671-7e9a-4f05-bc00-6c15f3185db6)
3. Press `Enter interpreter path...` then paste the path
4. Done! No more revolting squiggly line!

**Comment by Arlorean** [comment] 2024-02-05 16:51
I _think_ I've got VSCode showing me IntelliSense/code completion on Windows. It also seems to work with running/debugging too. I created a `settings.json` file in a `.vscode` directory local to my FontForge Python scripts. Opening the directory in VSCode uses these local settings:

![image](https://github.com/fontforge/fontforge/assets/1547800/56336a2b-40a0-4580-9aab-03dd17fac1ed)

In there I added these 3 settings, for the default Python interpreter (ffpython.exe), the language server (Jedi) and the path to the Python libraries:

**`settings.json`**
```json
{
    "python.defaultInterpreterPath": "C:\\Program Files (x86)\\FontForgeBuilds\\bin\\ffpython.exe",
    "python.languageServer": "Jedi",
    "python.analysis.extraPaths": [
        "C:\\Program Files (x86)\\FontForgeBuilds\\lib\\python3.10"
    ]
}
```

You can set these settings via the VSCode GUI if you want to see the options available. The language server seemed to be the key, changing it from **Pylance** to **Jedi**. 

![image](https://github.com/fontforge/fontforge/assets/1547800/0096256f-ecbf-4cf4-820d-fb87c23528eb)

Here is the IntelliSense in action:

![image](https://github.com/fontforge/fontforge/assets/1547800/77ac90f0-4135-406c-a8b4-6035553d2fb6)

I've not used this a lot yet so there may be a gotcha in there, but so far it seems to be more useful than not having it at all.
