### ISSUE TITLE
Suspected error in OS X FontForge.app/Contents/MacOS/FontForge script

### ISSUE THREAD

**Issue by krbeesley** [fontforge/fontforge#2480] opened 2015-09-03 22:05 UTC
Repost from fontforge-users

Title: Suspected error in OS X FontForge.app/Contents/MacOS/FontForge script

Background problem:  On OS X, 10.10.5, when I invoke FontForge (2015-04-30) from the command line

$ open -a FontForge  <nameOfAnExistingFont>

fontforge launches, but the indicated font is ignored.  Rather, fontforge always opens with a new empty ISO-8859-1 font.

On 3Sep2015, at 13:05, Dave Crossland <dave@lab6.com> wrote:
<snip>

When "open -a FontForge" your script calls what I assume is the latest packaged release, at /Applications/FontForge.app, which is the same as double clicking that app icon in Finder. 

When you do so, you run this shell script:

https://github.com/fontforge/fontforge/blob/master/osx/FontForge.app/Contents/MacOS/FontForge

You would need to edit that shell script, and yours, to pass the arguments supplied to the actual fontforge executable. 

End of message from Dave Crossland

On 3 September 2015 at 17:41, Kenneth Reid Beesley <krbeesley@gmail.com> wrote:

With respect, I think that this FontForge.app/Contents/MacOS/FontForge is broken.  Here’s what I’ve found:

1.  I’ve just taken a look at the script you cite (following the exact link above--which seems to point to a previous version).  I’m not an shell-script expert by any means, and some of it makes my
eyes cross, but it ends with the following if-statement, which looks reasonable:

if [ $# -eq 0 ] ; then
    ( exec $WRAPPER $bundle_bin/fontforge -new & )
else
    ( exec $WRAPPER $bundle_bin/fontforge "$@" & )
fi

That means that if the script is called with no command-line arguments (i.e. the count of arguments, stored in $#, is zero [ $# -eq 0 ]) then
execute the $WRAPPER with
fontforge -new
which will bring up FontForge with a default empty new ISO-8859-1 font.  That makes sense.
Else (if there is at least one command line argument) then execute the $WRAPPER with
fontforge “$@“

As usual, $@ represents (is expanded to) all the original command-line arguments.  That also makes perfect sense.  It looks to me like the _intent_ of the script is to pass along the command-line arguments typed by the user.  So the _intent_ was to allow me to invoke

$ fontforge myfont.otf

and have the exiting font myfont.otf opened rather than a new empty font.  Again, I think that was the _intent_ of the script, and it probably worked in some previous version.

*** The plot thickens ...

2.  But now I look at the FontForge.app/Contents/MacOS/FontForge script in the version that I just downloaded and installed (the downloaded disc image file is FontForge-2015-04-30-Mac.app.dmg, which I opened to find FontForge.app, which I dragged into /Applications/), and the final if-statement has been changed, with the two call formulas (shown above, from a previous release) conflated to the following single line:

$WRAPPER $bundle_bin/fontforge -new "$@“ &

That is, it looks like the current 2015-04-30 script is always calling fontforge with the -new argument followed by any user-supplied command-line arguments (which might be ignored in such a case?).

**** Is there a shell-script expert in the house?

3.  I tried commenting out this one final line and substituting a copy of the if-statement shown above from a previous release, and that didn’t seem to help.  I suspect that the problem lies in the definition of WRAPPER, which I haven’t figured out yet.  It looks suspicious to me (see especially, in the same script file, the definition and re-definition of WRAPPER before it is actually invoked inside the definition itself—-there’s also a suspicious call to WRAPPER that is commented out). The change to the final invocation(s) of fontforge looks suspicious.  In short, I suspect that this script is broken, and I suggest that the problem lies in the definition of WRAPPER.  Perhaps one of you is better than I am at reading and fixing such scripts.

Best,

Ken

**Comment by jtanx** [comment] 2015-09-04 00:14
Quite possibly related: #2405. cc @glyphobet

**Comment by glyphobet** [comment] 2015-09-04 00:44
Thanks for the heads up, @jtanx. @krbeesley is exactly right, the script was broken just as he describes, and this exact issue was fixed in #2405. Guess it's time for a new release?

**Comment by jtanx** [comment] 2015-09-04 01:18
Ah I see now, @krbeesley try updating to the latest version of FontForge

**Comment by krbeesley** [comment] 2015-09-04 04:57
> On 3Sep2015, at 19:18, Jeremy Tan <notifications@github.com> wrote:
> 
> Ah I see now, @krbeesley <https://github.com/krbeesley> try updating to the latest version of FontForge
> 
> 

OK.  Trying to update to the latest version of FontForge on OS X (10.10.5)...

1.  I downloaded FontForge-20150824.dmg (I assume that this is the “latest version”?), opened it up, and dragged FontForge.app into /Applications/

2.  In my .bashrc file I created:   alias fontforge=‘/Applications/FontForge.app/Contents/MacOS/FontForge ‘

3.  I opened a new terminal and launched

$ fontforge Deseret1868-Medium.sfd

and I got the following:

$ fontforge Deseret1868-Medium.sfd
PKGBASE: /Applications/FontForge.app
chantal:Deseret1868 beesley$ dyld: Library not loaded: /opt/local/lib/libfontforgeexe.2.dylib
  Referenced from: /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge
  Reason: image not found
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/MacOS/fontforge-crash-reporter.py", line 200, in <module>
    httpd = SocketServer.TCPServer(("127.0.0.1", PORT), Handler)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 48] Address already in use
Thu Sep  3 22:48:24 2015
0

What does all that mean?

By the way, the Detailed Guide for installation on OS X on  
http://fontforge.github.io/en-US/downloads/mac/ <http://fontforge.github.io/en-US/downloads/mac/>
still provides a download link that gets you the older 2015-04-30 version.


Thanks to all for your help,

Ken


********************************
Kenneth R. Beesley, D.Phil.
PO Box 540475
North Salt Lake UT 84054
USA

**Comment by glyphobet** [comment] 2015-09-07 03:02
@krbeesley, the error you paste in is a Python traceback, and almost certainly has nothing to do with the original shell script problems in this bug. So it should probably be in a different bug report.

That said, I do not get those errors on my system (OS X 10.9 Mavericks) with the version of FontForge, in the 2015-08-24 DMG. This indicates there is some missing information about differences between your system and mine. 

Most of the tracebacks (there are multiple here) indicate that FontForge's Python cannot find hash functions which are part of the standard Python library, so that points in the direction of something being wrong or missing about your Python installation. As a total wild guess, which version of OpenSSL do you have installed? Try `which openssl` in the console and post what that says.

The last traceback is about the crash reporter not being able to start, and can be ignored. 

You don't mention whether FontForge actually starts successfully or not after these errors. It might... does it?

Next time you post tracebacks, enclose them in triple backticks, that will make them fixed-width in Github, and they will be significantly easier for Python programmers to read.

**Comment by krbeesley** [comment] 2015-09-07 05:04
> On 6Sep2015, at 21:02, Matt Chisholm <notifications@github.com> wrote:
> 
> @krbeesley <https://github.com/krbeesley>, the error you paste in is a Python traceback, and almost certainly has nothing to do with the original shell script problems in this bug. So it should probably be in a different bug report.
> 
Perhaps.  

When I was trying to run the FontForge.app from FontForge-2015-04-30-Mac.app.dmg, I did not see anything like this Python traceback.   Using this version, I could launch FontForge successfully, except that if I tried something like

$ open -a FontForge  <nameofmyfont>

it would not open the indicated font.  Rather it would always open a new empty ISO-8859-1 font.

****

So I then downloaded Fontforge-20150824.dmg and installed the FontForge.app from that dmg in my /Applications/ directory.   Comments on the download page advised me to launch FontForge (on OS X) by invoking the launch script directly, i.e.

$ /Applications/FontForge.app/Contents/MacOS/FontForge 

and when I did that, I got the Python traceback that I posted.  FontForge 20150824 does NOT launch for me after the traceback.

> That said, I do not get those errors on my system (OS X 10.9 Mavericks) with the version of FontForge, in the 2015-08-24 DMG. This indicates there is some missing information about differences between your system and mine.
> 

I’m running 10.10.5 Yosemite
> Most of the tracebacks (there are multiple here) indicate that FontForge's Python cannot find hash functions which are part of the standard Python library, so that points in the direction of something being wrong or missing about your Python installation. As a total wild guess, which version of OpenSSL do you have installed? Try which openssl in the console and post what that says.
> 
> 
$which openssl

returns  

/usr/bin/openssl

$ openssl version

returns 

OpenSSL 0.9.8zg 14 Juy 2015

> The last traceback is about the crash reporter not being able to start, and can be ignored.
> 
> You don't mention whether FontForge actually starts successfully or not after these errors. It might... does it?
> 
> 

With the older FontForge-2015-04-30-Mac.app.dmg, I get no Python traceback, and FontForge launches (but always with a new empty ISO-8859-1 font).


With Fontforge-20150824.dmg, I get the Python traceback, and FontForge does NOT launch.

> Next time you post tracebacks, enclose them in triple backticks, that will make them fixed-width in Github, and they will be significantly easier for Python programmers to read.
> 

Sorry, I’m new at all this.

Ken


> —
> Reply to this email directly or view it on GitHub <https://github.com/fontforge/fontforge/issues/2480#issuecomment-138167584>.
> 


********************************
Kenneth R. Beesley, D.Phil.
PO Box 540475
North Salt Lake UT 84054
USA

**Comment by krbeesley** [comment] 2015-09-07 05:14
> On 6Sep2015, at 21:02, Matt Chisholm <notifications@github.com> wrote:
> 
> @krbeesley <https://github.com/krbeesley>, the error you paste in is a Python traceback, and almost certainly has nothing to do with the original shell script problems in this bug. So it should probably be in a different bug report.
> 
> 

As for my Python.  On my machine

$ which python

returns

/usr/local/bin/python

which is a symlink to ../Cellar/python/2.7.10_2/bin/python

This is the most recent version of Python as installed/upgraded by brew.



> That said, I do not get those errors on my system (OS X 10.9 Mavericks) with the version of FontForge, in the 2015-08-24 DMG. This indicates there is some missing information about differences between your system and mine.
> 
> Most of the tracebacks (there are multiple here) indicate that FontForge's Python cannot find hash functions which are part of the standard Python library, so that points in the direction of something being wrong or missing about your Python installation. As a total wild guess, which version of OpenSSL do you have installed? Try which openssl in the console and post what that says.
> 
> The last traceback is about the crash reporter not being able to start, and can be ignored.
> 
> You don't mention whether FontForge actually starts successfully or not after these errors. It might... does it?
> 
> Next time you post tracebacks, enclose them in triple backticks, that will make them fixed-width in Github, and they will be significantly easier for Python programmers to read.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/fontforge/fontforge/issues/2480#issuecomment-138167584>.
> 


********************************
Kenneth R. Beesley, D.Phil.
PO Box 540475
North Salt Lake UT 84054
USA

**Comment by glyphobet** [comment] 2015-10-01 05:46
@krbeesley there is a temporary fix for the second bug which you reported in your comment above [here](https://github.com/fontforge/fontforge/issues/2506#issuecomment-144622453). Look for the part about uncommenting the `export DYLD...` line inside your `FontForge.app`. 

For whoever has ability to close bugs; this bug, #2480 (the original issue reported at the top) should be closed as a duplicate of #2405.

**Closed** 2015-10-01 05:50 UTC

**Comment by krbeesley** [comment] 2015-10-09 22:02
> On 30Sep2015, at 23:46, Matt Chisholm <notifications@github.com> wrote:
> 
> @krbeesley <https://github.com/krbeesley> there is a temporary fix for the second bug which you reported in your comment above here <https://github.com/fontforge/fontforge/issues/2506#issuecomment-144622453>. Look for the part about uncommenting the export DYLD... line inside your FontForge.app.
> 

RE:  Launching FontForge on OS X  10.10.5

Hello Matt,

Thanks for your message from 20 September.  (I’m getting back to FontForge after a break.)
UNcommenting the line

# export DYLD_LIBRARY=$bundle_lib”

where bundle_lib is defined just above as

bundle=/Applications/FontForge.app
bundle_contents="$bundle"/Contents
bundle_res="$bundle_contents"/Resources
bundle_lib="$bundle_res"/opt/local/lib



in FontForge.app, as the “fix” suggested, got me only part-way.   
Launching FontForge then gave me an error message complaining that

libjpeg.9.dylib

could not be found in /opt/local/bin.  That means, if I’m right, that the launch script
first looked for libjpeg.9.dylib in /Applications/FontForge.app/Contents/Resources,
didn’t find it, and then looked in /opt/local/lib (which doesn’t even exist on my system,
see the definition of bundle_lib).

SO, I created /opt/local/lib/, downloaded a copy of libjpeg.9.dylib to that directory,
and tried again.  This time I got the error message

PKGBASE: /Applications/FontForge.app
chantal:~ beesley$ dyld: Library not loaded: /opt/local/lib/libjpeg.9.dylib
  Referenced from: /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge
  Reason: Incompatible library version: fontforge requires version 11.0.0 or later, but libjpeg.9.dylib provides version 10.0.0
serving at port 8000

Curious.  Something still seems broken.

Best,

Ken





> For whoever has ability to close bugs; this bug, #2480 <https://github.com/fontforge/fontforge/issues/2480> (the original issue reported at the top) should be closed as a duplicate of #2405 <https://github.com/fontforge/fontforge/pull/2405>.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/fontforge/fontforge/issues/2480#issuecomment-144627090>.
> 


********************************
Kenneth R. Beesley, D.Phil.
PO Box 540475
North Salt Lake UT 84054
USA

**Comment by glyphobet** [comment] 2015-10-09 23:57
@krbeesley as I have already pointed out above, what you mention in your comment above is unrelated to the originally reported issue, and as such should be reported as a new, independent bug.

Sorry to be a stickler about process, but it's really poor process to discuss new, unrelated issues in the comments on an issue. @-mention me on the new bug and I will take a look at it.
