### ISSUE TITLE
Can't see any glyphs after opening Google NotoSansCJKtc-Regular.otf in FontForge July 31, 2017 version

### ISSUE THREAD

**Issue by ipsmile** [fontforge/fontforge#3188] opened 2017-10-19 13:37 UTC
After opening Google NotoSansCJKtc-Regular.otf in FontForge,  can't see glyph of any characters! Expect to see glyphs for all characters. 
Just download the font files from Google:  https://www.google.com/get/noto/
Unzip the download, select the font and open it with FontForge

![fontforge](https://user-images.githubusercontent.com/28075439/31773521-ded3ab44-b497-11e7-9648-a76c6df5b491.jpg)
Version: FontForge July 31, 2017
OS: Linux Mint 18.2

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [x] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by jtanx** [comment] 2017-10-20 21:32
This is probably a duplicate of #1534

**Closed** 2017-10-20 21:33 UTC
Labels: duplicate
