### ISSUE TITLE
Having difficulty installing FontForge on my Macbook Pro running BigSur 11.5

### ISSUE THREAD

**Issue by BR5770** [fontforge/fontforge#4793] opened 2021-08-23 23:14 UTC
<img width="1280" alt="Screenshot 5781-12-15 at 7 11 28 PM" src="https://user-images.githubusercontent.com/89426776/130531107-1d98c269-2cd7-4654-a713-d6d8c99b6502.png">

Have downloaded both XQuartz and the 2020 FontForge as well as the 2017 FontForge

My Mac is not letting me use "Open With" when I highlight FontForge to open it with XQuartz, but is only giving me an error message about 

<img width="1280" alt="Screenshot 5781-12-15 at 7 11 28 PM" src="https://user-images.githubusercontent.com/89426776/130531042-5a03087a-323e-4055-856d-8161c231de2e.png">

* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The FontForge version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by ctrlcctrlv** [comment] 2021-08-24 04:04
You have to disable that security feature, the FontForge `.dmg` is not notarized.

**Comment by ctrlcctrlv** [comment] 2021-08-24 04:05
Closed as duplicate of #4082.

**Closed by ctrlcctrlv** 2021-08-24 04:05 UTC

**Comment by BR5770** [comment] 2021-08-24 13:43
Thank you.

**Comment by acalism** [comment] 2025-04-27 12:07
`xattr -c ~/Downloads/FontForge.dmg`
then, open the dmg.
or
`xattr -cr /Applications/FontForge.app`
