### ISSUE TITLE
FreeType rasterizer does not work well when generating bitmap for too many glyphs

### ISSUE THREAD

**Issue by medicalwei** [fontforge/fontforge#2403] opened 2015-07-02 19:20 UTC
Steps to reproduce:
1. Generate all bitmaps for a Chinese font at once
2. Some bitmap glyphs are ugly, and if we regenerate once for the selected glyph of small volume it will be redrawn well.

**Comment by ctrlcctrlv** [comment] 2015-07-10 12:02
I don't understand the issue. Can you show an example or something?

**Comment by medicalwei** [comment] 2015-07-10 12:28
I tried to generate bitmap glyphs from subsetted and flattened Source Han Sans using "Elements -> Bitmap Strikes Available"
The example of ugly glyphs are shown in the screenshot below:
![screenshot 2015-07-10 20 13 04](https://cloud.githubusercontent.com/assets/74481/8618559/19c640c6-2742-11e5-811d-33da2bd85bfc.png)

**Comment by mskala** [comment] 2015-07-10 12:58
Duplicate of #685 .  Generating in small batches is a workaround.  Fixed in FontAnvil, suggestions on how to fix in FontForge in the comment thread.

**Comment by jtanx** [comment] 2015-07-11 01:57
Closing issue - discuss in #685 instead.

**Closed by jtanx** 2015-07-11 01:57 UTC
Labels: duplicate, I-bug
