### ISSUE TITLE
recent fontforge for mac os corrupts features

### ISSUE THREAD

**Issue by mjsharpe** [fontforge/fontforge#4104] opened 2020-01-23 22:12 UTC
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
Mac OS 10.14.6 Fontforge 2019-08-01[x ] The FontForge version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [x ] Steps to reproduce the behavior 
Versions of Fontforge compiled for Mac OS from August 1, 2019 and continuing to the most recent update in late November, 2019 appear to corrupt the GSUB lookup tables when generating otf files from an sfd. With at least ten different sfd files I've tried, the result has in all cases been an otf that cannot be used  to generate LaTeX support files using autoinst or otftotfm because otfinfo can read no information about the scripts, languages or font features. The otf files are also practically useless in Unicode TeX because fontspec cannot determine the features available and cannot generate its internal NFSS structures, resulting in only the most vanilla features being available.

Looking at what is happening in the otf GSUB tables, it appears that 
(1) ssxx tables are not understood properly and their contents are merged into rtla features or discarded;
(2) c2sc tables are in many acses simply discarded;
(3) other tables have metadata with two feature entries, like
   <3,3>  dflt
   smcp  dflt

where, I presume, the first entry is provided back to otfinfo and since it does not correspond to a known tag, the table is ignored.

My work-around for these problems is to make use of a second computer with a fontforge.app from 2017. One cannot open an sfd generated from a recent version of fontforge because the old version cannot understand the newest SplineFontDB version 3.2. So, my steps are, for each sfd:

(1) From Element/Font Info/Lookups, right click on any table entry and, from the resulting contextual menu, select Save Feature File.
(2) Generate a (faulty) otf.
(3) Copy both the otf and the corresponding fea to the other machine.
(4) Open the faulty otf in the old fontforge and select File/Merge Feature Info to pull in the fea file.
(5) Element/Font Info/Lookups and delete the old lookups at the top of the GSUB list.
(6) Click over to the GPOS list. You will have repeated good data there, and should delete any duplicate lookups. Hit OK when done deleting unwanted lookups.
(7) File/Save.
(8) File/Generate Fonts, making a new good otf. 
(9) Open thenew  otf in fontforge. You may notice that fontforge has made nice new names for the lookup tables, and you may wish to Save, creating a new sfd with nicer lookup names than the one you got after merging the fea file.

In the attached files, the starting point was XCharter-Bold.sfd in the folder 2019. The bad oft with corrupted feature lookups is in the same folder. The files in the 2017 folder were made by the procedures described above, resulting in a good otf with good feature lookups. The sfd in that folder was generated from ththat good otf.
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by skef** [comment] 2020-01-23 23:37
@mjsharpe I think the files didn't wind up getting attached. Github is picky about the files it accepts -- our usual workaround for that problem is to place the files together in a `zip` archive and then attach that to the issue. If you've never done that, or just not gone through the process recently, there's a short how-to here: https://www.digitaltrends.com/computing/how-to-make-a-zip-file-on-a-mac/

**Comment by skef** [comment] 2020-02-01 16:34
I'll give reproducing this myself a shot in the next day or two.

**Comment by mjsharpe** [comment] 2020-02-12 22:37
I've been out of action for a couple of weeks---sorry about my lack of a quick response. Here are my files illustrating the behavior under ff from 2019 and 2017. One more piece of data. I installed a mint linux distribution  (18.3) on a virtual machine and successfully installed fontforge on that (from 2019-04) that does not exhibit the bad behavior I found on the Mac version from 2019-08. I was unable to successfully install fontforge for linux from the AppImage---it installed OK and I made it executable, but it would not open when double clicked.
[sfdandotf.zip](https://github.com/fontforge/fontforge/files/4195354/sfdandotf.zip)

**Comment by skef** [comment] 2020-02-12 22:55
This would be an unusual kind of issue to be mac-specific but with the files we don't have to speculate. I'll try to give them a once-over this evening on Linux and we can go from there. 

Another user on the fontforge-users list also offered (on Jan 23rd) to help out on the mac if needed.

**Comment by skef** [comment] 2020-02-13 06:00
Some initial results:

First, when I test on Arch Linux with a recent build the generated `.otf` closely resembles the 2017 file rather than the 2019 file. Only a few hints and some anchor points are different, probably due to unrelated code changes.

Second, this is the ttx console output for the two `.otf` files in the archive:

```
Dumping "2017/XCharter-Bold.otf" to "2017/XCharter-Bold.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'name' table...
Dumping 'cmap' table...
Dumping 'post' table...
Dumping 'CFF ' table...
Dumping 'FFTM' table...
Dumping 'GDEF' table...
Dumping 'GPOS' table...
Dumping 'GSUB' table...
Dumping 'hmtx' table...
[skef@isolator 4104]$ ttx 2019/XCharter-Bold.otf
Dumping "2019/XCharter-Bold.otf" to "2019/XCharter-Bold.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'name' table...
Dumping 'cmap' table...
Dumping 'post' table...
Dumping 'CFF ' table...
Dumping 'FFTM' table...
Dumping 'feat' table...
Dumping 'hmtx' table...
Dumping 'kern' table...
Dumping 'morx' table...
Dumping 'prop' table...
```
Note that the 2019 `.otf` has neither a `GSUB` or `GPOS` section. That's the likely source of the difference; in one case one sees the actual GSUB tables and in the other one sees the those parts that can be reconstructed from other tables. 

Therefore, in order to make progress on this it is important to verify the very specific steps that generate 2019-type files. Note that supplying these steps might "feel dumb" -- it's entirely possible that the boring steps I just took to generate the 2017-similar file will be identical to the boring steps you took to generate the 2019 file. Still, we need to ensure we are on exactly the same page before we know what to investigate further.

**Comment by mjsharpe** [comment] 2020-02-13 17:38
To produce the otf, I used File->Generate with output as Opentype(CFF), with the following options checked:

  Postscript
Round
Hints
Flex Hints
  SFNT
Apple
Output glyph map
TeX Table
Windows-compatible 'kern'

On the older machine running the 2017 version of fontforge, the options checked were

  Postscript
Round
Hints
Flex Hints
  SFNT
PS glyph names
Opentype
Output glyph map
TeX Table
Windows-compatible 'kern'


On Feb 12, 2020, at 10:00 PM, skef <notifications@github.com> wrote:

Some initial results:

First, when I test on Arch Linux with a recent build the generated .otf closely resembles the 2017 file rather than the 2019 file. Only a few hints and some anchor points are different, probably due to unrelated code changes.

Second, this is the ttx console output for the two .otf files in the archive:

Dumping "2017/XCharter-Bold.otf" to "2017/XCharter-Bold.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'name' table...
Dumping 'cmap' table...
Dumping 'post' table...
Dumping 'CFF ' table...
Dumping 'FFTM' table...
Dumping 'GDEF' table...
Dumping 'GPOS' table...
Dumping 'GSUB' table...
Dumping 'hmtx' table...
[skef@isolator 4104]$ ttx 2019/XCharter-Bold.otf
Dumping "2019/XCharter-Bold.otf" to "2019/XCharter-Bold.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'name' table...
Dumping 'cmap' table...
Dumping 'post' table...
Dumping 'CFF ' table...
Dumping 'FFTM' table...
Dumping 'feat' table...
Dumping 'hmtx' table...
Dumping 'kern' table...
Dumping 'morx' table...
Dumping 'prop' table...
Note that the 2019 .otf has neither a GSUB or GPOS section. That's the likely source of the difference; in one case one sees the actual GSUB tables and in the other one sees the those parts that can be reconstructed from other tables.

Therefore, in order to make progress on this it is important to verify the very specific steps that generate 2019-type files. Note that supplying these steps might "feel dumb" -- it's entirely possible that the boring steps I just took to generate the 2017-similar file will be identical to the boring steps you took to generate the 2019 file. Still, we need to ensure we are on exactly the same page before we know what to investigate further.

**Comment by mjsharpe** [comment] 2020-02-13 18:20
Checking those options lead me to changing the options on the neww machine with 2019 fontforge to match those on my old machine with 2017 fontforge. When I did so, I was able to get good otf output once again.

This is mysterious to me as my new machine is a clone of my old one from a few months ago and I have no recollection of changing the CFF options. Is it possible that installing the 2019 fontforge on nthe new machine altered the default options?


On Feb 12, 2020, at 10:00 PM, skef <notifications@github.com> wrote:

Some initial results:

First, when I test on Arch Linux with a recent build the generated .otf closely resembles the 2017 file rather than the 2019 file. Only a few hints and some anchor points are different, probably due to unrelated code changes.

Second, this is the ttx console output for the two .otf files in the archive:

Dumping "2017/XCharter-Bold.otf" to "2017/XCharter-Bold.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'name' table...
Dumping 'cmap' table...
Dumping 'post' table...
Dumping 'CFF ' table...
Dumping 'FFTM' table...
Dumping 'GDEF' table...
Dumping 'GPOS' table...
Dumping 'GSUB' table...
Dumping 'hmtx' table...
[skef@isolator 4104]$ ttx 2019/XCharter-Bold.otf
Dumping "2019/XCharter-Bold.otf" to "2019/XCharter-Bold.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'name' table...
Dumping 'cmap' table...
Dumping 'post' table...
Dumping 'CFF ' table...
Dumping 'FFTM' table...
Dumping 'feat' table...
Dumping 'hmtx' table...
Dumping 'kern' table...
Dumping 'morx' table...
Dumping 'prop' table...
Note that the 2019 .otf has neither a GSUB or GPOS section. That's the likely source of the difference; in one case one sees the actual GSUB tables and in the other one sees the those parts that can be reconstructed from other tables.

Therefore, in order to make progress on this it is important to verify the very specific steps that generate 2019-type files. Note that supplying these steps might "feel dumb" -- it's entirely possible that the boring steps I just took to generate the 2017-similar file will be identical to the boring steps you took to generate the 2019 file. Still, we need to ensure we are on exactly the same page before we know what to investigate further.

**Comment by skef** [comment] 2020-02-13 19:29
> Is it possible that installing the 2019 fontforge on the new machine altered the default options?

I'm not the right person to give a conclusive answer about the *likelihood*, but broadly speaking its definitely possible and even plausible. 

I looked through the code a bit to see if anything was pushing for an "Apple" output default preference when compiling the Mac version but I didn't find anything. However, as it happens our build process has changed completely since that 2019 release and I didn't go back though the old code. I'll tag @jtanx here to see if he can offer anything more conclusive. 

In any case it sounds like we've narrowed this down to an output preferences problem, and although the project tries not to actively screw up those settings, it is ultimately -- necessarily -- the user's burden to set those as they need them (otherwise they wouldn't be preferences). I will leave this open for a bit so we can decide if there's anything better to be done on our end, but otherwise it sounds we've determined both the problem and the fix.

**Comment by skef** [comment] 2020-03-05 08:55
I've hunted around the code some more. The only thing I've found that seems like it would produce the default settings you saw on the 2019 version were some "hidden" preferences. We could spend more effort on the root cause but for now I'm closing this as sufficiently resolved. It can always be reopened if needed.

**Closed by skef** 2020-03-05 08:55 UTC
Labels: maybe-done
