### ISSUE TITLE
Missing release lock dc->child_mutex in DebuggerTerminate

### ISSUE THREAD

**Issue by ryancaicse** [fontforge/fontforge#4874] opened 2021-12-29 14:52 UTC
Lock `dc->child_mutex` is not released before Line 332 just like `dc->parent_mutex`?
https://github.com/fontforge/fontforge/blob/e873b8f43e35bfc8d2053534c4e071a956115819/fontforgeexe/freetypeui.c#L328-L339

**Comment by ctrlcctrlv** [comment] 2021-12-30 06:20
Closing as essentially a duplicate of #4873; let's keep all the mutex lock questions in `freetypeui.c` there. The code block here very nearly intersects with the one you put in the issue there.

**Closed by ctrlcctrlv** 2021-12-30 06:20 UTC
