### ISSUE TITLE
How do I correctly stroke an ‹f›, without getting a hole in the middle?

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#4049] opened 2019-12-09 08:51 UTC
I've so far found no fault in the new Expand Stroke implementation, but perhaps have found a case worth scrutinizing further.

My TT2020 font is based primarily on [IBM Selectric Pica](http://typeballs.com); I want to make an italic with a reduced character set, likely to only be Latin and maybe Cyrillic.

I got started tracing as I always do&hellip;

![2019-12-09-164520_2560x1461_scrot](https://user-images.githubusercontent.com/838783/70420651-27538d80-1aa3-11ea-8869-3f8a41c29750.png)

&hellip;but have found a case I can't seem to beat: letter &lsaquo;f&rsaquo;.

<img src="https://user-images.githubusercontent.com/838783/70420852-8d401500-1aa3-11ea-926a-fadbbaa774b7.png" width="200">

Seems no matter which way I stroke it, or however many times I &laquo;Element&rarr;Reverse Direction&raquo;, I always get a hole in the middle.

<img src="https://user-images.githubusercontent.com/838783/70420978-d1cbb080-1aa3-11ea-89be-379c7d03ef22.png" width="200">

Do you have any idea what I'm doing wrong @skef? Here's the file for reference. Use radius 10.

[f.zip](https://github.com/fontforge/fontforge/files/3938632/f.zip)

**Comment by skef** [comment] 2019-12-09 17:54
I'll take a look. Two immediate comments:

1. I'm 99% sure you can work around this problem by choosing to remove overlap by contour in the dialog, reversing the direction of the errant contour by hand, and then removing overlap on the whole layer by hand. 
2. Can you verify you're using a very recent version of the code? There was a late bugfix having to do with the direction of contours produced from open source contours.

**Comment by skef** [comment] 2019-12-09 22:51
RE 2: I just tried this on a "very recent" (maybe current, certainly current WRT the expand stroke code) and it didn't reproduce. In any case my intended fix for this problem was part of #4011, in the lines of the diff of `splinestroke.c` starting around 1633.

**Comment by ctrlcctrlv** [comment] 2019-12-10 00:53
Perhaps we're looking for different things @skef? The contours don't have a hole in them, (i.e. four contours aren't produced) but they are produced with opposite directionalities, which as you say must be corrected "by hand". That's hard to automate.

I tested on 3890b4762567b84cd57b6d03fb382ad7fdb3ad50

**Comment by skef** [comment] 2019-12-10 02:18
Oh, well, -- hmm. I just tried to reproduce again and got the described result. I was reflexively setting the nib angle to zero instead of leaving it at the default 45 degrees. 

Anyway!

Suppose you run these source contours through the stroke algorithm as described but with Remove Overlap -> None, no Simplify, and no Add Extrema.  Then you unselect all points and select one point on the contour of the crossed "f", and check the Element menu. As with #4050 you'll see that the clockwise/counterclockwise indicators are disabled. So this issue has the same underlying cause as that one: the Stroke code does certain things differently depending on whether a closed contour is clockwise or counter-clockwise and that code will fail if the direction of a contour is misidentified. 

It's relevant that the menu is *disabled* rather than merely *incorrect*. That probably means that `SplinePointListIsClockwise()` is returning -1. 

Beyond that, however, I'm not sure how to proceed on this. The existing algorithm seems to be intended to handle complex self-intersecting cases but sometimes fails for simple (in both senses) cases. I could easily write a fallback that a) checks to see if the contour self-intersects and b) traverses the whole curve adding up the angles. (Would adding up the angles also work for self-intersecting cases, possibly with a higher total angle amount?) But is that what's needed? Without some kind of reference we may be in the same place (albeit at a smaller scale) as with the old Remove Overlap and Stroke code.

**Comment by skef** [comment] 2019-12-10 18:14
I suppose one easy thing to try is to code up the angle-sum algorithm (it's actually already pretty much coded in NibIsValid) and compare the result of calling it and `SplinePointListIsClockwise()` on lots of different splines to see where any "true" disagreements lie. (So disagreements when the latter doesn't return -1.) I'll assume that open contours should be treated as if they were closed.

**Closed** 2020-02-01 11:54 UTC
Labels: stroke
