### ISSUE TITLE
SVG style is partially taken in account

### ISSUE THREAD

**Issue by Pecita** [fontforge/fontforge#2978] opened 2016-12-20 08:41 UTC
If you import this SVG into FontForge GW, the style is not taken into account.
`<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="-600 0 1000 1000">
   <g transform="matrix(1 0 0 -1 0 600)">
      <path style="fill:none; stroke: black; stroke-width: 40; stroke-linecap:round;" d="M 40,80     a 300,355 0 0 1 140,300"/>
   </g>
</svg>`
If you import it into FontForge "neo", it is partially:  "stroke-linecap:round;" is not taken into account.
It is not a bad idea to take into account the style but then it should be done completely. Otherwise it seems preferable not to do it at all.

**Comment by skef** [comment] 2019-11-19 21:55
This is a duplicate of #2007

**Closed** 2019-11-21 22:03 UTC
Labels: stroke
