### ISSUE TITLE
Some SVG glyphs completely hang FontForge when generating OTF/WOFF fonts

### ISSUE THREAD

**Issue by Azumgi** [fontforge/fontforge#3699] opened 2019-05-18 10:34 UTC
I have a [project](https://github.com/Azumgi/Material-Icons-Complete) with more than 5k SVG glyphs parsed from material icons site and 2 of them hang FontForge if you try to generate OTF/WOFF font with them. Generation of EOT, TTF, SVG, and WOFF2 fonts works just fine.

OS: Win10
FontForge version: 2019-04-13

I created a small project for easy reproducing which you can download here:

https://www.dropbox.com/s/8utpujylbl2yu5j/bug.zip?dl=0

I'll still paste the script here for better context:

```py
# How to use:
# `fontforge -script reproduce.py`
#
# Instructions:
# 1) Run script for the first time. All the fonts will be generated just fine.
# 2) Uncomment lines with broken glyphs definitions.
# 3) Run script again. FontForge will hang when trying to generate OTF font.
# 4) (Optional) Comment OTF generating line and run script again. FontForge will hang when generating WOFF font.

import fontforge

print("Initializing font.")

font = fontforge.font()
font.familyname = "Test Font"
font.fullname   = "Test Font"

print("Initializing chars.")

# Glyphs breaking FontForge.
# If you will uncomment them, they will hang FF forever when generating OTF or WOFF fonts.
# char = font.createChar(57344, 'uniE000')
# char.importOutlines('./glyphs/call_end.svg')
# char.width = 1000

# char = font.createChar(57345, 'uniE001')
# char.importOutlines('./glyphs/movie_creation.svg')
# char.width = 1000

# Normal glyphs.
char = font.createChar(57346, 'uniE002')
char.importOutlines('./glyphs/iso.svg')
char.width = 1000

char = font.createChar(57347, 'uniE003')
char.importOutlines('./glyphs/last_page.svg')
char.width = 1000

print("Generating fonts.")

# Working as intended.
print("EOT")
font.generate('./generated_fonts/output_font.eot')
print("TTF")
font.generate('./generated_fonts/output_font.ttf')
print("SVG")
font.generate('./generated_fonts/output_font.svg')
print("WOFF2")
font.generate('./generated_fonts/output_font.woff2')

# Hangs FontForge.
print("OTF")
font.generate('./generated_fonts/output_font.otf')
print("WOFF")
font.generate('./generated_fonts/output_font.woff')

print("Done.")
```

**Comment by skef** [comment] 2019-05-19 09:04
I have a preliminary diagnosis for this, which doesn't quite yield a code fix but I suspect can get you going again.

Here is `call_end.svg`:
```
<svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path d="M18.59 10.52c1.05.51 2.04 1.15 2.96 1.91l-1.07 1.07c-.58-.47-1.21-.89-1.88-1.27v-1.71m-13.2 0v1.7c-.65.37-1.28.79-1.87 1.27l-1.07-1.07c.91-.75 1.9-1.38 2.94-1.9M12 7C7.46 7 3.34 8.78.29 11.67c-.18.18-.29.43-.29.71s.11.53.29.7l2.48 2.48c.18.18.43.29.71.29.27 0 .52-.1.7-.28.79-.73 1.68-1.36 2.66-1.85.33-.16.56-.51.56-.9v-3.1C8.85 9.25 10.4 9 12 9s3.15.25 4.59.73v3.1c0 .4.23.74.56.9.98.49 1.88 1.11 2.67 1.85.18.17.43.28.7.28.28 0 .53-.11.71-.29l2.48-2.48c.18-.18.29-.43.29-.71s-.11-.53-.29-.71C20.66 8.78 16.54 7 12 7z" /></svg>
```
and here it is again with the path clarified:
```
<svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path d="

M18.59 10.52
 c1.05.51 2.04 1.15 2.96 1.91
 l-1.07 1.07
 c-.58-.47-1.21-.89-1.88-1.27
 v-1.71

m-13.2 0
 v1.7
 c-.65.37-1.28.79-1.87 1.27
 l-1.07-1.07
 c.91-.75 1.9-1.38 2.94-1.9

M12 7
 C7.46 7 3.34 8.78.29 11.67
 c-.18.18-.29.43-.29.71
 s.11.53.29.7
 l2.48 2.48
 c.18.18.43.29.71.29.27 0 .52-.1.7-.28.79-.73 1.68-1.36 2.66-1.85.33-.16.56-.51.56-.9
 v-3.1
 C8.85 9.25 10.4 9 12 9
 s3.15.25 4.59.73
 v3.1
 c0 .4.23.74.56.9.98.49 1.88 1.11 2.67 1.85.18.17.43.28.7.28.28 0 .53-.11.71-.29l2.48-2.48
 c.18-.18.29-.43.29-.71
 s-.11-.53-.29-.71
 C20.66 8.78 16.54 7 12 7

z" /></svg>
```
Note that neither of the first two sub-paths are closed by a `z`. Also note the difference in vertical line heights (1.71 vs 1.7). I haven't looked at this code, but FontForge's SVG importer seems to be tolerant of missing `z`s when a) the sub-path is followed by a move-to and b) the math puts the end of the sub-path back at the earlier move-to point. That's true of one of these sub-paths but not the other. Hence when you save an SFD after importing this SVG into a character, you get a 1024 open path flag value:
```
StartChar: uniE000
Encoding: 256 57344 0
Width: 1000
VWidth: 0
Flags: HW
LayerCount: 2
Fore
SplineSet
774.583007812 361.666992188 m 0
 818.333007812 340.416992188 859.583007812 313.75 897.916992188 282.083007812 c 2
 853.333007812 237.5 l 2
 829.166992188 257.083007812 802.916992188 274.583007812 775 290.416992188 c 2
 775 361.666992188 l 1025
225 361.666992188 m 2
 181.666992188 340 140.416992188 313.75 102.5 282.5 c 2
 147.083007812 237.916992188 l 2
 171.666992188 257.916992188 197.916992188 275.416992188 225 290.833007812 c 2
 225 361.666992188 l 2
500 508.333007812 m 0
 689.166992188 508.333007812 860.833007812 434.166992188 987.916992188 313.75 c 0
 995.416992188 306.25 1000 295.833007812 1000 284.166992188 c 0
 1000 272.5 995.416992188 262.083007812 987.916992188 254.583007812 c 2
 884.583007812 151.25 l 2
 877.083007812 143.75 866.666992188 139.166992188 855 139.166992188 c 0
 843.75 139.166992188 833.333007812 143.75 825.833007812 150.833007812 c 0
 792.916992188 181.666992188 755.416992188 207.5 714.583007812 227.916992188 c 0
 700.833007812 234.583007812 691.25 248.75 691.25 265.416992188 c 2
 691.25 394.583007812 l 2
 631.25 414.583007812 566.666992188 425 500 425 c 0
 433.333007812 425 368.75 414.583007812 308.333007812 395 c 2
 308.333007812 265.833007812 l 2
 308.333007812 249.583007812 298.75 235 285 228.333007812 c 0
 244.166992188 207.916992188 207.083007812 181.666992188 174.166992188 151.25 c 0
 166.666992188 143.75 156.25 139.583007812 145 139.583007812 c 0
 133.333007812 139.583007812 122.916992188 144.166992188 115.416992188 151.666992188 c 2
 12.0830078125 255 l 2
 4.5830078125 262.083007812 0 272.5 0 284.166992188 c 0
 0 295.833007812 4.5830078125 306.25 12.0830078125 313.75 c 0
 139.166992188 434.166992188 310.833007812 508.333007812 500 508.333007812 c 0
EndSplineSet
EndChar
```
If you add a `z` before each `m` or `M` in `call_end.svg` and `movie_creation.svg` (other than the first `M`) then `reproduce.py` doesn't hang. 

There are two remaining questions. One is why FontForge does sometimes close the contours. I suspect this has to do with sanity-checking code. The other question has to do with the hang, which is in `autohint.c:_SplineCharIsFlexible()`. That function has a loop that is supposed to catch open contours
and handle them as a separate case, but it isn't working in this one. 

@Azumgi: Obviously FontForge shouldn't hang in this or (almost?) any other case, so we should leave this open. But the best way forward for you is to sanity-check your SVGs, editing them if needed. My understanding of the spec is limited but I believe these sub-paths should be explicitly closed and the similar sub-paths in your other example files are explicitly closed.

**Comment by frank-trampe** [comment] 2019-06-20 18:01
Did this get fixed? I'm using 937af488df9a4c5c042eb4ed9342320d9ff6c9d5 on Ubuntu 18.04 for amd64, and I cannot reproduce the problem.

**Comment by skef** [comment] 2019-06-20 19:18
@frank-trampe did you uncomment the relevant lines in the script? I fooled myself the first time through by missing that.

I was able to reproduce the problem around the time of my comment and I'm not aware of any fixes going in in that timeframe.

**Comment by frank-trampe** [comment] 2019-06-20 19:24
Ah, I was just running the script in the bundle and did not examine it in any detail since it seemed to be working.

**Comment by skef** [comment] 2020-02-03 19:02
The cause of this problem is a corrupted SplineSet that starts in a way that implies it is closed. However, instead of a loop it leads into a point linked forward and backward to itself. It would be very time-consuming to protect every SplineSet routine from such corruption, and more productive to track down what is corrupting the set, which starts out as fairly ordinary open contour.

**Closed** 2020-02-21 10:23 UTC
