### ISSUE TITLE
Missing char in Font Properties Menu, Chinese version

### ISSUE THREAD

**Issue by extc** [fontforge/fontforge#5002] opened 2022-05-03 04:07 UTC
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [X] Screenshot
- When using Fontforge Chinese interface, a character inside Font Properties Menu 
[67E5]找 cannot be shown
![圖片](https://user-images.githubusercontent.com/8214015/166402703-ca5fa408-03bf-4a58-adfd-b63a88550846.png)

- [X] The FontForge version and the operating system you're using
- Version No: 20220308 for Windows, under Windows 10 21H2

- [X] The behavior you expect to see, and the actual behavior
- I expect to see the char 查找, which is not included in normal Japanese Font. 
- The missing character [67E5] problem also exists in messages inside the Warnings window.
- [X] Steps to reproduce the behavior 
- Use Fontforge for Windows
- Change language interface by adding set LANGUAGE parameter in fontforge.bat:
set LANGUAGE=zh_TW

- [X] \(optional) Possible solution/fix/workaround
The menu font uses Yu Gothic, or Meiryo, which cannot show all CJK characters.
Change the menu font inside the Font Properties dialog box to 'Arial Unicode MS', which includes all CJK United Ideographs.
The menu of main Fontforge window is using 'Arial Unicode MS' already.

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [X] \(optional) Possible solution/fix/workaround

**Comment by extc** [comment] 2022-05-03 04:23
The missing char. problem also appears in the Preferences... 
![圖片](https://user-images.githubusercontent.com/8214015/166404436-5be9afb8-ba75-4976-af64-b08e3da227c4.png)

and Apperance Editor...
![圖片](https://user-images.githubusercontent.com/8214015/166404355-ce1bbb37-dc45-4eb4-8951-cdc4ae55621a.png)

**Comment by ctrlcctrlv** [comment] 2022-05-05 18:03
What font contains 啟 on Windows?

**Comment by Letheward** [comment] 2022-05-06 09:11
This also happens in `zh_CN` locale, see #4983. The workaround in that issue appears to work with `zh_TW` (although still not right):

![result](https://user-images.githubusercontent.com/59071629/167102352-36a5adba-3b62-48b9-87a6-3c9e30551c07.png)

**Comment by ctrlcctrlv** [comment] 2022-05-07 00:37
Duplicate of #4983.

**Closed by ctrlcctrlv** 2022-05-07 00:37 UTC
Labels: Windows, UI
